### ISSUE TITLE
Error in documentation on using fantomas as an external tool in Rider

### ISSUE THREAD

**Issue by ursenzler** [fsprojects/fantomas#1455]
Just a small problem in the docu:

I had to specify `fantomas` as the program with argument `$FilePath$` after installing it as a dotnet global tool, not as shown in the readme as dotnet as program = `dotnet`, arguments = `fantomas $FilePath$`.

**Comment by nojaf** [comment]
Hello Urs, thank you for taking the time to report this problem.

If you are talking about the ["Using the latest version inside Rider part"](https://github.com/fsprojects/fantomas#using-the-latest-version-inside-rider), in my opinion, you just made a different assumption about how the tool is installed.
The installation command listed in the docs is the one for a local tool (which is recommended). You installed it globally, so yeah things are different.

Are you interested in submitting a PR to clarify this?

**Comment by ursenzler** [comment]
Ah, I see. I copied the command line from nuget.org, not the readme and that is by default a global install. The readme is consistent in itself.

btw: why do you prefer having it as a local tool, not global? Are you using different versions?

**Comment by nojaf** [comment]
Well, Fantomas is still a work in progress and it tries to implement the [MS F# style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) by default.
That style guide is also a work in progress, so both evolve over time.

Next to that, in its current form, Fantomas works best to use it right before you commit your code.
But if you then have one version for all your projects, some unrelated code might change because you bumped the global Fantomas tool. That is why I personally pin a version for each of my projects and make it explicit when I bump the local version.
(It also helps to see if nothing major broke between versions).

**Comment by ursenzler** [comment]
I see. I use fantomas only in one project so I never run into this problem :-)

I use fantomas much more often than just before committing. I'm still new to F# and rather often struggle with layouting my code (some old C# habits probably). So I run fantomas in such a situation. Works very well.

**Comment by nojaf** [comment]
Nice to hear that, thank you for this feedback.
