### ISSUE TITLE
string interpolation part crossing max line length introduces new line and lots of whitespace

### ISSUE THREAD

**Issue by johlrich** [fsprojects/fantomas#1511]
Visual issue only as the new line and whitespace is all inside of the expression part, the string literal is unaffected.

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBnLsATgIYDmiAwrAHbWLRYCWNYAvGACQA6kAIogDNiAV3RYAotXgAHWI2pZcABUKwCcdKwAWWLNNwBuAILQ4whQDliAW0SsApLmD4iZRCbMKAdFdsBfY1NYcywAaUQATwcnFxJyD2CFcIivADVidGFEPx4uQi5qPILMHFxEQgA3RmhEAGUCOMoaOgZmajZOHn4hUQkpWXlFFTVYDW1dfUDPLF87R2dyqpr613igkJ8bbKnEsMjohcrquoa3BJDktIysnMgiwvzqSAAacCgy3XlSXFQwAG03hBQBAQVAOFgItJkGhIIMXoCQZAOBVrtD-gjQQAGV6g0GQACSUkQClqjAAXsgcbiIAAWDFgAC6CL8VKB9KREKhv1hCnh1KRKMyaIB1IgAEZWbjIABZYgADwAMvJEAriaQsFo%2BaKxQAmTH0pmglkI4FS8GQtGQABGsFg6C1eORqN%2BItFOsleNqiGs1TtNCMfXgAHkBEq6A7cUJ0GUDczJabHZzLTa7RGIALnWhXdSAMwexG1aTEGoAIUEREQSmIJFsWHKaZBWEIWVjRvj7PNXJhKft%2BYzQpd9Np%2BfTheLiDLAgrCtgAHdytBiGVCRVRsQmDQGxAmy3qYaQcbQQnEZ3k7bex3BVlB6KwABWEdQMel8uERAAVWkUMIi%2BX1FXi4bk8j5RjGe5xiaHZJtyPYNv215ZkOYAAGyPpAz4Tq%2BlDoEuuBUNQ%2BDNgwRBbmAoGIK2B7tvyp4weecFOgOiG3gA7GhGGThW0rela9YgRkYG4vuECHiCx7prR3b0X2jEIeit4ABzsUWL5Tm%2BVDoJu-HRhR4FtpBNHQVJqYyVewpIQAnMp45GAIdaEFQ1jWMQpE7rpQkQUeUEWnRJmXpm8natiSHoSpmFqXU3q%2BppwFIeRlEidRZpGVAsGmQF2a4mKEohRhtn2V6PoaFpSFuQlYCiWyhk%2BcZF40WZN7au6IWEkgChBtQAAqhARAA6owGqkfFelUQZyU1al0n%2BUxgXUmKea5WFRiqOY8D8OgjA%2BvZrnNu5oLCRVSWJhNPJYAxDXMdqNJobKcr4gInVaMS4g6bUWhEFg-XwINj40vqI2JWNx1dlAcLpTNmWgmKD4hbdhICIwcpBt%2B65EOIcrSG%2BuC4G0pF3v9Hn6V51Ug6d50ZUhYqobD8oAEr0EQ8BfT9SF-eVlVgOJYIpWT4NyZDIJimxNNyvTcCEPAFjCNYvGECG%2BJ1tYPyPmK7NHSePPWL0jAbXQABiRDObo5SdT5fPmbeYpKSFYuM9K2u64gBuEEb21odAWjVsW9kAPqzow32amrQMaydYPTfzlNWSLy0kBEQaEEq%2BDM5qv0E-tnlid5pPh-VFO3nqN3yrHxDx4njD4FLMvlPLivK5TwfE%2BNpNa2IOvKs7rsm2bEcW26OW3pAJdl0nWD223jud%2BubshR7XsMOUfsB4NjdZyTlq52aF2zbiOrNYPt3pEKJbyPAXwp6RbMA4dIcSTzm%2BOtvAsQDqC0H-KevmK0NAn1I5-L6nVm6cQQHQ5lzDkYdeTm0atSHU10Ra8DUAAcWwOjTGiBsZtAvo%2BfGq8qrNzPH5POEMkI6hhgfB2yoSyaWgAAaxLCQOh2BcAdVqFsDS0tYq3mGoTUaTdgaELqlvfObpqaDwsIgWcjsyxYHnMSU2UJujyAGm0IwUhuLV0IPXbhAk9ogMzvggRvkhGPxEbA4Wg9wiIGkPdR6xJCRsNsGGSkcVdF4M5tnDeUDe4wN3tbd%2BcoXo%2BlwFobBQD3HgMkpNIhwiSEF2joPUk1BSCYGWqQaWxJPqICtNKBALidE6QiZ44x5M4mihzMFQeRgNqkGoJ-ag39qCklqeuYQb5OqwFapk9cuNtKCQzkTNeBCSnQMurmAeooh5iHKNQHpFQVQ0FIBo2WSjqAqJoNo0UPCBl8KGUY2qpTI63hzPvSZ48mDOIVDYK08BiAUE0jjZJEipHKiGm46%2BYDikHNGTvUEOY36TN4BXYgVpMBBIrloWoEQFDyjeYUj56s74nWJMGUMyp6gREwIcvuuZ4GD0kKi5xpEYCEHQAISART14jJ8WM3EOZyGTPqIQaoY88lwv6foo0bwGRUlhLgPWONfjxT8EAA)

#### Code

```fsharp
let storageConnection = $"DefaultEndpointsProtocol=https;AccountName=%s{storageAccount.Name};AccountKey=%s{storageAccountKey.Value}"

let serviceStorageConnection = $"DefaultEndpointsProtocol=https;AccountName=%s{serviceStorageAccount.Name};AccountKey=%s{serviceStorageAccountKey.Value}"


```
            

#### Result

```fsharp
let storageConnection =
    $"DefaultEndpointsProtocol=https;AccountName=%s{storageAccount.Name};AccountKey=%s{storageAccountKey.Value}"

let serviceStorageConnection =
    $"DefaultEndpointsProtocol=https;AccountName=%s{serviceStorageAccount.Name};AccountKey=%s{
                                                                                                  serviceStorageAccountKey.Value
    }"

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas Master at 03/06/2021 17:13:59 - f828c652049a8d558b06c613d5a7261bd973ab96

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by johlrich** [comment]
Ideally if the expression gets formatted and is still 1 line, we could allow it to be kept in place. 

If it needs to be multiline, perhaps they should be at start of line and indent based on its own context only. 

Thoughts? Happy to try and help again if we come up with a desirable solution

**Comment by nojaf** [comment]
Hey Jonathan, thank you for reporting this issue.
Interpolated string expressions now add the indent and newline when the expression is multiline or the max_line_length was crossed.
See 
https://github.com/fsprojects/fantomas/blob/f828c652049a8d558b06c613d5a7261bd973ab96/src/Fantomas/CodePrinter.fs#L2673

In your case, the latter happened. You could easily change this and remove the `autoIndentAndNlnIfExpressionExceedsPageWidth ` function call.
That will of course lead to different results for the existing tests:
https://github.com/fsprojects/fantomas/blob/f828c652049a8d558b06c613d5a7261bd973ab96/src/Fantomas.Tests/InterpolatedStringTests.fs#L82-L110

So it is not that easy to give here a good answer.

When I originally went with the implementation of interpolated strings I kinda winged it as the style guides did not have any guidance at the time. Could you perhaps raise in https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting what needs to happen if the construct is actually multiline?

Once we know that, we can act upon this. If the guide does not dictate any extra newlines and indents than the fix is quite easy as described above.
