### ISSUE TITLE
Delegate with many parameters result in a compilation error.

### ISSUE THREAD

**Issue by MNie** [fsprojects/fantomas#1514]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIDqAlgHYDMATAMICGANswEaPQDWYAvGEmaIA5o3R5YAMzAAKAHKMAzlgqUAgtnJ0AKjjwAqMFXRhDx00conDC5ZlUattXbgvmzVt54-WwtlVSOOnpevsYAlGAAtAB8YGywsMyQADTgUIqI6OhUwoqoYADa6RCgEOVQACRYuAWQxqkl5ZCVAG4sAK7IaMUVFQAMaX3NAJKUSFb45ABeyEPDYAAsTRAAuk0AvvOlK1U13VAN281tnQe9CwCMxxWQALKMAB4AMlSIz4iUwugAFo0LYEutH6u3WFS2TTKfRa%2BzqCSS-2hp2YXQKF2GtBuzXwiCI5DgzFg6nQAFFxgB5SSvShzXYQSQsTKgzbHKG3ap6OGJZJYlrtFHnOlgahYiCQfDYTiIABCiEksAATogAAqMBWMEjiBWI4boBVdZng1m7GGctCQeE8k3I1E9IWLUVQCVS2XypXPWAAd0QCugSkQY1asD9OSJOr6eoNwzB5QhFTZJ1h5st4bFNsFAIArI7xZLoDK5YrEABVbC4X3%2BwPBsTkMOOhnMJnRlmQ61JqAp3nptFCgBsOed%2BddRfozCUinoROU%2Bug6EVqfKDabfRjEDj5QTafbFu5C75Zx7AIA7AO8wW3Yg7ri2D6F-TGYhDbHjcNTbVk7uu-zbUUhQAOU8XULJVJ0JSg7zAJdH2bI1W1fDl3w7T9rW-DMFgATkA-M1EkLVJyIIhGAgyNoJXFt4zbM0kIRL8DztAFLkGIVcyAi8cTxAk6yFKCnzXF8kW3TsULo38GOuZjB0QHCtXY-Eki4gESN4sB1x2eDBOQ%2BDUMPK5MWYsYJnQclKG0BV7HIX4IJ4mDnzggSqJ3GjhIFHThkuEUJLPNQFVgDpxgAEUQZhyDxLViP1UiKlXFT%2BPZbcjmcn90T6S4HWYh5HhGSRtB%2BT4SUbRB8B%2BRV0AoeBLMdRYQRsvi7LihyEq0kTkoqS5s3Sp4xkkchHnJcsxEVElHmwJVFEUWtwMdTNqrI2CKPUhqrD3bt6KufsOseAAlRA4AVeAyoq%2B0Zqi8iN0oxD6iW2iXNWtyTw27bdvgOQOiIG8FUpEZxCIfJHUuZTVLATc9gcogOmYHJgppAAxRVCOyH0XFpJqbtEq4AOYx7FXgO5wcht5YYVeGwpzaAfjVTgtQAfU9chyr%2BAHYsTRb0GW7TbpSzCNu89VMHJBVXmUA6-kq47ymiwHgbfA5LtZ66kqFYEcwynnGD5gXyGUF63p9T7vt%2BoV-pqmK6uZi6wYh8gocQQnicRzl5bQjFxIBSBVfVwX0Fxy3rdtsQSeYsmKdnH0abpyzGdNrcWbZ5rFb012MoANTOaUqHgXJhYgqrI-m%2ByLsapF2bRjEPMTp5ob82cJrT8ZM-DkWjtzs6FoLq7EqdvpaDS8vHn82B0AAcSyIaRsQMaJqzqaxbWU61PzmWhJRhWAVodrE7xq23mlQluGldVuCyRRjPwDVEFA17Ju4h9m-n%2BqLqXou49X9bXbkRBPWt2V0G9T4kcC7qlALITTUOMK8OsFQGwBNZWatk8730XppJ%2BqMWrlFoPdV2ABpRAiBsBZRyp8MYp8SDUmRgsGBJ05otwXnUQu7Ji6oIgLQDGvd8p4kUD8KeTdjaS3Oogpyy9O4VFoFzV2UwvhCG8sIV6nxSqIDYHcBAZDhgUPFnPIGfCuQCOQSvBY1AmKuzUMFYQlBK6UGrkSKYJixAdCVNoWABlZE1gUuQm%2BPCmbRwfkg%2Bhz89EuwWG7CGPpKA1laO8IkwhwHvQAVQYBU4rJuNgbVeBZt%2BFWkEa5PodBlab1Ic8DUbB4CMFHLAcaXx36fzeAkgqt8NGtzSbHFBQpqBlwCf5TWjA2BCDYZrH4%2BBMBWCeNU5clC4HUIQXUT48BKSkPwFgIQjTdHDGoD3AJZJplUiqaTBUzBJCQFqVLBCDTHaZIqNQdeAS5kKnxF7JRwzIpqPBOkVY8x6iKGhuNAoPENhAA)

#### Code

```fsharp
type SomeWin32Callback = delegate of (NastyWinApi32Type * int * int * int * NastyWinApi32Type * int * int * int * int * NastyWinApi32Type * int * int) -> bool
```
            

#### Result

```fsharp
type SomeWin32Callback = delegate of
    (NastyWinApi32Type * int * int * int * NastyWinApi32Type * int * int * int * int * NastyWinApi32Type * int * int) ->
    bool

```
            
#### Problem description

I want to create a WinApi32 type in my application because this type is a delegate that accepts 8 nasty WinApi32 parameters after Fantomas autosave autoformats generate not compilable code.

I assume that in such a scenario it shouldn't format it at all(?) or use some indentation in new lines.

like:

```fsharp
type SomeWin32Callback = delegate of (NastyWinApi32Type * int * int * int * NastyWinApi32Type * int * int * int * int * NastyWinApi32Type * int * int) -> bool
```

or

```fsharp
type SomeWin32Callback = delegate of 
                               (NastyWinApi32Type * int * int * int * NastyWinApi32Type * int * int * int * int * NastyWinApi32Type * int * int) -> 
                               bool
```

#### Extra information

- [X] The formatted result breaks by code.
- [X] The formatted result gives compiler warnings.
- [X] I or my company would be willing to help fix this.

If this is indeed an issue I would be glad to help fix it : )
#### Options

Fantomas version: `4.5.0-alpha-001` 
Master at 03/08/2021 19:16:36 - a2fd887e67becc7c9497a0e6c7581de3b541f902

Default Fantomas configuration

**Comment by nojaf** [comment]
Hello Michal, thank you for reporting this issue.
I would expect the output to be:
```fsharp
type SomeWin32Callback = 
    delegate of 
         NastyWinApi32Type *
         int *
         int *
         int *
         NastyWinApi32Type *
         int *
         int *
         int *
         int *
         NastyWinApi32Type *
         int *
         int
        -> bool
```

in this case.

To solve this, there are two parts.
The first is moving the `delegate of` to the next line when it crossed the max_line_length.
https://github.com/fsprojects/fantomas/blob/a2fd887e67becc7c9497a0e6c7581de3b541f902/src/Fantomas/CodePrinter.fs#L3617-L3622

Change this to:
```fsharp
    | ObjectModel (TCDelegate (FunType ts), _, _) ->
        let short =
            typeName
            +> sepEq
            +> sepSpace
            +> !- "delegate of "
            +> genTypeList astContext ts
        let long =
            typeName
            +> sepEq
            +> indent
            +> sepNln
            +> !- "delegate of "
            +> genTypeList astContext ts
            +> unindent
        expressionFitsOnRestOfLine short long
```

The next part is trickier, because of the long tupled definition I would also be splitted on separate lines.
We already do this when there are no parenthesis in `genTypeList` ([example](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIDqAlgHYDMATAMICGANswEaPQDWYAvGAB0ATgMoQISZogDmjdHlgAzQSLHj1YAHKMAzlgqUAgtnJ0AKjjwAqYaI3qq6MDdX3xj57bVuPLu261dfSpjU1oLXE9XAN8vALBY6J9KJz9ve0T-N209TANQ80sorIyU4vSNRzi3AFoAPjA2WFhmSAAacCgdRHR0KmkdVDAAbU6IUHtIABIsXCHIR3ax8WmANxYAV2Q0UYCABg6AyABJSiQU-HIAL2RDtwAWZYgAXWWAXzvxp6gZy3nFz4rKbrZhbIa7NwARkB6kgAFlGAAPAAyVEQyMQlGk6AAFksAgAOPbfV7qD7LCYaaazbZQJotfFU4GbWkQ%2By0GErfCIIjkODMWBGdAAUTOAHlFKjKLdvhBFCxuiT3oDKbDfnM0JB6a1OWsWeDZWBqJyIJB8NhOIgAEKIRSwISIAAKjCEjBI8iEjPs6CEWyVZJV32pf012q9QJBYJ2hvuJqg5stNrtDuRsAA7oghNBdIhTqtYNm%2BoLw%2BofX77KTxOT1KqgTT5mHdczQazDQBWONmi3Qa22%2B2IACq2FwWZzeYLcnIxbj8uYioryopQfVtK1zR1y8jrYCADZOwme0n%2B-RmLodPRBXpfdB0PaS%2BJZ-ONJWINXxLXTSuG%2Bv73qWwaAgAdn3bte2TRA4R5NhM3vOUFUQf0q0DSYv1DH8my3AC3AJEDEz7B0LwFShYLAR8EIXAMlxQ%2Bs0IZDD9WjAIAE5cJ7QxFA9C8iCIRgSLLcjn0XGtlxoul0M3BiRkNSEDkNLs8PA7leX5adDTIxDX2QplRLXOiJP-RioWhOSD0QdiPSUvkWlUgJ%2BI0sA3y%2BaiQzEvSUMwwz7EhDk5NOc50DFSgzCEPJyFxEj1IopCqO0lzdI3dzJLZDRIWNEzQMMIRYA2M4ABFEGYcheQ9PjfQE9QXwcrS1R0gF9KjKSAkhWM5IRRFjkUMwcUxYU50QfAcXtdAKHgcK43uYkos0mKariurEoMxqoQ7VqkVORRyERMURzke1hURbAHR0HQp2IuM20mwTKOE5yNSgeamQ8pavL3VbEQAJUQOAhHgEaxpjS6KqE98RLmlJf2bBrkvUSFgLez7vvgTQNiIaChAlY55CIQY40hezHLAD8fh0ogNmYPpCulAAxe0eN6TMIhlBaoeknC5IR%2B14DhMmKbRGmhDpkrO2gHEXU4D0AH003IUa8Xx6q6zB9AIae6HxEhFi3sy11MDFIRUT0P68XGwHxEqgmieDO6FnB%2BjFrViBaFko42u1xhdf18g9GR1HMwxrGcek%2BWZsV63SfJ8hKcQfnBYZv47ZZgJaGMo43Y9g30G5iOo5juQhbkkWxZvTMpZl8Lg5u2LrYetVVcNWgfJdpEADUWStKh4H6I2SImiuQdu1ca4jJL67SpvESpnKb1O9uzi7svjYBvunKrwfbfq7c3FoFrx9y2B0AAcR6fbDsQY7Tu787TZeYGV9m63Gw3rD2RWl2ecjtErQFbgrVdbgeh0IFfAbpECERRmdNS8Fl6E1Bg-cSzNN7slekcTQiA0xRxtOgDMmJGb5Q2pQMKp1DBnEgr7IQgcAiRSutFSu99VyPwQc-DQtA4ZHAANKIEQNgDqXVMSnGASQKUTM3BUKBtdfuq9-jr0YZ5ZhbNx69V5DoHEl8l5TSqiHT8OkGGPRHknTWRxLhYikJlaQKNMTDUQGwOECBhH2FEWbW%2BMCB7fjcro%2B2hpqDOzcJAQwhVpCUEnpQaegpLgBLkBsB0ZhYB%2BQsZOGyIioHqItrA%2Bh8D3GJzcNQFOPi-EekoJOVY6JBTSFIWjPBVBCGXgikk6h01aGhzSW42ueismNx8VnPoQjkRujYPARgJ5YAnSxKg9BaIal9WgZbVCrkEoZMQRoagY8fG5S9owNgUhFFexxPgTAKQkQTKfGImhEi6HzExPACUQj8BYCkCrVp9hqA7x8aKS5kpxnCyEMwRQkApmpNcXMlpHiAjUFfj4m5Qg%2BSZ1sYc8qjiySdGeHcBYOgqYnSGOpN4QA))

https://github.com/fsprojects/fantomas/blob/a2fd887e67becc7c9497a0e6c7581de3b541f902/src/Fantomas/CodePrinter.fs#L4246-L4299

Add something like:
```fsharp
        | TParen (TTuple ts'), _ ->
            !- "TODO: something clever"
```

Are you interested in submitting a PR?
If so please check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#getting-started-with-fantomas) (and add a test to `TypeDeclarationTests`).

**Comment by MNie** [comment]
@nojaf thanks! I will take a look if I could prepare something : )

**Comment by nojaf** [comment]
Thank you, feel free to ask questions you might have along the way.
