### ISSUE TITLE
Formatting of Bolero/Elmish `concat` doesn't match other formatting

### ISSUE THREAD

**Issue by kojo12228** [fsprojects/fantomas#2108]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMA3AlogO5gC2Ci6Y8%2BAzgA4CGW0AFmALwA6ATlwHYQIcftGZgA2mHqSwzLDwB0AA2XR0jWrVVgukLPiyY9YALqTeAodZs2siAB449AYR6JmiMADliYAAo8sABWiNBYepaCtramUVExtjS4svJKquqa2sq6kABGsA4m5hIJiYkAZrA8pLKw-Iq0AK55pIZgABQVTYIA%2BmAAtAB81HRMLOwAyi1tWIEhYVgAlGYWfNHlmwZGiABihOjwZBRUNAzMbPHrmzciR%2BRI6IoAojxBfNc35QA8AD5g3VEBnqZS%2BN3%2B3nqXmGYEQpHoWAAnqCweV-pNYKQvKRaABzQYjRBvaqQgwVAAijH4uKJZDxnUBYH6MLO4zYYBcmEYPFe7yWKLBcU%2BN3MQoEkAANOAoLRsAZqbRUJJpRBQLZIAASJH0ZBoSD4fhYSUqoSa3CMdBNXXKxIABiliUgAEl%2BEhDZN8AAvZAOmIAFhNEFMJoAvr7VYGoFrETqlfrDcb1RrzZbrRJIxAAIzhmyQACyjAcABkDYgi4hqVhWImYpmAEy2yPB6xhk1q3PR2N6ivwADyFRL-EQkyRmBr1jNFqtSvTiTrOYnz1d-cHPozGAqkCboZz7Ynnet%2BVgsHQ49NyanafXAGYF6aXbKeFh9vwLb4iOhS2frAorduW7ukaatqh4FCe35Rim05oLO-p3hAkCTHC%2BBwOg9QAIJYEufYDl%2B8EAhasr-kIrbWHu54gXGYGnnek6pjO64AKz4YhTDQIgABCiBVO4-jcowWL2DwEEQL%2BiDERApFCORCEHlRx40UBF70TB64AGwsZMbGcdx1RlrARBEmIsourgsBiMC-AiWAYkSWAUkRkmlF6tREF0dBNoxAA7Jp2lcTxiAAKr0DqPDGYgpnmcw%2BD1NZFSEeJsQ7m2SnOVArm0cpHmwbYAAcvmMOx-l6ZyWQuPUtC-uE1RxQldkOWAMlRmlR7gZlUFXokACcBVFbp7h5nCeRErV6BEUlAEpU5MagQpblZZ1tb2uurGFTpAXlWhVn4fFY2JTYzYkYB01dulc3tZeDGJJm2YrVpa3oRUQnlaQpCMNZtkTUdU0di1GVKR1V21vOd1%2Bf1w7IahsU7XVX2Scdv0zfJbUA5dqnXbeoMPU9RJIW0UPbeun0HclZGpUjLnnajKmebYmZ%2BixLpulgvb8AAKjwiIAOqGNWMN7fVCP7n9VNJoD6O1sxWPsehQQ9PA5KUPgswjfhxPWId8M-cLFNQAaRoXTTOU2JmGkrQWDhOhUbOsBWzx7ZMrDVFgPPwFW1l%2Bo2cP2ULFG6-GBvU9l66Zj55uFi6FT4A4vahcw1TPA49DuFoMWE4kjFeyTk1kydh76-N4u0yb%2BXhw4ABKYTVPArvu-hnuC9rfunQHhdo8X1iZj1ZeV3APDwN4TSkMNPD9k69g4tZmaN7niMt6QTToAYn5Drs1RvVgQls0jhvB3Oy2Or31d5ovy%2BlmvNTyKrK1sPx4REr0RD4G71Yz9J5MtwXu%2BLbYda3Y6FtZY8EYIiXsPASyVVrnzdcDdvYNSasBf2X8g4-xsHWEGADCxAJAWAiBWBB7DyJGPCeip8LTzgb7WSLUF5L3wCvPY68r48G3rGb%2BQNf6Y0dNg0B4C6BYBPrQ%2BhF8N5CWsjAVgd8hKP2fu7N%2Bjk575wTGwiWv8GZlwAGqXg4gaGg1IoHWVylnDWpN355zjMgsW7djbWDrFLTBDhdg9HCGnbRroDS4n0fXIxQhNY%2ByblQpBSiUHsLQWbex5JYBYAAOLYETsnRAqd6ieKYt4oMJj5E6xbv9SxRt1x1jDgA0%2BdDSwcTQtAAA1hxYBFTsC0FZpMASiBNpD3TjEXa41s7fVnpk2aKMcl7xiHWUujp3z0K4lgQyFYWGIEVlHfghg07oVdINQhPBSHrnaftYxOdTEKORopfpqCbHd0dAAaUQIgegVsbYVhdA0rEq5RodO2V03ZPTzFBMOSE6w14D4xHzIWe2bRaCsGSYkWBnStbdObr0g5HYi7WKENef%2B-yPTUkwLLXEQ8Kwu0QHkPMFAnlbJ8ekxqH9YVt1yYka8GD-noU-LifgjigRpw9Iy5gTR3Bs1gEzHF0VoYbNhpCvx0KAlZNFvCqxN5OF0qXkSV8BhcD6WpCskesyDQLIqkSuRZKzGUz6ZKqlMRrxqMKbQ1cRYBJ5HgIwTksBaDuNGXhQVAsKH%2BOav7bJhqBm2GvHY-55I6CMDyJgIFdBWCTERIaQs2q3Wio9eKg1%2B4EU3jCf885lzeWGhdFUqkbBY3CvgeS-ZlKfU2GvAU-5pSqTlNXLQWWsB5a%2BEqogeAAiz5DjiSnB1Wq1Y8D-HGt5MKS3KI7ki4ZVbuTFXcIG2g0AeDKwNJ4eAgV5n1EVpkYBlkC0vKhUOsVFLR2IogNeE5qKFAoX4YS-mzySUtmlKYX0%2BpaC7AdUqTZIAQxAA)

#### Code

```fsharp
let view model dispatch =
    concat [ p [ attr.``class`` "title" ] [
                 text "Create New Project"
             ]

             div [ attr.``class`` "box" ] [
                 form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                     titleField model dispatch

                     cond model.Error
                     <| function
                         | None -> empty
                         | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
                 ]
             ] ]

```
            

#### Result

```fsharp
let view model dispatch =
    concat [ p [ attr.``class`` "title" ] [
                 text "Create New Project"
             ]

             div [ attr.``class`` "box" ] [
                 form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                     titleField model dispatch

                     cond model.Error
                     <| function
                         | None -> empty
                         | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
                 ]
             ] ]

```
            
#### Problem description

Noticed slightly odd formatting for some Bolero/Elmish code. I believe the error stems from the `concat []` not matching the typical `<tag> [] []` format, but not sure. If I understand the code correctly, I would expect this to match the `ElmishReactWithoutChildren` active pattern.

##### Expected

```fsharp
let view model dispatch =
    concat [
        p [ attr.``class`` "title" ] [
            text "Create New Project"
        ]

        div [ attr.``class`` "box" ] [
            form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                titleField model dispatch

                cond model.Error
                <| function
                    | None -> empty
                    | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
            ]
        ] 
    ]

```

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 1/1/1990

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by kojo12228** [comment]
I now realise it is quite like formatting for `input`:

```fsharp
input [ attr.classes [ "button"; "is-primary" ]
        attr.``type`` "submit"
        attr.value "Submit New Project"
        attr.disabled (String.IsNullOrEmpty model.Name) ]
```

It might be annoying to correct this edge case but I could live without it.

**Comment by nojaf** [comment]
Hey Kojo, this appears to be working as expected.
Fantomas has no idea what your code does or represents so it mistakes the `concat []` as a unary HTML tag.

For more information, see https://github.com/fsprojects/fantomas/blob/master/docs/Formatting-Elmish-code.md#elmishreactwithoutchildren

As a workaround, you could create something like:

```fsharp
let fashionableConcat (_attributes: 't list) (children: 'e list) = concat children

fashionableConcat [] [
    // child 1
    // child 2
]
```

Not the answer you were looking for, I know 😅.

**Comment by kojo12228** [comment]
Makes sense, once I thought about it after reviewing how other Elmish code is handled, it definitely feels within the realm of _won't fix_.

On a related note though, the formatting behaviour for `fashionableConcat` also doesn't look like I would expect it to:

### Result

```fsharp
let view model dispatch =
    fashionableConcat [] [
        p
            [ attr.``class`` "title" ]
            [ text "Create New Project" ]

            div
            [ attr.``class`` "box" ]
            [ form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                  titleField model dispatch

                  cond model.Error
                  <| function
                      | None -> empty
                      | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
              ] ]
    ]
```

### Expected

```fsharp
let view model dispatch =
    fashionableConcat [] [
        p [ attr.``class`` "title" ] [
            text "Create New Project"
        ]

        div [ attr.``class`` "box" ] [
            form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                titleField model dispatch

                cond model.Error
                <| function
                    | None -> empty
                    | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
            ]
        ]
    ]
```

I'm a bit confused as to why where would be extra indentation for the `p` tag. Any ideas? Happy to investigate myself with some direction.

**Comment by nojaf** [comment]
```fsharp
        p
            [ attr.``class`` "title" ]
            [ text "Create New Project" ]

            div
            [ attr.``class`` "box" ]
            [ form [ on.submit (fun _ -> dispatch SubmitProject) ] [
                  titleField model dispatch

                  cond model.Error
                  <| function
                      | None -> empty
                      | Some msg -> errorNotifDanger msg (fun _ -> dispatch ClearError)
              ] ]
```

this no longer matches the Elmish pattern, because the `div` bits are no longer indented and they became a part of the `p` function application.
Shuffle it back and it works as expected ([sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMA3AlogO5gC2Ci6Y8%2BAzgA4CGW0AFmALwA6ATlwHYQIAM0a1W%2BWP0YAjTAGEp0ZmADaAXTW8BQ3WHrbBe46rDMsPAHQADa9HRjatsF0hZ8WTK7DrDxk2BYiAAeOK7yPIjMiGAAcsRgAAo8sABWiNBY3r58-H7%2BNLj5-kKm5la29o7OrjKwwdnFJWpgwrA8pC1SlrQArjKkHmAAFMK9ggD6YAC0AHzUdEws7ADK-YNYyWkZWACUPlq5zc3unogAYoTo8GQUVDQMzGyGTce6cPw35EjolgCiPBSfCOb2MAB4AD6tcaZSR5EGgkpQ2JSGJzMCIUj0LAAT1eiN0UJWsFIMVItAA5jN5ohAe0Ue5hAARRj8Cm0siUkZjSbUhaPZZgeSYRg8AFA3b4kqaHI6ITqSAAGnAUFo2HcbNoqDUKogoGMkAAJLj6Mg0JB8PwsErdUIjbhGOhemadSUAAzKkqQACSn0QVpW%2BAAXshPf4ACy2iDqW0AXzDeqjUGNONN2otVptBsNDqdLtUSYgAEYE3pIABZRjBAAylsQ1f9FKwrCz-iLACY3UmY7p47b9WWU2nzf74AB5YS1-iIFa4zCt3T2x3O7UFkrt0uLv6fCdT0OFjDCSDduOlgeLocuyB1WDoBd2nPL-MHgDMm7tvrVPCwl2k6HiRDoHW966BYzonr2Z5JkaJpXjed7vkuearge4bvhAkArJi%2BBwOgUgAIJYNu46TsB6GtI6aoQUIfa6OeD6wem8EgcmuYrmga7%2BAArORmFMNAiAAEKIG0kSJKKjCkkEPAsRAYGINREC0UI9EYZeTGwLeLFIexrr%2BAAbLxKz8UJIntPWsBELSyhqr6uCwMo7hSLJgQ8OBxg9jRUHZox5rMYhj7IRxB4AOxGSZwmiYgACq9CmjwNmIHZDnMHCLmiOgVEeae-bQepfmaQheVsc%2BJQABzhYwAmReZwqOIo-C0GBmTtOllEKdlkG5T5qZwYV2mBbpnHGAAnJV1VmZE5aYjItJtZlHV6J5SneYOvlQP5xVPihJRFh6B58VVplRYoeH8PNWVLTldF5et179QFJU7W2JYHcZR34cI0mKKQpCMC58mKWAymJj1w4bQ9W1BXpxgduNx3mVhgy4c55EZZdujLcDq0Xndm3Zk9wW7W%2Bb0mZ90lIzht6owegOdV53Vrb1GlaY921E22aEHb6SBWmO-AACo8DiADqHgtmj7VAyDYCqcmeOQwT7Mw3oRY8aTH0pOM8BMpQ%2BAbHN5F01dXU3WDV6WtabPQ8NquGQdlbBN6wgC6w-p-AtKysO0WBi-AzYueGXb0ytjO48z5qWwNhMq7oRZhQ7Va%2BsI%2BDBGO8XMO0fzBPQkS0LQaXkVxwcmwzZtM%2BDGZW1DQ0HkWFWJ8EABKGTtPAfsB%2BRQfSzjDER1AUfW7Xu1jY3LdwDw8CxL0pCzTwE7ekE5IuUWPdh33lekL06DuEB07nO0f1YNJAvM0PpX%2BJ2vHj235bb7vdYHx05iGwdbASZktITEQ%2BD%2By2a-l3DpXQeNcL7GHbK9L0jt8KAkYDiMcPBaxNQ7hLVCJdMbXRUrdfuVdo7K1trodsG5G4wJ4HAhBSCsDT1nrSBeS8tTkVXiHbG681J3S3jvfAe8LiHxfjwU%2BaZz7PXASTL0pDyGILoFgO%2BnDuFPyPtJFyMBWAf2kt-X%2BAcAFYPNumEBSsbYHnbFzKBVYABqT5BKWhoGyFBLkyroPlJg0GFcLaZiERzcB6sTHBHODCJy-BLGfEtBSWxXcHHRicbLbBwC3GgOEXods9tvFMlgFgAA4tgbOudED5zhKEg8xctHOKAX1VmcSPEJITlA%2B%2BXC6yCTwtAAA1oJMhTTsC0H5isSSiBToz3OpLBaRSok6IKmU-Rw9L4Ny9ABbhwksBWX9AIxAusU78A8HCfCnxpo0J4Awg86NFoYNNtolxLMirjLAQk0eXoADSiBED0Gdq7f0voumkj3BdQ5jjjnFI3q46uFz4m6BfPtbxHtBjiHySUbuzCZZyxgjg-Gg4Y4EKEC%2BSB-hMLBMwDAikM9-S%2B0QDIcsFBPlDPhflCGYzkX4NfMQsRQEKT8F8fwWEUhAxMuYL0SIAtYA8wJalGmJQDnkuiaU85NKDElBfKIzF%2BEd60mkO4XAFk2TbLnisy06ypB7OFVLWFvc2GIsVpKiZxgXzGMxTI9we5qySRkPARgwpYAFzZDMsi%2Bz9Wl1DoAv5Zy8FSv8C%2BLxmKmR0FkJgcFdBWArBxFaKsZKDWsPlsa6lF4UWviSZiu5Dz%2BVWl9C01kbBE3epYb6o1lckXptpdKqpmL6mskaXuWgMDYDa3iE1RA8BrW1OnFkvOBcdUAzcl8iJPzhmnNGRK6tgbzVTPraKGqkQw20GgDwfWlpojwGimsqQusqhkP8SWo5ZcTklP9e42OaLrmYtnOuzIJKkDHu%2BTRFU6gwwWloOcAu2oRWxiAA)).

**Comment by nojaf** [comment]
I think this thread is resolved, I'm going to close it for now.
