### ISSUE TITLE
Mid-expression comments lost

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#2126]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEAuBPADosAyhgIYb4C8AOgE6UB2EEA9C2AM4azX4YAW%2B0XgEsANvHYkyYIQyywArtTABbYjImlENeozDAwxAEYKMRTWgCCx%2BRgB0Zstoa6wceXTLUHiNAGEFHojU9pL4AL6QADTgUGyIGBgyAOZsqGAA2jEQoC5QACTYeGmQMhhRWYyQeQBuxCLyyGiZuRAADNEtUACSdEgeBEIAXsgdLQAsFRAAuhVho9mT%2BYWNUKXluVW19SvNLQCM8y6QALLEAB4AMjKIF4h0SXzr%2BwBMrYszunMVOUcFuCuQO7wADyADMrnREEQsCIRotNnUGmldrlnoddJAAKK9MEQuGdSAiUGQd6zQ4-DF-IpoSDGWAiJ6UrZIpqLCAAZnRlR6cWoGAAYjI6gA5RAAdxE10ZLgw1AapM%2B5PhVIBdIZXIR22RbLAYy5EEgBEQyiEcBEsDoFgw2JB4Kl%2BrAoLqcQVjC%2BugplRVxTV0oNNUROx1AFYHYacMRoIgAEKIUFcRAABWI1GIyniQT9jFl8tyHzdSo23ppvo1Aa1rM6ADYwwQI1HY-HuBdYGKgtBiHEetVYB3Ehas5g5YhXRB3YxPf7lj7YPSs5qWRkdQB2Wv1mNxhMAVRweGoHa7dB7faEA4dTpELrzZO%2ByunJdn6uVzKDnQAHGvIxum4hfCJO2w-h0BwcrQJw1CDo6zojteiq3kW95QKWz6BtqnQAJyfg2m7cMcxqGJm57QaOYDjgsCH-DOc5li%2BaH7O0Orhl%2BjYJv45p0JBF5Xi4%2BZjoWvyIbSj7zuWi4oi4ewHIxdZfhYoKeP4yiqJBOYwTxN4enelEPtRKEVkunR7Gi0nrix3BGiaZpnjqXFqbovGkfxlKCchRa0ZW%2ByciZsnyUEFmmvS1mdKpJFkXoWnUkhwk0ahHm5HseqMT0fQYMCdAACrUFgADqQiPERl52YwDlhZOSzaVFulubFBn7KG3lRhY1ABPAAAiiCSiangqcOoVOV6glrDF%2Bniboew1oxpxnF0oLpfwdCYoVBC8FwGC5fA%2BU6mMbywQW8ECRVJQeCJ7m1fFq6TecPSgkIZzAnupBcJiZw4NwbBsKeHEOsGO3qXBmkUZFR1lMNYk6nsH6XWcABKiBwNQ8DrZtnTbX1%2B3OYdQ16WDhmYVDsPw-AwryMoBHUGCXRkMoqQOnsaMAwdQPKPIIiJJKkL8lwqgJEE6WUaDr4tK8YYE1w8DHCzbPXJz1Dc91YaCCmkaeAA%2BmKQgbbwJK7Xx6MDZjx0C3RqJSQSU1NamWDAtQVwcEjWsOqjOuOXrU4GyD2OC6ixlm%2BcFvEFbNtCBwxOk0EFNUzT4P0xOEUAszrOiNLXOkJ4fNFEbcUuM8XkEv7ge2xgEuJ%2BziAy3LhGMYrqZgUEasa48MfkYzAJY9VI06s8iW%2B2cABqgbRjI8DJPbkFvr99kabHgOt4bnvG9n9U9-y7hgZ9g%2B9CPDcO1tE-FVPzcY0Dbe-Kdo2MM8E0961sAYAA4vEz2vYg72faP3179MB-hTPVFPu3OMhYXTNpLJOkJozmmgAAa2jDXKB8Q2BpQIGmX89ISZfRssRZ2pU45-xOjVc%2BEBniQwJKKCU1xYwYDbHcdOiB2o3ToHlT6Fheh4TDtQKOnRbJNx-i3PBmczrZzxgSAA0ogRAOAZpzTuD0ZB6Y8ScSwX9PaDMj6zw9gAr2Lh2QMR7otE0bBeDv13jwsqVQXLRXnlnXQ7JTYtENMkWETUkgkzuGtRAhhjgIHxC0bh2D%2BpuyBq5U%2BBCdTsh9vYiwkokh0BXnQNeFoBgxNIIoRA6VYDJTcaQT6ijCqmNwTpf%2BISO6dHZLnSJrMgh0GydUG4FokhsLJvQmQTCLScN8Uoye-1p58MKfgkpLR2Td3scXRIeILhpkMPAYgf5YAfXuGQ0uuTuJdJUT0tR-CrGCJsUvexrVg5GFhPo4OvACBYA8OcZZRUv7dMPvrIJljNELxsVfexYiJGZI8D0WBxB4k7y4Z0-etzeEbL6QIwhYB2TAPsRA35UC8RsCai1UUHBEDi1AaXJ%2Bb0PptJ6rmZRutVH3NVI84pgDcjshITClMZk6HB2gNQIQJpqlkHgFuRhFp2rQH-KmfsGCAV5P8a7cqDyqpkq0TY4R9iiCMrAl4pAVzQoxCmKMEobB%2BQfTSNwsIQA)

#### Code

```fsharp
  type State =
    /// store the child state in your main state
    { aboutState: About.State
      counterState: Counter.State }
```
            

#### Result

```fsharp
type State =
    { aboutState: About.State
      counterState: Counter.State }

```
            
#### Problem description

Comment lost

#### Extra information

- [ ] The formatted result breaks by code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-03-04T13:49:31Z - 67312877fed24b558c36ab546808a21657aa8580

Default Fantomas configuration

**Comment by SteveGilham** [comment]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIFsCGAXaAFmAB5gDuAlrgQDoBONAdhmAD5gDCsAro7onQCyAZwDmYOL351MYsAFoAfPSYsIAG0S4JPPgJHiAvCuZqIXKQIB03AA7w8iHZZlzhuR1cl66AZQ-8JiZmwGDujuRURN7S-hGGzj4GYAC%2BADTBagD0OWA4tmDUTpiIwsLYok64sIUETgDWFIzwYLAAZnml5ZWZLDlZYACePHQSBBTqLXB8dLDqYIyIiPDChTUE2M2avRgcmPBWjLCLkGngUMJauE2iwqhgANrnEKBmkAAkuIO2yGiQTbhTs8MB8AG7YdTcX6PYEsAAMZzMEEgAElmog%2BL4KAAvZCIpEAFlhYAAusD0sDXmoPl8fvd-nwgW93uDIdCnkiwABGfFvQTYYgAGSaiEFGNE1CZSK5ACY4cSySwKSwqSwad9oZAMfAAPJtYWLfyDTRStUsiFQ%2B4cpEy3nUgCizT1BrxxOR6jakAV5LtqpBnw19IARrA5qb-azLWhrWYAMx2tVoy50XAAMSaEIAcogyOoReGWLg6FDvUrfcT1XS-iGwwmoOa2Va3WACXXkb5EJgKHB1McAIK4R26-X5ttgNoQy6ljDKjB%2B5EBqtQGvqAv1yPs5sAVjHkF8tmw0EQACFEG1YHREAAFbB0bAlaRriBFktmRUz8vM2maldrsEWzdOQANl3fdDxPM8L1FWAyAEaBsEuNFQVgeDrmOJ9CmLRBpwgWcXgrRcf1DVc63-Rto2bAB2UCDyPU9z0vABVWwfjoeDEMYZDUIodCxwndQpzfH1KQI79g2Iv8GyjGFOQADho8D6Kgjh1AQ4QuEYdxi2gao6Aw-jBLUd9cM-alCPE2sCI3JtOQATgUujIMvQROyDAR9MnbChLLESv0DasJNIqTAOlBFmz3WiIIYxAuF7RgPIEryjOElVRP85dAqsgCbOlHlwrAo8%2BzaaQuEwHAMJfJKWGM1JTLNMSAss5lrIozlZQcqKoI7Lse145sDKqjAarwsB53rBqMqasyWpk6V43yyKitiTtuzmPrOUqnDat8syJsgX8gpmmM1C5VtwrRJA%2BB1RgABU6EGAB1KIEsM6qUrnNKl32zLmuy1rpR3BbwL7WZeHgAARRA8y7R8x027yPx2%2Br0oZQFDr%2B2azC5EDwv5YgUTaG66kYe1Et8AgL1wJ74ElMcCXlBGTKR-09oBSSjubLlqNxgU0TaChiB1Vi8Ave1iFsS8yh4%2BKxy3Bnkp81K-K%2Btn0fIzGTvknniAAJUQOA6HganaebemtpGsbK01VWsvV46WC5eztb1g34EzbhMDcug9RRfhZAwrlzbqlmUcwbh1GuPNFlTC8cFwaQbsDNXpPtjA5V3F2L3gQRw8jkUY5kPBYfCwhb0PaQAH1KBpggvUZ7ald2lGbd%2Bu3mxlPLOUgPGQbvQYdToYV3GN2u6flt7FY%2B5XrcZZOQrMGVbW13vsH7weKHcd3PYEH2-buMdA-ri3Ps1MOI4mfPY6LgRE7pOecoX%2Bau5Xteh9wHPz6jxAC7j4uu9Lu8OkBBVwoDXOuCtEaN2RirWetsU7tzOl3PGAA1ACx4mjwBuCPDCslx5DXevhae9IW7TQxqnCAMpAZIIFKmXgOlpboOaFg0BJtORmyPsHBcrNYGt3gZyGUONqHEHBrAXAABxLQYsJZdGltg2WeCIDDU4eNFGB04HzzUDKbmSDc4X0WMeXs0B6jHkAfULQwhrq%2BHvDFOYHsZb9U8kHZmXDVE-VIW3fhWsu7ZlzCKU8uBYIYlvogSG-NGBUGln2ZoLlt50H3g4xKTioEhy%2Bmo3hGiWAyidl3AA0ksWwBMiYYjRFYkoLoXqDUUQQ0aJ9iE8PcXwpEsYwpCNJl2YQBA5GmwUaSapltzKNRIuoh%2BahYydyRHuG4mgQaiA9hiKmiAgyCAQK6TkA0klTybqktxZoOacljEvZ%2BeZRCMFoYwehxwsQnLwNwS8N1YAXXmXgaWFSNmEK2URKauyyHNljE-CZfYI4CEYM80E0FGCiBiV7UJTQInHHiWsxxHDnEqO2V8iMPz9mIImR-a4LpBT3iDA4FSsBhA3B8V-V5yLkkuLRUM9JIyWCxioRM8GG9sBBk0G0jeBBfCDD4AKKlECmY0tRZ8%2BlDSMkYFjIIiZeTEAFPRHwNEJjNiECFRPSBmzoHivZpipp2iJkGM2PUF0wgQa6DdqUfg2ddFfykZLMl8KKpYTeTUohgy9UeKaV4o1t4lKXjZcIaAdAKBdhBTaxi4TjiQ2gKpO8aF7GIsSdS7VKTdX33%2BnGbJEz-Chp0sspAGr8FKnOCSfE-xhCpjJfcdZKQgA)


#### Code

```fsharp
    match x with
    | CounterMsg countermsg ->
      let counterMsg =
        Counter.update countermsg state.counterState

      { state with counterState = counterMsg },
      /// map the message to the kind of message
      /// your child control needs to handle
      Cmd.none
```
            

#### Result

```fsharp
match x with
| CounterMsg countermsg ->
    let counterMsg = Counter.update countermsg state.counterState

    { state with counterState = counterMsg }, Cmd.none

```

**Comment by nojaf** [comment]
Hello, this is expected behaviour in 4.7
You are using triple-slash comments in a location where the compiler is not capturing them.
Please use double-slash instead, Fantomas will try and preserve these ([sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyugIbp4C8AOgE4UB2EA9A2AM7qxV7oAWe03ASwA28VsVJgB9TLACuVMAFsiUsSUTU6EYGCIAjOekLq0AQQOz0AOmOlN9CGDizapKrcRoAwnNeIqNuJ4AL729sro-GAAHmAA7gI89gA%2BYD4ubgCyLADmTr5uirlgALQAfPYQQojo%2BRn%2B2XmUNA4Q6X4Bstjw6nUdRXls6lbOHR5hLdpqEgk8fW4eYGTzDcXBADSVYExKRNhgPHiKiCwsRDlcsAe8YADWUqKwAGZKJ2cXWzsy8k6CIvmuKiwIRgWiIRDwFgHK7cIi0eDVLZeRTwKy0WBgyDrcBQFg1dBSHIsVBgADaOO0FMckAAJFhcCTIFJ0FiqRBaQA3IhCWTINDkxyCsAABmxQupAEl4YhXPgBAAvZBi8VgAAsbLAAF0qRsqaBxbT6XyoMzWQaaVyecaBSqAIzKg2ZIjRAAyUkQLplOR4ZrtACZhRrtYLdYL9ULDThjZAZfAAPJPN1gwiYaq%2BwWc7m8kk28V%2Bh0RgCi8ITSaVGvZQiekCDOoL4YzdKjjIMwPT1ItWetFbAAGYCxmpXiqOgAGJSbkAOUQcSE7vbgvQVF5tZD9Y1kYZaEgraEC6gnatOZ7qoH1PwiEUAjgQgxpnQxfjifnZ4gT25eNXjlDjgbHaNLawG2Z6Zke-I9gArK%2BUD4NgRDQIgABCiBPBwiAAApEFQRDHG4%2B4QEuK7isG37ruaAHbru%2B6gdm4EqmAABs0GQLB8FIShaEurAcT%2BNARB4lKHKwHxBIYvhBzLogX4QD%2BlLkc2lFAXuIGHrRZI9gA7MxrEIchqGcAAqtguBUHxAm0EJIkCGJ0HvkIn7EXWeobk2W5QFRKmWmpuZCgAHNpcG6RxnBeEI-EsD4tBsMu0DsFQ4l2Q5QokTJZERq50YeS5XndvRACcAVsXpaGZJeej%2BAlH5SY5a7OfJbk7kp1Gqbldqij2LGBex%2BmID4t60JV9nVclTlhi5FHuU1nldse9G2vaHU6YgphPG4PiKMo4mEcNgopWAslgH%2B7IZYBwHZTNdH%2BoVQU9ReV43jZPaJTtjh7QdR0HhNjVneaOWzXa-aLV1K0LJe17Ao99HbdJ%2B1pY2X1Zb9F3qXNp4dVKSCuHGtAACpUJgADqiTcINSW7aNv7jQpk0-elf2XeKtpQUDbGmECLjwAAIogc5Xnh0HQzVpF1elX2mtNYEo3aTEdU60QSk8OO8LQhZDfg3AcOgRPwD60GqoGQupSL8PU0yrjNfTUuM1psvOlKTwCNEcYmSQHCFtE2CcKc1kDdBEEGyNtVjfV0bi%2Bdks%2BYKtr%2Bbb0QAEqIHAVDwNrusngH5NB5TIeMmHSMRz2toFbHCdJ-Ak6yIo5VUAmEqkEU4m2jD71Uw1iiyEIBJzmCo4cBEbg482EveT2AbMaXHDwJkHdd%2B6vdUP3FXMfwWHwW4AD6CQ6yTzdw-%2Bpt53TyOR44foLfRkBy2z2GYHGVBumwqck3rGevRTcmiwf5vD61eb5rH18iC33vgINgFcq7%2BFrvXYk0Em6G1hsbfebcZ7CDnn3EgA8h7hxHvRP0gML6AOAQ-dA09O6oJ7ug9A-MOor2wrFfwm8BDbxrPAluOdtyH0bJbE%2BEA-RowvnLAAal2RCDxCRP3Er5V%2BEA3p72OmLb%2B2Df5Cj9MzARzpRwuFij7UR8JxFMLTvRfWu9EHyK-iyH%2B-08wy3UdETmsB0AAHEaju09m8H2Ei-bSK1O-Q6rdMpTSUVYlRNsBEoO7khW80BbiITobcGoLBsb4Bwr1YEldfZPSqiY4On8GqIyPgXXBMcL7TlnO6ZC6AeIykHrgbmDtaCJB9qYeEpUIFUBgZkoa2Ts65ICbTLhx9R7FwvgAaXBNgBWSsZRSmSccMspMXoyN8R9TcodFH5xwSqXs7VbGqyvCwbgnj07dI-ibPJgSNnKMFL2c%2BKoWKEmqGzHIlcZRa0QHoTICByz0Weicvx7CabKSCQzIUvZ-4ELnDkWgmjaDaIxHKKFJB5CIBxrADGrySA%2BwWX8lZJ1FL9I7NwnsvZ8F3NMJ3fwtBMUcg9BiHIrTq51KkI0jEHSflZNYXIz6pt8kDMKVs-hdzSEEjLC6HCegeihVgCwQkpSInYs5aY7l5yCXHSJfRXsai7mc1AfoaoezQHcHwJgVwzoFWB2Fjks5fSgWXOCdcmxdyxmIAmdKVwUpYlwn4OazOlqenWtOragpmzxS9lCXcxCYVaC3DLCwNmvhy4nFIFPcJ7pXFexlayrakkcX%2BMDRbQZGrikRqwsVTgOqWDQCoAIK8VLk0GQaRibm0AwrYVEhk9lXTFVWqQTagt-LQ3DLuYQatsVPlIB9W-EMOJNTKiZCwUcMqSS-OCEAA))
