### ISSUE TITLE
How can I prevent Fantomas from putting unit and/or equal sign on single line?

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/fantomas#2245]
Given this input code, which is quite common in tests, I'd rather not have the equal sign and `unit` symbol `()` on a single line by themselves. I tried `fsharp_align_function_signature_to_indentation` and `fsharp_alternative_long_member_definitions`, which I thought might affect this, but to no avail. Any ideas to prevent this from happening (short of adding them to the ignore list)?

Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqiAzuhQBQCUYAvADoBOzAdhBCUQEaJWYAPoA6AAbiA4gEsAboi4BDLrFzLocAK4d0YAO4z0ACzAyOFLQDMrM6DMV7WlQQvhgrO%2BBQA0YaMZKrADm5sFgJnhKmrA6euhKANaUHqzEEcZ4zhSuiO58SgA2KtBRHO6RynJKMsV8hYiSYPRMbJzcHWAA9F1g8LBgFMR46JTobVydEDLBHLDO9BNTU5A%2B4FA56OhhFKhgANrrEKArACRYuHuQ5uirR9yQp9WFWshoh8tgAAxrn5AAkuVHPgZAAvZC-ZYAFnuEAAuvcAL6Q46wqDnHBvKA3O5nZ6vPYfZYARhRnUgAFklAAPAAy5kQtMUwRMuJJACYvmiER1kfcTuSMZc0JBFPAAPJWekcRD4LANNkdR74rFEqbsslKgCi5Ul0ohaIgkEKVkg3KRZIFSqFWMgfFgsEKioeTyKBPehrAAGZNQ9ATlWOgAGLmIoAOUQ%2BkKDOdHXQrFe5t5lrRjwutvtjtj6JVhM9UN9RvwiCIdkdsA4AEF0DqJVKY4WPEUcknuHyOlaXemrpmnb7lW7VZ6AKyNyD4bDRRAAIUQVnmiAACkElCRRqxsxB44mpjy2ymzt2Rb3swOXkPPgA2McTqez%2BfOWmwfSCaBKHKAuSwN-bCubiIJogrYQO23CdkaNo9g6fapq6555p8ADsN6TqU94LgAqtguCsG%2BH4cF%2BP4yH%2BjZWM2QG7ha-KwUeUAnv2cHugcnoABwoXec4LgAwsUFAUFxFZUAm0DoPM-5kYULaUcm1GHpiUFZgxuYep8ACc7FoZxzgUiWAgbqR5HAWAoGonJwp0dBp6MReJI-J646oTOWmIAJhQkZ6ElSZ0e4gQegq0XallKYOCEkqS9m3qUlZWOuAlEEQSj-tuFHeVRHY0fJx5BbBynMZ8xIahFjnoc4xalnAbkcOJhnSfusn%2BZlFmKTlIUqSSPpFVO0XrmVZaVUlgFGSZYDgeiAX0S18FtVMxIFvZgJILo4ocKQrCYAA6kYxjVZJKUdD5xl%2Bda43ZXirV5SSo6dVFaReAAIog0aluuA07qlMnpWZto4sFU0XTN172VS1L-FYpCZBwWq7fgxjzOgm3wKyjZQlytW%2BfVx2NdcuhWblaqdMSyFAzSgK2NS4o4UoomsFq1LYNkFDEVVjbDqj711Z9DXmdjty-Ux%2BMdMSbHE9SABKiBwKw8AI0j%2BZs-taVgRl3M-ZN-OesS6ki%2BLkvwGGWj8IIkr-KMRC7I2xJDUdXZY0QWiFNs0YykG8wJVsgikPJfM2eqdl-Dr8zwBS9uOwyLusG7L1jgEK4iYIwiGIj21WxjNsqzj3uheq4V-MDlasKwSiYOKrD0lQMvbcj8vcAdw2jWmWOq2df0C9w7KFbnNL54XxelzIVD64brDG6b5saynnOY9zdsO7UYeu1T66e5cmfTZ07IdX83dFyXZfoMHs9O4g4eR4I-4wIEhdx6wCcyEnZpo4dqcQQFTeCnjnrsnNnfUgAaoO05zDwDCBXf8LFq7wkVqZLm30M5qx9uvK6P8gw6BEkzQB5QQF31lp8FGE8lZfSuG-a0H9PjskBj-O6sB0BSEQDWOmDMmagJZhAsAtdrYvyxhNZu6syFE1ziHOeMppxuWgIkacV9kjUGWvgVcLlHQG2Zh5Gq7N0aTzThmU679zqtwgOyYWfwIxRgZLOdAL5FDL0QA9WwHAjBM0rOUHSQ8x6fE8ntGuUCRrK00c1HhCCOjsi1n8AA0ogRA2BQbg0UICWRJB9Q7S8grD6BCYFELgX4rOnQvR%2B2WJSGkUNSwUGMMwuW%2BDoFTx8TBDJa8OhehzrkkEHBggNHzsEA2jh1qID4BSBABpXEqKSRzFJFSFJVO0S3T0XoO65MrNGWYKCOBoIrCCWYVMtDOFILABajgqZMwSe4yByTykaNGbjHRkzN4zIdoIDguyFBPiaU4vS1jzB2MEvsspXjCFZV8eM3hywvTf1yQfbY%2BpaSrj4PAJQPFYCMyaUYo%2BHzH5128ac1e-0slINyXdfuSh6iIAKf3Yw%2BBMC6BpEi1RT91GcO5twv5-juBegobk0J4Ttm6EBBIkoldlG7U%2BfXSCPyxkkPOZ8L0-DckiJUIkfUFB86xHKBGKgeQQVCIJQwygjN3mNmSvy1FQqzkTLFQYyVQQSpWP7tAVgMhSy3NGPADCtiKwPWgMUQuv4lH9L5cijhY0uFaJFUagFQTcmiyUKstIiQKWDLUcMk5Br0W6LACjG88Y7D716dGjxvJ1hwkhNcCgQZGZ7DcSAREQA)

#### Code

```fsharp
type SomeTests() =
    member _.``Given an open account with insufficient reserved funds, charging the account takes from the reserved balance and then available`` () =
        // do some test
        ignore()
            
```
            

#### Result

```fsharp
type SomeTests() =
    member _.``Given an open account with insufficient reserved funds, charging the account takes from the reserved balance and then available``
        ()
        =
        // do some test
        ignore ()

```
            
#### Problem description

Please describe here the Fantomas problem you encountered.
                    Check out our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#bug-reports).

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-09T12:59:04Z - f2e3c0898acc865e05bb3d94510daadf797a234c

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, increasing the `max_line_length=200` seems to do the trick. ([Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqiAzuhQBQCUYAvADoBOzAdhBCUQEaJWYAPoA6AAbiA4gEsAboi4BDLrFzLocAK4d0YAO4z0ACzAyOFLQDMrM6DMV7WlQQvhgrO%2BBQA0YaMZKrADm5sFgJnhKmrA6euhKANaUHqzEEcZ4zhSuiO58SgA2KtBRHO6RynJKMsV8hYiSYPRMbJzcHWAA9F1g8LBgFMR46JTobVydEDLBHLDO9BNTUxMNepKyCsqq6mDR2roGRqbmljZ2DofZue6e5b7%2BgSFhGVExcRFJKVZpRK9g11YbjABWKHFKe3KryqNTqDSaLRY7EmUx6fQGQxIETGS2WMzmCzokB84CgOXQ6DCFFQYAA2qSIKAppAACRYXA0yDmdDEhncVnVQpaZBoenLMAABhJ4sgAElyo58DIAF7IaXLAAsfIgAF0%2BQBfdWM7VQNk4EVQbm85kswXCmli5YARiNnUgAFklAAPAAy5kQPsUwRM1uWACYJRKTXqOoa%2BUy3WaOWhIIp4AB5Kx%2BjiIfBYBqhjoCor20UmiBh11FgCi5Uz2bV5aghSskGjBtdCaLSYtkD4sFghUL-NtJYtjqmAGYq-z5TlWOgAGLmIoAOUQ%2BkK-uHHXQrGF7djnZNrPZvf7g53prt46bGpnEEg%2BEQRDsg9gHAAguhaxms9uHw8IockPbg4w6LsRzPTkLyHGdiyFW9xQAVkAp9sGiRAACFECseZEAABSCJQSFGVgrwgPcDymGMwOPG1oJTWCrwQ0s6SbAA2ND8Aw0ocLw5wfVgfRBGgJQcnlORYDEykPwoiJ90QUCIHA7hIMfHsYIHOCT1HRCHSbAB2bjeOw3D8IAVWwXBWDEiSOCkmSZDkwCrGApSaI7eNdMYqBmPgvS2InToAA4TMw-j8IAYWKCgKCij8qH3aB0HmeS3MKEDPKPbyGPNLTLwCm8DPFABOcK%2BPM5x3RfARyNc9zlLAVTjTy5M-O0ljAqQ50pSbdCIqqxAEsKFymwyrLOlolT6MTXy%2B06oqxxK50XX6njMM-KwyISogiCUeSqI8qavIgnz8qYxbdOKstxSdSt1tMyLnGfV84FGjh0sa7K6NyuaLo6wrruW27nWnR7Nu2wRXrfD7DsUpqWrAdTTXm-zgf00Gpide9%2BvlJBdHTDhSFYTAAHVji%2BzLjo6abmtm7s0aum0bvYu7UIh0pPzSLwABFEC3V8yPh6iTpys62t7K0lsxtnnS4-rPS9WUrFITIOGran8GMeZ0Ap%2BAQ0AjUox%2Bma-sZgGuV0LrWeCjonWMxXvXlWwvXTGylFS1hqy9bBsgoZzPsA5CTbF36Jf%2B9qrZ5GWgqbJ0wqdr0ACVEDgVh4H1w271D2nTrU86o%2BljG47u8qk9T9P4FXLR%2BEETNZVGIhqUAp1EYZqDLaILRCkpLcc0XeZ9opQRSHy2OeqmCM0Mr%2BZ4HdHu%2B-9QfWGH4W0ICYiUsEYRDAN4w21N%2Bnzc7ovrYnlap7WmUle51glEwdNWD9Kgs4Po3c%2B4OmkZR09LeLlmIM5ZTwejfb0d8H5PxfugGuddWANybi3eO7cT4aXmt3XutRl5D09mRMeHIL5Y06GGcGMoIGP2fjIKgC9MH90QCvNegh5IwCeNEMiu8ZD70PmHM2EcLZnxjiXSexDcZgK9AANTHFhcw8Awhv3kiFT%2Bup86tUjlLc%2BQjL7EI5mIxcOgUqB2keUORnDs7imNigvhp91GCMAbLO23AwwKzEbzWA6ApCIB-L7f2gd5HByUWAb%2BHc0GW3RnY0u4ZHY30XlgnMWFRrQESFhe%2BiTPEUCJvgEiw1By1yDuNb6PDj5WJCVHMJiZbZNjDInGU65Nz%2BhwugESih8GIH5rYDgRhA6fnKDVOBSDxQTRpl-FRyNC7nmZuUoBDiKzlxlAAaUQIgbAKs1aKHlJkkgDYqaTTzuLAuktOQAMmfYpsk4%2BpiM1q%2BCgxg-E50sfstRBUdLhOER0Sc19lhPjCA0bmwRa6ODJogPg7oECNgGQU3Z4cHn8PGUDF5Wi3mgM%2BZ%2BLcsw9HglkhwJUsxPZaGcKQWA%2BNHCe0DtsoZyi9mqJhU8m2UzTmkORb3QQHASUKCEhwYIvS6ptPMJ0xKZL7lUusTSwhwDOiTlEZ8mhlIGw%2BhInweASgYqwADhy2pdCBVHx-mMkVmiiFvJ0Z83mVClD1EQJcqhxh8CYF0N6TVhTtUHMunC45ESpzOM%2BQspZRLdDymSSUd%2B%2BTqaCtGU6wGzzXWvO4JOKJnz4kqESA2Cg3NYjlHXFQPI0rYnmu8ZQAO-LAJHRDb-TSzqI3dgqeKSc1S41BGeq0qh0BWAyFfCy0Y8ALIdI-PzaAxR76YvtZC3h0LhVltpScqtszPnJyUDitIiRB3DMpaGx5Y7RXTLAMbbie47DoBBUgRdFKwKkh1OqLkFBFwBxpIMkA%2BogA)).

From a technical point of view I don't see a bug here. You might argue that this a stylistic bug, but [we do not discuss these here](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for).
If you feel strongly about this, you could open an issue and make your case for the F# style guide at [fsharp/fslang-design](https://github.com/fsharp/fslang-design#style-guide).
Thanks for understanding.

**Comment by abelbraaksma** [comment]
PS I've no problem accepting that this is default behavior right now and turning this into a feature suggestion instead.

**Comment by nojaf** [comment]
> However, whatever setting I seem to use, it will always place the equal sign on a new line.

That probably is because you lack a return type.

So Fantomas supports two style guides: by default the one from Microsoft and the one from [G-Research](https://github.com/G-Research/fsharp-formatting-conventions).

In some (very limited) cases the guides diverge and that is why we have the `fsharp_alternative_long_member_definitions` and `fsharp_align_function_signature_to_indentation` settings.
With a return type, the [GR guide](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM7b4MKOJNLPJIDsBzAMQFdLosBLWSsAQzACMw0WlHAF4wAejEAdAE6SOEMAAoAlDLlrKEsAG0AVADoAZgGcAuhq0BbTgA8A%2BukGIHiGlgAWwgGwAGC2LATd05pAAc7TkdqSjtDRmY2GOMWaM4semlnLFg7QSQhNMThLGl6ZAAacChjbFYaY1QdKohQBQVIABIsAE9Q5DRIQSxISraIToA3SLLG7Waxn1Gx8YBJSnysAGUWAC8K%2BbaAFgOwU3mAXyWWk86evsbBoRGbjqn0GbQ55YgARiuxyAAWVsABknCDXNQPM9vmBfCczm1LvNWgCur1%2BlBXPAAPKGMGURCbHqYGFot4fJqwgBM-zakAAous8QT9rDIOhDJAERd-qj6ej7gMePh0GSBRTMV9vgBmOntNY1aRYWiCSIAOUQAHdHITxWMSmUeUi%2BS87pjICLYGL5ZNplKThBDvLxptEJYWHA8JQAIJYJm4-FOfVtQyRGrGhTItr89qCi1Wm0vSWzR1gACsLqgm1CnGgiAAQohDLBMgAFEKcSzYRDSEMKQ2ISMQaMKWPjeMPRP1u3vB2wrxZyA5vOF4ulxAg2Ba2vQTg1NYTWBz1jsesQRvNsCt67LW4Yruinuve2p2EAdiHI-zRZLmQAqqE%2BtI5wvKEuV4l14Fw03loio1NPdO2FI9bRPPsz2%2BAAOK9cxvcdMgAYXQedjCQ9hjENZhS2-MN0Ajf9eRRM0D1A61jxTT40wATjg0dbwnQF3R4Ws8N-LcdzAdsoBAqBu3AqiqW%2BH5FjTYd4LHO9EAw712IIv8xgAlsgLRc1DwowTT2o2Efj%2BcTr0QH1DCwWsMMsaxv03IiTRI4D1PIpNgKE6Vlh%2BWkDMkxjMjdD0vTXLN8MIpTiJjUihX4sDk204S3LlTzR2M0zpF8z1rQCtNrJC2ywvssjIs06LIJ0kTnXEtYNhxSgABVpG6AB1FhoUCjibMAuy1Pyy0oucmLXLGH5MwS-MfWkWBGHgAARRBHA9ZKrNKRS2mU7dVIFByoCGSi%2BrTH5B3E4EbBWQxqvcVwGQUzZ3FLLBGvgZq00OHxOLWuMNseYYtOK2KBsvA7bDWQwWBsHFnzSUsGRsUJMmMZIMthdNnralSOvWrqtq%2Byl%2BraH5YP%2BmwACVEDgaR4Duh7YSel7Ube9Gnkx-sRLo-GiZJ%2BB1XoSxWOkPEVlMywGizH5qdyzqIsgSx6HQVhdUQWhS2sLBkuqg8Gag5ZqTE9lWdLeBASlmWnHl6RFfmodoGCaQ82SuwtRYe73G5ZHVppjt3oxoqsbTal9PZQ7Rqt7ocWkMEsPJx2syp52uJ4-dxY93rvuxhRqQ8v3bADzgg5DlgsI5rna15-nBd2kW23Ci1JellhZeN03axV%2B41ZKjX4vZTPs9DrB9er2uFbSM3xItytmFrW37ehMvdzFi0E-JHaaTK9ObAANXtAs8kEahw%2B-aCkey9rRbR%2BP6c9xmNaG5eGCYVdKA39Yt53yP9%2BW0Ly7yk-PrP9Wxmpfbl8mrALAABxbAkNoaIFhokJ%2BaZEZT24hXDSTl55J29n9P2Bsa5OALHgaAABrAsVt8HYGMFVTYVYZLWk5pQeSwVX45XfjPJB21UE0jxuyTUOpsHYBnK4RuiBppA0oE1RIPp1jMQLtIEusIgpLQUCtGOiDHIsK9jSZm7IADSiBEChGOqdVwaxyHVlZLQuREAFGvTdnTL%2BidVGyi1t8IEtgLoemMO4GBlMX7yLftPY%2BCYeooLscsGUvtHHbBoJgUa1BOauFuogHggIEBsm%2BLI%2BBsc%2BLdUKrY8%2BYwZRp0cT6KIlBr4JHYNsVI6RMjVVgBVWJhR4bfCyvQw%2BjC-HMObj9NoMo24FOlrWSghQJiTnYNQCR3NBGCBEZhUxaSlEFWQRKBesol6OJ7qwVkIIqw8HgJwFCsBkg0E4bLGZ0dLG8XegJb%2BLdcmX0cZNXOnAeCYBcbndwmxugFBsCcg%2BKMj603Fpc7JP8un-0cVonRtShBrEIZwJgEc0ypNOa7c5XVAWBJyV09BjicGwrwayYwo1xrrE1FhRAetMGy3ATDOGlBpGNMWrMj%2B-isnouBQoGU7DsUhG8gI3O0BpAsA9AM0y8B7zCPYNNaAqEra32%2Bc035rT-nMoWXGFyaYZTqMcQTTgqQxp4Lld4hhvilXtKuZ0hQT0rwlE9N3JJBrzEXCqKYJYgxjC0GSI0VJ5wgA) says to always put the `=` on its own line (when things are long).
Where the [MS guide places](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXM7b4MKOJNLPJIDsBzAMQFdLosBLWSsAQzACMw0WlHAF4wAejEAdAE6SOEMAAoAlJAA04KAGdsrGltRgA2poigFCyABIsATwAOyNJEFZ1py1YBundPSfGHhYADBoWFpAAkpRIQgDKLABeyGHhEAAsQWAAuh4AvqlmWdZ2joYuQu5p1j5%2BASZpEACMheGQALKcAB4AMoKIPYg0WAAWVY0AbMFZuRYFHuZtNg4BkEPwAPIAZn2UiHF2mOMR3r7%2Bhg2NAEytEQCiMdu7KVkQkOhbkDP5rYsnpasePh0MdPLVzmhLmkAMy3SzRHTSLC0QS%2BAByiAA7uh%2BqCLFhpP5vnNfsVlmVnEDYCC4TUzvVXmB0nC3nFEABbFhwPCUACCWAemx2uJZYC2vh0xIU8wsf08APKVJpZPBDMaYAArKLIHF7JxoIgAEKILawaSIAAKnGknHZ2EQ0jxCgJRLSs2lpOq5MBwKddLqF0ZE21uv1RpNZoGsExDugnB00S8sDjrHYTogLsQUogMoUcre3sVvtppwDkMZAHYQ3qDcbTeaAKr2RzSOMJyhJlNsSjpsUSrNun4LMkKynFlX0wPqgAc1bDdcjAGF0PGtIv2FoXcwzb3xehJYOScOvaOoEq-aWIYF1QBOOe1iPm9ocngO3f97NgXNFE8rIvUi9VSnRomlCRkdRrcN60QdceXffcB3Cd0c09JZT0gc8SyA8t1SaFpwNDA1eS2LAHXXdl2U4XtM0-b8wHzKBCzHACsMnHCQJuAjIIXc02U5bk01FPcDyQodZRHP9mOVL1sOvEDYS4sNiNI6Q%2BK5alBMZGjDw9Y80Mks9xxkti5LSJpmXA6JYiwDZKAAFWkWwAHUWFGeCRIsZCv1Q-4DIwoyllkqFwiaLVFKI6RYEYeAABFEBxTkVOowlEM8sS8wkikoFcQCTOCiwmmDcDOi6SItjskYhjuBC4hGM0sBc%2BA3NFdJph0lC9N8rKKjcViy1MkKq2K7poi2Fgug2FtOCwM07i6exzS0LRu17DU2tEo9xN-bqcr6q98oUJpZ2GroACVEDgaR4Ea5rGVa2ifPlPzdonfqDuaO8TvOy74DReh2VfaRtkiUj2QMUUmgezqnu69l6HQVgcT2WgzUorAVLsv89rVa4wPVSBvrNeB2nhxH%2BhR6Q0aS7VoBGa19RUgB9TEWCasYoa2-SdsqbHgLSK58PxkreWkG1bA2aQ%2Bk3G6xha9a0s2jLttWF7jLexkrk4oXuhFsWJalrA-oBh1gdB8HGUh9rvOhgt0LhhGWCRxAKaph1MbKXn2P5hT8d1zhxcllhNxJh2nZd6bqfA2n6eYB1mdZtyOaVrmVZ5179o1izta6AA1elDUEeBBGoGXe2neWFC8uiGJKZ607VjP1SuMLs4YJhU0oAuYmL0u5aTn8U-KVXAryjWiuzmLYCwABxbA5oWxAlu7XvGTW-v6Myn0WPTnH%2BaGoXScd-pDTwaAAGtDRtc-sC0Wy4ltGDqX%2BnshI-K3q83-9pJH9Wm%2BO-GMTYmPtgGMQx3aIDimNSgrluy8hiM%2BY20hzbqmEqlSu6UB5dS3t-E4QUNafXxgAaUQIgewZUKpDGiPfO0zx3JoIgFXR6ts669R3nzcI0I8aNA6N0aqnItAjBXuqe678mGMXQphNhXsOGC24QkGgmARbUH%2BkMBqiAeDtAQC8FBb8Nq6U5lgr%2BuVf6NGhFrbhvIcTUEoG3Zg3YEjWOmvQc0dlYBWVUdNFar8ELrxrkxQy28G67w4T7CxCMHSUE8V4KMNAEGA0gYIGBG46G%2BM-lJYxjdTFZ24SHVgzwei2h4PATgy5YDLRoIAp2KTRE23EX5SRQT2EWGhC3bhMUg6cB4JgPhQcRhxFsEIbo1S9EdQMTDbBGTgnNPHtw4hpD3FCGiJfTgTBZaMlQak5WRjPYDWafvbhJ8Vln2eFoEWUUYgYk3IgYmh8nbz0WstZJoptIjOtmM5h3UGk-0yTCf%2BBzrQ8QgUHaA0gWCckiaReADZoHsDitAFcNoO7DIVvo5Ohj0k7PemAaEBDuGnU4I4yKZ9kXoMVpg8Z2ypG7IUK1EMBIuRYE0UgElDD8iaGyKkFwWhaDLUMBsvIQA) the `=` after the return type.

The style guide from Microsoft is a community effort and is still very much in flux, new questions or ideas still get cleared out and I do welcome you to challenge the guide and help improve it. Some things aren't really fleshed out yet.
Other things have been changed multiple times due to new insights.

I mean it wouldn't be a stretch to always put a function signature with a single unit argument in one line. That makes some sense to me, but the point is that I don't want to be the judge and jury about these things. Because, if we were to agree on this, I have to deal with the next person that will open an issue claiming the `max_line_length` wasn't respected for that function signature.

Over the years, a lot of people have asked a lot of things and I'm just really done with it.
We follow the style guide and because of that, I can shortcut things over here.

**Comment by abelbraaksma** [comment]
> We follow the style guide and because of that, I can shortcut things over here.

I totally understand that, and your sentiment towards not wanting to go into discussion about every other person's personal preferences. Turns out that I merely misunderstood the guide in the docs.

Also (personal opinion alert), it just looks really odd to me to have `()` on one line, followed by `=` on one line. Thanks for taking the time to explain this to me!

**Comment by nojaf** [comment]
> Also (personal opinion alert), it just looks really odd to me to have () on one line, followed by = on one line ;).

Seems very reasonable to think, you know where to knock for that 😊.
