### ISSUE TITLE
Idempotency problem for unit of measure

### ISSUE THREAD

**Issue by dsyme** [fsprojects/fantomas#2264]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAdATugdgFwE8AHRMAC0UzzLAF4wB6AZ0Th3i10gBpwoW8eAJY4A5k1RgA2nwigICqABJCJSZBF4eshZCUA3AIYAbAK7I0MxYoAMva7oCS7RPgDKQgF7J7DsABYdCABdHQBfXzkg5VULKE1tBz0jMzirPwBGSOtIAFlDAA8AGRFEItdRakTMgCYbaNDFCJ15HJViOMhXeAB5ADMSnEQ3QmMfaOSTc0l0hxrsxUgAUXZ%2BwfG-KGM%2ByAbw7NbF9rU0SAAjWFhjaqOU6ctoiABmBaccFioAMRETADlEADuxlKN2seEw5j2TQOE2OnQuV1BEEmqRmjwCr2RbiIhmgiAAQog%2BrBMIgAAqGTCGAC2iDwlCRCnBkIcjQUzUUh10cPUCOurxR92k6IArJioNjcQSiSSyrAAZRoIYWM59LAlcJYDhGRBmYgoeyYUkeac%2BYzBWl0QA2cWQSV4wnE0kAVSIJEwSpVODVGqEWp1YD6JhYBogHIUXORJqgZoFBimls2AHZbfbpU7EABhYzKpiZrVMZnQPAkgNB4wh1n7Fqw2K8y782F3RN%2BAAcqZxDplpNyiGpZwZ4vLlesbLDRraddNDfN8dRD02AE4O1LHbL88Z-UPg-qq9Ca8apzGZ3Hm2jNhk7Oi7Z3EABBPr0zD56nUwwBvWhsDhqKHjr1xFTwTc9Miya80zXUk3D7IQ4E3bVtwrXdR2rTla3-adAKbYCF1qFc8QfJ9oOpWCri3dFPz3Q0D0nDDjyw40z1whwMhecDbzvTBYFMdgABFEGBEinw-CFkMUMdvwnI4jw0fBZyY4UL38W18gKRw%2BgAFQoHAliQtwyBJPAAHUhHgKpxX8eoqPHGjpLo2StCA%2BdFMyMVr1U5w%2BiEAoendQwS0wJYCiIUkmCYP0ENFKyUP3NC-xOeI5KcoVZmsDIbXcwoACVWBJeATLMsgA0sr8fzASMYnshJkpbFiU0ygocrgTB4F%2BUx%2B0ofpHHpakJHFDJSqk7kZOpUxjGEYEhk%2BEk30ESgNP-GqQJY9tryavLcjGibSmmzBZuE21oDISlcSfAB9AFTKqQbbOGqqkuw5zUsUDJlwaziqQIHpMBKQsCvM9ESusyTbqjGTqselL0TqFTCg%2Bwwvp%2BoRCzajrMC6nq%2BvRAbgbKiq9BGrahEmxBdv2%2BbFsh2rrBqMDNkgeHEd%2BvBNvG4mdpm-yDuvI6TuLSgLquoqbri2iEoc%2BScJcuZ5gagA1BN8REeARFEf6ivFVtovE1CI3Q8WIcYqXnoUGo2Pp1TPh44sIqV9hVfV4rtYUCS8f1zpDbaBSTYgGplIa3jYDwABxOkgpCxAwoix3xRFZ2Ql138xfhE8qeWmm3ItomSfxTdoAAa3xKkC7pJgehwNwaSzK52sizZhzEl3E-K92AMbI2nuhjL6f%2BIFSkJPAFVcBaSH4rycCETUcDvdhezRrH653EW9filOGK943ofq%2Bm72BUQcCtnAba1Dx9-80xSQ02BnCQfB-Iissl9xoawfs2M0%2BYmnVp38bKBwe-9ByjEHPAcmAx4iEnhFBefgG7LyTnZcW78O5Q02DUN6Wc2brCKDSM48BDDZlgOFMQvcSaPyQnAluq826S07psJ4V56bh0oEIWkd9jAAGlECICIDfVweBnBF0MEfDW6JYHP1BpVRBqdkHU0UE8OmfhIC5yEfndYTBOLcXYP8QsiB4Cs22kMcOoVwoFhEiyGK1FRYILXu3DetC-BPFlvTfElJIKIF4sjaAmAWE-HpPAZ0E8tT8WgDmKkU8yEjh1rFFeydqFLU-nI82iimHeNYXgEwIwuKmELBCIgIwCBjAiY3BO0T4F3QNg9GR6c5H%2B3ppw7hqlUagP6MonAqjSjQJYjYeOYBXYv0kTYmhKCHGZ0UZk2CLMEAbBgU-CxYY%2BDBF8BoJgnxwqSFgWEIAA)

#### Formatted code

```fsharp
type herth = /second / second

```
            

#### Reformatted code

```fsharp
type herth = /second / second / second / second

```
            
#### Problem description

Fantomas was not able to produce the same code after reformatting the result.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [x] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-05-18T11:51:41Z - ce92e669f26ae2aec1ed8189b55227a19fa4af8a

Default Fantomas configuration

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for reporting this problem.
This is an interesting case actually.
Looking at [the AST](https://fsprojects.github.io/fantomas-tools/#/ast?data=N4KABGBEAmCmBmBLAdrAzpAXFSAacUiaAYmolmPAIYA2as%2BEkAxgPZwWQA6ATl8gBcAngAdYYABaweAiWAC8YAPRh6bZNF79IIAL5A):

```
TypeAbbrev
 (Ok,
  Tuple
    (false,
     [(true,
       StaticConstant (Int32 1, tmp.fsx (2,13--2,21)));
      (false,
       LongIdent (SynLongIdent ([second], [], [None])))],
```

Notice that `StaticConstant (Int32 1, tmp.fsx (2,13--2,21))`, that isn't the best representation as there is no `1` written anywhere.

The `range` of the `SynConst.Int32` does include that entire abbreviation `/second` and due to some recent change, we print numbers straight from the `ISourceText`.

https://github.com/fsprojects/fantomas/blob/ce92e669f26ae2aec1ed8189b55227a19fa4af8a/src/Fantomas.Core/CodePrinter.fs#L4328-L4334

`loop t` will eventually print the SynConst and repeat the `/ second`.

It could be changed to something like:
```
    and loopTTupleList =
        function
        | [] -> sepNone
        | [ (_, t) ] -> loop t
        | (isDivide, t) :: ts ->
            match t with
            | TStaticConstant(SynConst.Int32 1, _) when isDivide -> !- "/ " +> loopTTupleList ts
            | _ -> loop t -- (if isDivide then " / " else " * ") +> loopTTupleList ts
```

However, maybe to better capture this, we could introduce a special case in [SynType](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-syntype.html).

That workaround will probably do the trick.
`TypeDeclarationTests.fs` would be a good place to add the unit test.

Are you interested in submitting a PR?

**Comment by dsyme** [comment]
Looks like we should fix the SyntaxTree here

**Comment by dsyme** [comment]
> Are you interested in submitting a PR?

At some point - it will be recorded and linked as a limitation in .fantomasignore of dotnet/fsharp, and we will eventually clear those out.

**Comment by dsyme** [comment]
See also https://github.com/fsprojects/fantomas/issues/2265, whenever we fix these we should likely do them at the same time :)
