### ISSUE TITLE
Splitting ExperimentalStroustrupStyle to separate settings

### ISSUE THREAD

**Issue by Thorium** [fsprojects/fantomas#2276]
I love the `ExperimentalStroustrupStyle` setting in records, but I hate it in computation expressions.
Computation expressions are so crucial part of F# that it should be very clear what goes on there.

What we want to optimize? Maintenance.
Let's observe the following code:

```fsharp
let myMethod() =
    async {
        let! x =
           async {
               do! waitSomething()
               return 4
           }
        return {
            Id = 1
            Data1 = "asdf"
            Data2 = "asdf"
            Data3 = x
        }
    }
```

There is no way to create this properly on any settings in Fantomas.

**Comment by nojaf** [comment]
Hello, thank you for opening this discussion on the Fantomas repository.

Splitting `ExperimentalStroustrupStyle` is an interesting case.
https://github.com/fsprojects/fantomas/blob/434df479ee60f7ce3b177af49e047437d4e5effe/src/Fantomas.Core/SourceParser.fs#L1819-L1831

Stroupstrous current works on records, array/list and computation expressions.
You can imagine that if we split one thing, people will eventually ask for everything to be split.
This will bring in an additional churn to maintain Fantomas.
It might be worth having, I would like to see what the community thinks about this.
Are enough people interested in this to carry it?
And of course, what big of an impact it will have on the codebase. Because there would be more changes of course than just the snippet above.

**Comment by josh-degraw** [comment]
Is your issue here essentially that you want `async {` to be on its own line, rather than on the same line as the binding? Because if so, in my opinion that's not (or _shouldn't be_) directly related to the Stroustrup style, which is mainly just about where the braces are placed relative to identifiers. IMO your example still conforms to Stroustrup style with the brackets, so I'd say it would make sense to allow that, but as a different flag, something like `compututation_expressions_on_newline` or something like that.

**Comment by nojaf** [comment]
Available in [v6](https://www.nuget.org/packages/fantomas/6.0.0).
