### ISSUE TITLE
Default values of width settings

### ISSUE THREAD

**Issue by nojaf** [fsprojects/fantomas#2288]
As we are developing the next major version of Fantomas, it might be a good time to revisit the default values.

I believe there are three categories of settings:
- Maximum width constraint settings
- Settings that adhere to the G-Research style guide.
- Auxiliary settings.

The first group is the one I'd like to revisit.
The second group should be disabled by default.
And the third group is probably fine as is.

On a side note, the maximum width settings are not mentioned in the style guide and I don't think this is a bad thing. Different projects will have different needs and some level of flexibility feels ok here.

Anyway, the default value of the following settings might need an update:

- [fsharp_max_if_then_else_short_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_if_then_else_short_width) = 40
- [fsharp_max_infix_operator_expression](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_infix_operator_expression) = 50
- [fsharp_max_record_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_record_width) = 40
- [fsharp_max_array_or_list_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_array_or_list_width) = 40
- [fsharp_max_value_binding_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_value_binding_width) = 80
- [fsharp_max_function_binding_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_function_binding_width) = 40
- [fsharp_max_dot_get_expression_width](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#fsharp_max_dot_get_expression_width) = 50

Please o please provide your reasoning for increasing or decreasing certain settings.
I personally find it terribly hard to change these default values because a few people say `x` or `y` "feels" better.
Changing these defaults will impact everyone using Fantomas, so "With great power, comes great responsibility"

**Comment by nojaf** [comment]
@dsyme any thoughts on this given your experiences on formatting the compiler?

**Comment by dsyme** [comment]
We're using this in the F# Compiler, though that's not necessarily representative

```
[*.fs]
max_line_length=140
fsharp_newline_between_type_definition_and_members=true
fsharp_max_function_binding_width=40
fsharp_max_if_then_else_short_width=60
fsharp_max_infix_operator_expression=80
fsharp_max_array_or_list_width=80
fsharp_max_array_or_list_number_of_items=5
fsharp_max_dot_get_expression_width=80
fsharp_multiline_block_brackets_on_same_column=true
fsharp_keep_max_number_of_blank_lines=1

[*.fsi]
fsharp_newline_between_type_definition_and_members=true
fsharp_keep_max_number_of_blank_lines=1
```

Of these I guess I'd argue for the following

* `fsharp_max_if_then_else_short_width=60` - F# has no ternary conditional operator so there are plenty of times you want single line `if then else`
* `fsharp_max_infix_operator_expression=80` - Possibly 60. Similar rationale as `fsharp_max_if_then_else_short_width`
* `fsharp_max_dot_get_expression_width=80` - Possibly 60. Similar rationale as `fsharp_max_if_then_else_short_width`

* `fsharp_newline_between_type_definition_and_members` - this should be the default, in order to encourage XML docs

* `fsharp_max_array_or_list_width` - Defining data using lists and arrays is common enough. We shouldn't penalise it resulting in sometimes 10s of extra lines.

* `fsharp_max_array_or_list_number_of_items` - Similar rationale

I haven't yet played with ``fsharp_max_if_then_short_width`, I assume we'll want 0 like the default.

**Comment by auduchinok** [comment]
> fsharp_max_if_then_else_short_width=60 - F# has no ternary conditional operator so there are plenty of times you want single line if then else

This is one of the best examples where keeping the existing "single-line vs multi-line" style plus checking overall line length would likely work better in the most cases than checking an `if` expression length.

Tweaking the settings like this can mostly work for a single code base, but the formatter should work well on many projects, and tweaking settings like this will likely lead to aggressively rewriting of some perfectly-formatted code in some projects anyway.

In addition to that, if we want to enable incremental formatting during typing in future, we definitely don't want to rewrite code that aggressively, otherwise it wouldn't be a good user experience, so the formatter has to keep properly formatted code untouched.

It doesn't seem difficult to check if an `if` expression is one of the following forms (the tree has correct ranges for all of them):

```fsharp
if a then b else c
```

```fsharp
if a then
    b
else
    c
```

```fsharp
if a then b else

c
```

**Comment by dsyme** [comment]
@nojaf asked for some more info

This is too much penalty for defining data:
[https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMB[…]wOkaYyoXBF6WNmfRLA4wEDAj8dQgJVg9AVDCNYQkQ03CX3qEAA](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMBbAngIIBOxAhvmALxgDaAPmAIwDcYATGwMxsAsbAVjYA2NgHY2ADjYBONkwAM81s07MezfswFh6AXQA6xAwDtIAGnBQAztiwBLEwHNrqOlYigI3qABIs%2BAAOyGiQjlgWHt6QvgBuZOgAriHuPj4KlmnRAJImSCZYAMr2AF7ImVlgvFEQelEAvhWeNX4BwW5hBZFZMfFJKbQtEExNaZAAsmQAHgAyjogziM5YABbdlUzsCi11Po1RXmP%2BQSmQS-AA8gBmcyaIhQGY6z69Cclug5Ucoy8AonnXW7lIYYK6QHYNUaHF7HdqhABGsFg6Ge0TibwGIK4PxyJlsxCwADFHAkAHKIADu6HmqJ8WGIyQheyhLRibVOiORtL8fXeaE%2BlV4OIgkEKgTI0EQACFEFdYMREAAFMjkXDYRDEbkQemMrK7bz7HzQtHsjqclE4179D4ggTCqBiiXS2XyhawCka6BkWy5WKwL0OWBme06xBMg0snqwjlIi2s9HW-kg4T20XiyUyuUKgCqgWCxC9PpMfoD9iDWrAVwStnDEEN3mNIujZtj3KtfNSlTEqcdGZdCoAwuhvdYB0HrDroFh5RWq%2Bga3rIQd46aEa3LQmOwKspIe%2BnnVnEONELh4RrZ9Ww4vmcuo6uoOa25vMV8ZHunZnXWP0OX7XOF2k%2Bp1pGRz3pAj4bryL4bBkIJpk6hBXFgGpjrguBkBWoa1mA9bNHeJwtlykEYjaXxMCMcG9gerqFCe9hwD%2BwYgv%2BV6AUuRorgRa5EfGUGkRs7DvpKiHIcQtG4PRyK-iCWHXhGt6gVxD7rrxJFJmR2KUfuJCwIkeQACKINSEmiZhDKsT4QE4SBMJgeET58epGxCnBkxTNkVwACorEshQrPKWAAOr2PAqwVtscnAQptlKZ0ETEYmnZZEwdqudMHneUsvzzvc-kEsFoVrPavARWxN4cfhcJQPZCVbiCTApml7kmFc9hTBc%2BZkNOxC-FMgQKtY1hlkxXwCKVlnsQ2nFVXFDlqUlaRMN2TUAEqIHAxDwAVYXFeN3hWbhYCNq0sU1apiXbotu6ret8rwKSiSnhq1zZMhuCuPaTDYYdx1srFuCJOgDjUnchLyuhWCiZ5BG1dByVvnBa0bfA4yA8D8xg8QEOmam0ArCqEqiQA%2BhSIVhd9NkmqdXSw-xWRbKmbkkOQ%2BAXMQcwTttRUgiVFPRVTM1nVGjkLT47AUV8EzTMzFBsxzWAPU9xAvW9H31XzFWKTNANA-YIOIJj2MatD7S0059OCXBMus%2Bz9gTqjuv64bXU43BeME1OGok2Tawa1NlWnELRwi5dYuaZLbkAGoYlKjjwI4ThcxWkh7bUk14Vrgc0%2BddVfOwLkR9MhJ6VOw2x3kCdJ7tfsZzFgvZ8L82h947CpYXUz6bAWAAOLYL1-WIINw1V7aqdgAdlNNmBEE53DaTsI1Edo3r8xSj%2B0AANZSuQm-YNYFwmIUZBqt%2Bj0jZULE10d00xjxjcXSC7DLZL5JUqv2AeksJuIIZrUmPYgYTCEDyMeJWasviX0itZfmU9Yoz3vrnSo7BrqS0INSJwJhi4mFLkGYoGCuqJAVJ5WAuR8hYC6sNC8OUr6-WbNxOMCC55iwRqgoGGoTAUNiG6ZwoCzzEF-o4ABw1wEX0vDQm%2BhEGHBybliWCS9dZAhmMfeE8AyBDlgENZwr99ZUIAhNcq-tM6SLmg-L4XAJaVEgP3DU9g1QFASAAaUQIgQIpClhYFyNvMg2DuYQLEVAn6Ej6EmMQVkLgltJZr28RvIE1gdJ6XuoPZCKNl7637gNIa44zK6jKvJTWddb5SJhCHLE4dLFShVJ%2BBU%2Bk7bQGILYkkyTsz-yDIZaAw5yCAN0RZfa6dr4B2MWbUW3guAF0sdY%2BpdjyHoAeMQXSE4GSBAePgJ4f5-G5KivkgWWd4qzzpmkLgbdLFOJcW5RWfDrhRJMDE%2BYIjkoKDHhPGBJ0ZrwOkaYyoXBF6WNmfRLA4wEDAj8dQgJVg9AVDCNYQkQ03CX3qEAA)

I think this is only relevant to `fsharp_max_array_or_list_width` as it looks like `fsharp_max_array_or_list_number_of_items` is being ignored in my settings because I'm not using `fsharp_array_or_list_multiline_formatter`

But in any case the point I'm making is that data definitions can easily get penalized from 1 line to 10s of lines under default settings.

**Comment by nojaf** [comment]
Hey @auduchinok, could you open a new issue for your points.
Happy to discuss this over there.
