### ISSUE TITLE
Using fantomas in VS resulted in scrambled script file

### ISSUE THREAD

**Issue by halcwb** [fsprojects/fantomas#2371]
Unfortunately a very difficult situation. Working on a very large script file with fantomas enabled on save (working with VS). The whole script file was scrambled up with a result looking like [this](https://gist.github.com/halcwb/eaad0977d962f17aaee78c18e6670a48.js).

Currently, I need to recover from this, so, won't be able (and really dont want to) reproduce ;-( 
I need to reproduce a whole days work. Actually, it is a couple of days work. 

Also, see: https://github.com/fsprojects/fantomas-for-vs/issues/34

**Comment by nojaf** [comment]
Hi, I'm sorry you lost valuable work due to an unfortunate series of events. Fantomas does its best to format your files in a way that matches your expectations, but bugs can happen. This is why the editor lets you undo the changes when using format on save. There is unfortunately nothing that we can fix with so little actionable information.

**Comment by halcwb** [comment]
I understand that without a reproducible case you can not do much. Let me first recover my code, then I will try and see how I can reproduce this on a copy of the script file.
