### ISSUE TITLE
fsharp_experimental_stroustrup_style=true breaks on types with nested anonymous records

### ISSUE THREAD

**Issue by LiteracyFanatic** [fsprojects/fantomas#2413]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBZTdAc0wGUALTAJwIDoBRADwBcnjvYTPKwrVMAEUScAOulmwCidGFoBPPN0TZ5i5Wo1bWAOUTdWACW7cCOpSvWbsx0xatsAUnlhz0CuwDE8ABVYWAAbAGsASzN2JiZBc0p4MKjqWVluVUVyShpJTgBBbnNYXAAlfAJvPFIAXjBgWQgIACNMWoBVJjC0DSY0qmaW6EYCTSY0YAAfYZaWxjx6Pt5BufmweExuTBWB6gBtAF116YBfWQv0SAAacChaq0G8VDAD%2B4hQDagAEizFV6QNLcW4fFqQH4AN0wYQArsg0O9vhAAAx3ZFQACS6CQ6G4tCiAC9kOjkQAWMEQI5gs6kz6U37-BFQYGg74Q6Fw5lI5EARjpG0gFE4ABk0ogRUoqNx6Gy%2BQAmFEM6nzWlgr6Cv7ZZmQJTwADyADMxehELQsmESQyOTD4a8ed95QL5pB2DijSarRjIGFDZBlTSBRqXVqAWhIK1QmE5SHOXbEQyIABmZ3g7G1JjcfxpGEmADuqVNMY2vHhAdVQetoZ1kfCxYgNq59sTYDJqYbtCIJAAQohDYJEAAFZg4UyIJj1lqlxDllpq%2BbB8HVwG16Opxvxt4tgCs7agneIiF7-aYEtgefH0A6iGxkNgV%2B4UW8k4g09nEHnLUXDeX4dXk43bkWwANj3SADx7PsB06AhFCYK9alve9tifa490NGFanfMBP3pdlfygf91yhW0gIxAB2MCIKPKDTwAYTCDo8DompS2gAQJ3QzCZ2%2BFU50rfCmRXKMAJIpsEwxAAOKiuxok9EDILRWnHF8wAwsIsN4wN1SrIS-xE4i4zI5EAE4ZMPY8BxYsJny4jSeI2PiPwEzU9MIgyqyM5sMV5NEW3A2TCkNCYWOwbBMFUt8tIrHTBO1YS60M0jvL5fl-OoyzT1oLQojgGy0JbdTNMc7SF10%2BL9MSzzkokhVzJIIKJmy7BcvCWyWyikqYrKuKw3cqr8K82rvl5FN0sChJYRxSRUhaiZIqYMtov42LXIqlk8VEoatx8tt-OFTFDSCeglAYQRuAAdSieAZVUpVluc1aQzcoFNqS8Sdr5Xd9swThDuOpR2Hss7Myum7ZT3YD7q6laerWvrXpBd7NwdDZeVAn6-vQQ0ok4fU4O2QQuAIU88DwVDVMk6H5icnCXOe9bEa2mrPpGyjMcqOAmHgMHbr3MlqZaWncMacqEdZZHjJG6SOcQLn4CMWFsGUpgjUxRwXj3XlsJF79GUZ7BYTCR9C0QfxBHCqxxyCeLJZSkazP8znBHgMgjZN8VzaYS35rA0YR3Y8cAH082u26dfppcXol6qPtR%2BZFTA4VCniTBVH1JgxQ0XmIZbKmI6eqPGZjwaWfjlp5TS71k9T9PM6iDRFeV8c1Y11TtYeunC5-F7DeNqJTa9n3rdt2OUZbeUnX8lO%2BDrrPuDd-vB4t7Zff8-2%2BEDpgQ7D2UC7hhnxbesepY2eUxur36ADVSO7NJ4EGHPKcFqlSq-MWdRLzVtvLiB5T2y%2BnB-BTXYqhO%2BOJH671UgLfe79eqf2PqXOOE9vqAPELAbgABxUwxNSbk28E-Pc%2BdO66w-glNcJ97ZnwxtXd2A9xTdhstACI3ZN4RFMHgfU6BaCjmskrAqGIioORpm-PC8MaweSQePDE8p2benzKbXs3ALxKBtooSQON0AxFQoUHEilm5CAWktGGj0D5FwRkRShw0z4y29IUVIVB0DAPQKA7wBJHHbFhKeEI2JcQ7EfO1QR3FYFiMPhIga38y4T0dnY4244sCPkhGeag%2BiVYaLSNomoqkhEhNFvA8hzNkEYiTH5Wh-dPQihwK0LYDFYDk2oAo8U2TgkkMjj3RmlipGn3mEmKuyJXScDglEXAeIYQAGlECIAIL4pQ3BsSsMoKMZp9lcl6whC9TpkSinIiTFPb0jDKARE9HgFOsApoK3wJoV2dDTa4PwPg9AmsOqLWEULUReTxEFLttYnpF9%2BndmYJlRA4gG7QAGC1BJiB4CdC0d4SQ0BGJ8ACQI5EOTWnd31hYyRWzpE7IAf04m45hmzJhOaSa-RYQEHNKoS0RjXmv26nAz54Yv6xiicU1B-SJlTOFE3FWRoDnoCOeKJ5PkUQvzAMLNpmLwkUK6VQnpND%2BlktygvBAXpUUtJMThe4RxSRAjwIEKIrwclnCAA)

#### Code

```fsharp
namespace MangaSharp.Extractors.MangaDex

open System
open System.Net.Http
open System.Net.Http.Json
open FsToolkit.ErrorHandling

type MangaDexAtHomeResponse = {
    baseUrl: string
    chapter: {|
        hash: string
        data: string[]
    |}
}

```
            

#### Result

```fsharp
namespace MangaSharp.Extractors.MangaDex

open System
open System.Net.Http
open System.Net.Http.Json
open FsToolkit.ErrorHandling

type MangaDexAtHomeResponse =
{ baseUrl: string
  chapter: {| hash: string; data: string[] |} }

```
            
#### Problem description

I often use types with nested anonymous records when modeling JSON responses from external APIs. The new `fsharp_experimental_stroustrup_style` setting seems to break on such type declarations.

#### Extra information

- [x] The formatted result breaks my code.
- [x] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-08-06T07:12:17Z - c1d5250db7f583191c3152a2e1d7bc8b0e2e096e

```fsharp
    { config with
                ExperimentalStroustrupStyle = true }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hello, 

A couple of things here.

Using `fsharp_experimental_stroustrup_style` without `fsharp_multiline_block_brackets_on_same_column` does not make any sense. `ExperimentalStroustrupStyle` is an extension of `MultilineBlockBracketsOnSameColumn`.

Enabling both will lead to valid code:

```fsharp
type MangaDexAtHomeResponse = {
    baseUrl: string
    chapter: {| hash: string //
                data: string[] |}
}
```

[sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKA7AhgW0QZwAdNpEwBZTdAc0wGUALTAJwIDoBRADwBcnjvYTPKwrVMAEUScAOulmwCidGFoBPPN0TZ5i5Wo1bWAOUTdWACW7cCOpSvWbsx0xatsAUnlhz0CuwDE8ABVYWAAbAGsASzN2JiZBc0p4MKjqWVluVUVyShpJTgBBbnNYXAAlfAJvPFIAXjBgWQgIACNMWoBVJjC0DSY0qmaW6EYCTSY0YAAfYZaWxjx6Pt5BsAB6dbn5sHhMbkwVgeoAbQBdbemAX1kb9EgAGnAoWqtBvFQwE%2BeIUB2oAAkWUUn0gaW4jx%2BLUgAIAbpgwgBXZBob7-CAABie6KgAEl0Eh0NxaFEAF7IbHogAsUIgZyhV0pv1pgOBKKg4Mh-xh8KR7LR6IAjEydpAKJwADJpRASpRUbj0LlCgBMGJZ9PmjKhf1FQOy7MgSngAHkAGZS9CIWhZMIUlk8hHIz4C-7KkXzSDsAlmi12nGQMKmyDqhkinUevUgtCQVqhMJKiO8p2olkQADM7uh%2BNqTG4-jSCJMAHdUpaEzteMiQ5qw-bIwbY%2BFyxAHXznamwFTMy3aEQSAAhRCmwSIAAKzBwpkQTGbLUriGrLS183D0ProMb8czreTXw7AFZu1Be8REIPh0wZbAi9PoB1EPjYbA79wot5ZxB54uIMuWquW%2Bu0abrOO78h2ABsR6QCeA5DiOnQEIoTB3rUj7Pvsb73EepoIrU35gL%2BzLcoBUDAducKOmBOIAOxQTBZ5wZeADCYQdHgTE1JW0ACDO2G4Qu-wakutbEWyG5xiBFFtimOIABx0X2DEXogZBaK004fmAOFhHhgmhtqdZiUBEnkUmVHogAnApp7niOHFhO%2BfE6QJOxCT%2BIm6kZpEmXWZntjigpYh20GKYUpoTBx2DYJgmlfnpNYGaJ%2BriU2pmUf5QrCsF9G2ZetBaFEcAOVhHbabprn6SuhnJcZqW%2BelMkqtZJBhRM%2BXYIV4SOR2cUVQlVVJVG3l1cRfmNf8goZtloUJIiBKSKkHUTLFTBVvFwmJZ5NUckSkljXuAVdsF4q4qaQT0EoDCCNwADqUTwAqmlqut7mbRGXlgrtaXSQdQqHsdmCcKd51KOwzlXbmd0PYqR7gc9fUbQNW1DZ9ELfbuLo7IKkEA0D6CmlEnDGkh%2ByCFwBCXngeCYZpsnw-MbkER573baje0Nb9E20bjlRwEw8BQ49R5UvTLSM4RjTVSjnLo%2BZE3yTziB8-ARiItg6lMGauKOB8R6CvhEv-qyrPYIiYSvqWiD%2BII0VWNOQTJbLGUTVZwW84I8BkGbFvStbTC28tUGjBO3HTgA%2BkW92PQbzNrh9Mv1T9mPzKqUHioU8SYKoxpMFKGiCzDHZ0zHb1x6zCejRzyctMqWX%2BunmfZ7nUQaKr6vTlrOuafrL1M6XAEfab5tRJbfsB-bjuJxjHbKm6wUZ3wTd59wXvD6PNv7IHwXB3wodMBHUeKiXSMs9LX1T3LOzKlN9eAwAapR-ZpPAgwF7Tot0pVf5SwaFe6vt1cIDKiOrfTg-g5rcUwk-Akr9D6aRFsfb%2Bg1f7n0rknGe-1QHiFgNwAA4qYcmlNqbeDfkeYuvdDY-xSluC%2Bzsr443rt7Ee0p%2BwOWgBEfsu8IimDwMadAtBJz2TViVHEvUGZfyIsjBsPk0HTxxMqbm-piyW0HNwG8SgHaKEkATdAMRMKFAJKpduQgVprQRq9E%2BZcUZkVoeNK%2BCt-SFFSFQdA4D0CQO8CSFx%2BxESXhCPiQkBxXzdRxGVFy4j%2BpIKkdQ9m6D5Gu0cebacWBXywivNQIxGttFpD0TUTSYTEGSNPtIka-8q4djTEFRhw9fQShwK0PYLFYDU2oMo6U%2BT%2BKFMlsgmJTs7HzDTHXdEnpOBISiLgIkCIADSiBEAEACUobg%2BJOGUFGB05yXSjYwg%2BjY2Rl8Blz39KwygERfR4AzrAOaKt8CaE9kwy2hD8DEPQLrHqq1wliwkd06JtUaF7LoQMm%2Bwz%2BzMFyogcQLdoADA6ikxA8BOi6O8JIaArE%2BDBJEeiApFDY4D1ZrsspcT0RphAcM8m05xmLIRNaWa-REQEGtKoW0piPmf0iUUqxKC0a2M5jsNMmDhkzLmeKNuGszTHPQKc6UryAoYg-mAcWOLjbWJkQSuRRKGHDOpYVFeCA-SYs6RQ54ZxKRgjwIEKInwClXCAA)

However, and this might be the point you are trying to make, the anonymous type does not appear in the  `stroustrup` style.   
You would need to fix https://github.com/fsprojects/fantomas/issues/2412 first because there is currently no implementation for `MultilineBlockBracketsOnSameColumn` for anonymous types. 
Once that is in play, another change would be required in record field declarations of the record type definition.

Are you interested in submitting a PR for this?

**Comment by isaacabraham** [comment]
Just to add onto this, I'm seeing this with both stroustrup and multiline block brackets [same column](https://fsprojects.github.io/fantomas-tools/#/fantomas/v5?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvGMAD5gAiAhltcaRQHLUC2iDAOpAJIDO1atG4BuMAEEA5hxIAWAMxiaATy6QAsrAB28astFgAwrHSwArgCc1AIXRnE3MGQC%2BT55AA04KH2xYAllqSfKhgANreEKAQMVAAJFjKAA7IaJCBWJ6RMZBxAG7Udqnh2bEADF6xsbw6iFpYAMr%2BAF7IlVUQsqVgALrZzu1R3bmJKaHp9VkduQVFoREdEACMg1Ua1AAeADKBiFt1klgAFlOLSwBMZd19sQPZ0WsJycWQdfAA8rg7WogNiZinar5Qr2ebdCDnVbVACiOk%2B3za4IwuEg136qweQNGLwARgR0ICcsC5mgFot5FCcjwtL4LFgAGKBQpMRAAd3Qu0JsSwFnsaNuGOGTzGaTxJi58VmoNJSNklIgkAaSSEiGsiHwFkQAAVqBY2NhEBYJRAeXyOjcYndYpiidjxmKCZSZiDimSOgBWeVQJUqtUavawVmG6DUXzUvKwEMBbTGsCmxD8y2C6bC3H4iXOkklRZgABsXsVyugqvVsE1AFUkikLCGw1oI1H-DGvbhCr5ExArTEbQrU-b007idLs4sAOwFn3Fv1lxCGdChvjGGmm6BYMux1vodvm9H3IV20UDoVS11IgAcE6LJf96kQrBxho3bYTO4Fe5TB6gDozQ9POYAnJevqlpqximFoT5bi%2BVQWp2yaPJ%2BkDfoOJ5gjmSwVEihYquIuBYIaxisKw1CxvGHZgF2Qwfs8-biihLpoWcKxYZO14zg0d7%2BHA4GQduMG7ta%2B40YedHHgxMroZCLFXrh%2BEWBxrBcSYzZImRr5Ju%2BCHCV%2BR4pqhElnBS0k4RY5g6JQiAcopcmkby0GxLBFHwVi2kTJk9FZm6VRLHKWHqJsPC4AAKkcdQNEcZZYAA6v48DHLGVzqXBmkuSKUAZD%2B%2Bkjh0Syen5AXBaFWjQlB4WRTFcUnF6uaJfxb6CdRaVuZl4nZd5%2Bb5Rs1K4P4GzvNWtBltCGxJJqfB8E2EFemetUOQJ3ZCU1GUecOXmxEs46dQASogcAWPAFXxV6sizTEjmUaQi0vMtYmeUiSwXttu1lvATBmPehqfDw%2BGsCEXpLORF09vEiGsGY6ABByPz0mWxFYHJQU0Stf5nIBWE7Xt8DqODkO7DDFhwzZBbQEcupCHJAD6rKxfFgPObark3XprVrTElwFv5GziBYerKO8Fg7Hw0U01V56nRA53072iFM48WWsxCzE5usXM83o-OC1gb0fRYX0-X9910ylDNNWDEP%2BFDiD44ThqI2MyOMR05xScr3O8xr-hC9j5uW9btBE1hJNk6uhpUyLqJJU5xvS4zkwOwZTtGcrnMAGoutYgTwIEkiHaLOYzUbDVaUtce3atSLnL5yebPSZhaKuk0Zzo2e57GJ2FwtjXXaXzN3Tm5x5dXGyULAWAAOLYMNo2IONk2t9N4u9PNVHF2mom9%2BX-cdcnOMW7stiRgA1tYerQIf2B8O8WgNPqYHvVNql2R3K%2BpWvjplyjTubcrLLsvv2BBjqHbRAFkepaH8NGLQ4gdC3h1gbHMak6oaSLq-Wi78N6fyqOcR6rsOSSC0LXeukCmj4NoJYRAQVYDUiQPUWgk1eL2TOsvS6Xc0EtT7osc4aNcFyS0HQvIAYgiwIfBYUBgQIGTXgYsTcfE5r1U7qvNh8c2qxHkJhHe5sERbDYDiXQc5YATSCL-S2DDn4sMUSJdBcsWZInkErRYkAp6Gn8OwWh6AADSiBEBJGoXULA1IT7UHrnnaRz4zHAxGK5ZCH9HZVHkC7BxtggmHwRHwbmZlXoz3wljXelsp5jQmtoKRHREFyOQQo1Blj2Gb3JEnRJuppyakoJ7aAFgXFMmyeWcB2gLLQHnHqSBpjI5AyukomJCc4lVwcU4tpri6DoD%2BKZMwQteRJD%2BMoAEXpSlMPkS-E23d3LjJUTEeQg8HGeO8ZzbWIjPhJK0Ck3YxTvJlEXpLaOIMom6WsRwjo8ht4OMWVxLAmgkBDKQZ2bwPR2jpD4PSCaoQZEJmcEAA).

```fsharp
let foo = {| Data = {| Name = "Isaac"; Age = 43; Day = "Monday"; Colour = "Blue" |} |}
```

goes to

```fsharp
let foo =
    {| Data =
        {| Name = "Isaac"
           Age = 43
           Day = "Monday"
           Colour = "Blue" |} |}
```

rather than what I would like to see:

```fsharp
let foo = {|
    Data = {|
        Name = "Isaac"
        Age = 43
        Day = "Monday"
        Colour = "Blue"
    |}
|}
```

This is important for us on Farmer because we create very deeply nested anonymous records which represent Azure ARM JSON. Without this setting, the files go wide very quickly (although the Stroustrup setting does help otherwise e.g. lists etc.). Once you get to 120 characters width, Fantomas starts to (understandable) wrap text very quickly, leading to files that are very long yet lines that are 95% white space and just a few symbols at the very end.

**Comment by isaacabraham** [comment]
Confusingly, whilst inside an anonymous record, even lists seem to stop obeying the [Stroustrup style](https://fsprojects.github.io/fantomas-tools/#/fantomas/v5?data=N4KABGBEDGD2AmBTSAuKAbRAXMAzWsYAvGMAD5gAiAhltcaRQHLUC2iDAOpAJIDO1atG4BuMAEEA5hxIAWAMxiaATy6QAsrAB28astFgAwrHSwArgCc%2BDANphuAJUTwD3AELoziV5ADqACwBLLG9IMW4AeQtqLWkfJxcw%2B0gPLx8A4NDwyCiYuKTHZx9UrOSMkJ9c2NLCxOyS9KCKgpzo6u4wAF0wMgBfHt7OC04tIZGxrUwcaxI7WuLPGr8mpar87ISFtJby1bb15M2Whp2Vyv2lo-rFxszzvNCuyAAacCg%2BbCxA2L5UMBs3hBQBAQVAACRYZQAB2QaEg3ywL0BIMgYIAbtRFn8AaDQQAGV64lE8HSILRYADKgQAXshCUSwLJkRBOsjevSgczwZCYX94eSkUTURisWgcQyAIwc3EaagADwAMt9EAqyZIsP5BZKAEx4rms0Hs5HAmUQ6GwqBk%2BARXBKrSICmQzBa0HCzFebFciDa6WugCiOhtdrpXowuEg%2BrZ0pNrrNvLhACMCOgXSj0e6LeKifJfcStB8LFgAGLfTFMRAAd3QytToKwFi8kcN0a5qJ5FsgSZMtfBIo9YtDslzEEgFKhQkQbkQ%2BAsiAACtRouwQhYexB642iQaQUbQTG0%2B2%2BV2U7m3aL-qGAKzDqBjidTmcq2AVxAWaDUD4ktGwd9fbRrsAN0QJsdxbIU4w7Y8ezPfsLwZMAADYb1HcdoEnadYFnABVKEYTfD9EC-H9aECf8b1wTEPhAiBdxBfcRwgo9k2g9NzyzXEAHZkLvNCH0wxBDHQD8%2BGMfMN2gLBMIAij0Corco2NVtGMTZjT1Y2D2NBAAObjUPQx91EQVgE1faTKOA%2BTm0U8DDxU7s1L7TNQwATl0%2B8MNnYxTC0MzZIs3FtxosDTVsqAoIcjNPXgiUCVDFCJ3EXAV2MVhWGoACgOosBaM5GzzSY%2BylMcqLJSlOKeP0-iKSMwI4G83y5IChS9yU0LO1UorIoHaKfXKvTEpXarWFqkwyNDTLLNA6yQvyuyT06tjQwlHM%2BoSixzB0ShEGrYaVwyht-NBQLsuC2M2oRFjiu6yUhzi9R5R4XAABV-DJCl-EwrBfECeANQAvVJqC6aztmqALoixbouvO6Hue16tD9Pz3s%2B77fs1G8EIBpqrJavL4zBgUIY0pakJhuUSVwQI5QiPDaEwv05ShWc%2BD4UifJvLSsaO5q6Na0H%2BURImnOiriyacOALHgVG-pvWQuZBY6ctIPn8YFy6urgyUdLFxAJfgJgzGM18bR4EJWF%2BG8JSypX6O5fnWDMdAvmre0i0wtKsBXJ78qFkqiQlVy4vFzD4HUR3neVN2LA9vbkOgfxFyEFcAH0Kx%2Bv7rdOg9%2BfBhbifg3VkPuuVxAsaJlCiJU%2BC%2B9P0dDTnM%2BB7PVdz8Crs1oltTK%2BDZRLsu9ErwJq4No2LBNs2LaWxvcZm1WHadwIXcQKOY9fb3eV967O96nvS-Lwfq7Dhel5X2hY7i%2BPE4k19U9riNAZOpuGPOwm8%2BFhltRWnvi4ANQzNxvjwG%2BJIaWdd4INwfjbFWHZW6mnbppEE2pbrf3lEWMwWgJJswAToYBoCAJy2nrzPGMDX5tw1gg700MUFykoLALAABxbADMmaIBZmzPBHN5Ysh5rlWekEOpkMhh-Um39w6L2VB4H8ABrNw0RoBSOwHwCIWgKRsAEiYQ27NxoHUIbwkGqtwpvz9ribUose7lirBI7AL4yTr0QFtSmWhghs3EDoQyo9J7wQmtjKaM99H8MKoI-OH9ta72rJILQaCMF-hUYECJtBLCICerAEkSByQkTGvBGSjVuY4yIXwgq80gnv07oHMJK4tAkTRE%2BWI7iTIWAcd8Zx2hPEMmyYdBWPDlbEMKerIR2ZYqiIXsGBUbAEy6EErAVmsQLFLwah07heS9HNwCUUuB5DQzyG7gySAzDXyBHYOk9AABpRAiAoSpLJFgEksiYjx3mbo7pBS5p9OCdmHeOyPAxCkcGPgpcNr61YSEUOYil7MOZqzFp%2B1Nw%2BKBn4lZvTN4d1xPIL%2BnzFx8VnJQIe0ALAHNLMCrCTjtBbWgEJaIMSHmQKzs-fmhjinGNBPIZBOy9l4sOXQdAjp1pmGrg2KEjplDOhvN43Jvj8n%2BL5LA2M8DNlUJ2ac85xcR71JtF8rQPzlStP9niLhXQum2zbHSgR6z%2BkopETs7ltUsCaCQFS2F2U3idHpPCPgRZWZ-HaSAXoQA).

**Comment by nojaf** [comment]
Hello,

We recently changed the online tool, to enable Stroustrup:
![image](https://user-images.githubusercontent.com/2621499/210503413-080ac6b3-5e12-4f22-b66d-a7e276e48f4e.png)

> This is important for us on Farmer

Important enough to send a PR 😉?

**Comment by isaacabraham** [comment]
@nojaf thanks for fixing this :-) Farmer suffers from this enough that I'm happy to contribute to an issue and give minimal repros. But I simply don't have the time to contribute more to this project, as much as I would love to :-(

**Comment by isaacabraham** [comment]
> We recently changed the online tool, to enable Stroustrup

Is this change cascaded into editorconfig or are the old two settings still valid?

**Comment by josh-degraw** [comment]
I made sure to keep backwards compatibility, so the old settings should still work, but using the new setting should hopefully be less confusing :)
