### ISSUE TITLE
Incorrect async indentation when inside of a match

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fantomas#2501]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAbRAXMAPMAvADoBORAdhBALYCGW0AFmAA63QDWtA5ogEqJuASwDOWEvSGxyAVRLowAdyFZGpClTAAfMAGVY1RK3ZdeA4WIlYps%2BWAC0APnXkXmzbREBPctDDAXN3dgzBwSRBEWaREjAjAiSATAskpg93CsAFcSSiTElLTC%2BIK0gF9kjSodADlpIycwADNaIXRlVXjIAAUTHiNwi3FJaTBshXJYHEbYTPJ4JJTIABpwKBisa3JuEVQwAG1ViFBgyAASLC8WZDRIIXIsZcOqM4A3WnRM6-2nzQAGFcKkAAknNEPddEIAF7IAFpAAsPzAAF0nqVYUdEWcLlddrd7o8Tqc3h8vgdCgBGdHuSAAWVouAAMndEAywdxVAS0gAOX6IlGaNFPY7U86XL6QMHwADyjSZ5EQugumE5mle70%2BuzJaQATFTVQBROYyuUwxEQSDoRqQPmoqnC1WinE3ABGsFg6BVzyJ6tJZrAAGY9c8QTESFgAGJ3d7VRCKdDMz2acSfG0Cu2Yx3i13uxNQb0kzV%2BuFB826NjQRAAIUQ03CPQkhiwiBIuYgycQqaogs09q92Kzbo9QbVBbQWuCAFYS1Ay%2BwqzXYOEGbBFM3oJ5ECCXrB19ZpK2wO3OxBu1Re%2BbM7js0OM8SNWO-QA2aeQWcV6u1xAyFhXEjrmJbjuwzkAezToDEx5gKeGKEv2V6DrmI73t8hQAOwvm%2B86fgAwugngiNh0TJtAWCLqB7wQcE-JdumsFivBObDvmyHju4XIYeWWGLogNKINQzrNuR4EdlRtpChmcEughTF3r6hQAJwcXOH7cYR6D7tOYGUe41EnrRIqSVA16IcxclpOS-x%2Bq%2BnEAIKNE2JCEdQdAHkeolpuJdFOkZ0m3j6hYUpSVmYSp4S6HxQhwOpIGaRRIk6WJPYSfRUmMX5o4oeZurBbZ9nNuF1CRe6Gl%2Bm5CUeUlXkDmlhKyQF5mBjlc42SQMxzAAIog8aFQ5rkkCm7k0Z5BkpVAdwPDJ-kPhSxZWXSuBAo0AAqjBgrojCLlgADqQjwBy068oNenDQ6hl4hN6UsX65JTnN9KLStYL6sJ62bTte2MAej6HeVQ2VSN3nnSZdXTeZz53Qt5CNEIuBSr%2B9CLvquAsOEIgiDYB48pB0H%2BMlgPjcDU2ZcE5LoRDAhwCQ8Dvftfo-ZoulQfpp2jUDk0Zaxmjkux5OIJT8DVJk-HNjKQJNtQOzTuS2PM32rPUJk6DWPG8rhoudAbM2S30ezV0UopVkU4u8A0oryvMmrJAa71L5MLQEgkc2AD6ygfdaR1Mydcv4-iutmcE2qWYC80tRIXhSiQTJiDTn0HTLXsXmdBN%2B-VAdBcH9Kh7Q4eR6IWCC8LJCi%2BLkvXfH-0s4DCtK60Fvq-QDnaziKegwH2WAlnOdR1gps1yriCW9bgm24w9vsA5Lu7Ry5dnnj4rJ5d-vuNqjUZ7gABqPqVnc8B3NwMeY-TVCMzj555knvuL6ny%2BzWv4azCRNjb3Me8H9OcJHxAJ%2By4nrML7VRNOZUG1LdNe7VJgAHFsBIxRhEdG0g35%2Bixh7U%2Bc8GI3gARzP02pwbBzNrXeUlZ1KcErA7Dg2ARBSnILoWghg1JCxiqVfq8UGaJVnlVdBhMsGFG1GTQEMY4zMmrFgVcYIm6IE6tDcgKgbA2TmLxQupdChlVYRVdhANqoYJFCDYmy8eYd3jNwcg99fB7moUIIx9BsiICWrAEESB7jASEtpVRf11GV00VwvWOoDYGIcuQSQLwWTSG4AogSJBJF3BkdEZxLDj5sJghozhLddGaH9EHNItJ8EmgZLQ508BaC4VgOjLYAj%2B59QGr9Y6FdvaeJSUAiA-p06ZJgc2IQhhHHoAANKIEQCwexYIsAglIbQXwsc-RaTiV-BJuMOGpS0Q6HRDSAzt0yUQ0ZHATQiBam1AWEQmwm3wf3GBqN4HkCUWkFR8S1GJI8ckq%2Brd3D%2BlXms%2B2oUJGiGgCQdpUYDkyGkdITq0A8JWAxtOK50ybmzKSfMrxS80m3xacjNpHSsDvEVK1TIlhMgsEVF4ZU4LmEz1ubU3E-9tGAL9P6UBmSel9PmgXcJMp1nkE2cyC5JNiXQrubC%2BpVLcGZIxZFHuCBTSFEmdjVYSJYS3BEOGdGuwJWlCAA)

#### Code

```fsharp
let x =
    match packageRegistrationUrl with
    | Some packageRegistrationUrl ->

        async {

            let response = ""

            return ""
                
        }

    | None -> failwith "Package registration url not found"

```
            

#### Result

```fsharp
let x =
    match packageRegistrationUrl with
    | Some packageRegistrationUrl ->

      async {

          let response = ""

          return ""

      }

    | None -> failwith "Package registration url not found"

```
            
#### Problem description

The `async {` is not indented using 4 spaces but 2 spaces only.

#### Extra information

- [ ] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas master branch at 2022-09-11T16:37:09Z - 7fb34e52debe65604158a2a9730a5d8927a47d9f

```fsharp
    { config with
                MaxLineLength = 80
                MaxRecordWidth = 0
                MaxArrayOrListWidth = 0
                MultilineBlockBracketsOnSameColumn = true
                MultiLineLambdaClosingNewline = true
                BarBeforeDiscriminatedUnionDeclaration = true
                ExperimentalStroustrupStyle = true
                KeepMaxNumberOfBlankLines = 1 }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#ignore-files-fantomasignore)?</sub>

**Comment by nojaf** [comment]
Hey there,

Well, this opens a wonderful new can of worms😔
If there is trivia before the Stroustrup expression it should not start printing the code at the current line.

So, without the addition newline you would have something like:

```fsharp
| Some packageRegistrationUrl ->
    async {
```

formatted to

```fsharp
| Some packageRegistrationUrl -> async {
```

I assume Maxime you added the new line deliberately?

//cc @josh-degraw

**Comment by MangelMaxime** [comment]
Hello,

I think I added the new line on purpose yes. The code where, this bug occurred to me is pretty dense:

![image](https://user-images.githubusercontent.com/4760796/190120642-f85aa522-fa0a-48e6-8973-cfbd5e0408d1.png)

Adding the new line, made it a bit easier to read it.

**Comment by josh-degraw** [comment]
@nojaf What's do you think will the best way to handle this? Could we add a check inside e.g. `autoIndentAndNlnExpressUnlessStroustrup` to alternate based on if there is trivia before? Or would it have to happen more locally to the expression type? I see `lastWriteEventIsNewline` but I'm not sure if that's all I'd need or if I'd need to do more manual inspection of the trivia.

**Comment by nojaf** [comment]
Well, I'm afraid the problem is two folded:
- It can happen if there is trivia after the anchor (`->` in this case, [sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKEIFsCGAXaAFmAA7bQDW2A5ogEqJUCWAzrgE56OwB2AqmwBswAd0a4CAHTYTuGMAB8wAZViZEJMpRr0mrDri59BYALQA%2BMAHpLUmXLnZmAT27QwwW90-2fYAYlwwNkRmYh5mdQBeMAlIWM9vXzlg3ABXNll4uOlZXwBfRIhFADkedXMwNQJIABpwKAjcA24qZlQwAG16iFAfSAASXCdiZDRIRm5cWu6MAYA3bAFU0c6ZuQAGOqTIAEluJEmlRgAvZC3fABY1sABdGbzznuuBoZH28cnpvv6FpZWupIARke9kgAFlsAAPAAyE0Q0MQLXEX18gIATOtrnc5A8Zr1QYNhitIIj4AB5ABmsO4iCUQ38KLk80Wy3aAN8aJBTIAovtKdSztcIJABBTIFj7iD8UzCW8xgAjWCwASM2Y-Fn-IVgADMXNmewibFwADEJotiohhAI4aq5OxlhKcVLnrLiYrlbaoOq-mytRc9cKlKRoIgAEKICmwYIABWwHDUuEQbE9EHtiEdGFxcmlatebqVKr1zJ9aHZPgArAGoEGyGGI1H4bBhEnoI5EHs5rBWwYeCmwGmMxAsxgc8LXe93YWXb9WaWtQA2KuQGsh8OR4K8YgjNitiIdrucXtVimLCKDsDDp7fPMTgue4uz1ZJADsS5XdfXiAAwgJHMwv%2BE9rQLgUZ9ieAhnj42KZs615EreHpFt6j5lvYAAcb7Bh%2BDZgogmDykmYGnumUGSniLo3gqd5ITOmpJAAnJhtZrg2AECEeWrgZB9jQUOsEEpRUCTveyF0aimxasuWEAIIUombAAZgOB9gOpFOuRcFykJ1HThqvpAsCknvixwRKHhjBwOx3BERBJE8WR2YUfBVGIbpJZPqinJGTJclJmZmAWcqHFJKp9nqY5mn5q53y0fpqK6t5tbSWwsCpPsAAiiDWgF8kqWwDpqTBGkCc5UATFMNF6XOQL%2BpJEKQjsFIACoEIiSgEFGuAAOqMPAyJVpihV8cVMqCR8FVuShWqApWdVQo1LWItytntZ1PV9dUVbzoNYVFRFJVaeNImxdVqKLnNDXcBSjCQmS254FG3KQsQwTMMwhh9mhO1yLxF78aNpVHZV7moXIgKvhd9BwGw8Drf1frfRgv2Xu4TmHeVx1VR5PiAhhkOIND8DFKk%2BFJpSOyJpgbRVoC54o6OXpjZgqQCAY1o0saUY4E0SZNfBwNTUCjGSVDUbwGCLNs3CnNsNzuVLoQcZkPJAD6ogbeKQ1-SNuaAxjAtiT4GJLvVyUcE4ZJsLCrBw5tWpfXT-26%2BjnwG3FRuGdsptsOblvW7gxOk2w5OU9T02OzrY5M5LjDs4gMty7z-OTYb9hol52xm9gFtWywuAS6zsfS1zeDy5JiscMBSZq71yIR-tAMuxNMVY6DGBoglXtQgAahqoYTPAExULbn2IxAyNO1Heuuyn7tp7VXeQsaaXAYY-f7EPI9VhcY%2B3A5I5o8S%2Buz6dRuzYv6WwLgADiARPS9ITvTwW-27vE%2BR4zgPCW7p9p%2BdXsxzjqGdiFBQyV3IAEZgZJuBKGwGoNiJNrJVlCj9feV4DpRSnC3EGWo0QQ22BaK0cJwy4GbIiPmIxMrXW4GIQw0l9i4SDmHEK%2BU7KoPCgfSKCEsEEhOtjNOeNM7WioNwZergewwMYCIvA6REBNVgHsA4uBDxIM4sReunCMHcMxjgpIaJhZCPktwTgcxGwtEYQRNgVCJi0PCDZbi7C9qaMbpgnRgtfDagkgAwuApoRwPlPAbAP5YDvRaIQuO9i2FIzQajLhLkeEyj4W3CA2pPa%2BEgPfJMjA1CTEWAAaUQIgYgijES4D2GA7Arg7ZJC4lE8eMSGYvC-jpbB7ifDagzuk4BlTyACmYMlVK%2BwLSsEQOLQBcJ76vSftwZhvgUHRI4eglx2if78LkNqTuXS4wmUQOlFg0A2DZLNImeAvAaE8EytAX8%2BgPrHnUVremh8VknzWRgbUC90mZMOTk5RAg6QpVSHoVIxA6ROAZMg1hGilnOyPjPVpqd1nn3SQUop9VA6WMpN07gvS4SzJxusN%2BDSnnxLcQit5-90n-IsvnBAgoan3N2kOeoNxzjjGYMad67RakgDyEAA))
- And occurs if there is trivia before the Stroustrup SynExpr.

We might be able to check these conditions in `autoIndentAndNlnExpressUnlessStroustrup`, but that wouldn't cover all there is to cover I think.

@MangelMaxime, do note that adding the additional newline deliberately is forcing Fantomas to behave inconsistently. If you are working in a team, another team member would not have made this decision, leading to the entire codebase being a mixed bag.

**Comment by josh-degraw** [comment]
@nojaf This probably merits discussion in the style guide repo, but when formatting my team's codebase it brought me back to this issue.

I wonder if for Stroustrup we either should put computation expression names on their own line, or have an option to do that. I'd actually lean towards the first at the moment to be honest.

I _personally_ think that this:

```fsharp
let private extractMissingHeaders (error: CsvHelper.HeaderValidationException) =
    seq {
        for m in Regex.Matches (error.Message, "Header with name '([a-zA-Z]+)", RegexOptions.None) do
            yield m.Groups.[1].Value
    }
```

is more readable than this:

```fsharp
let private extractMissingHeaders (error: CsvHelper.HeaderValidationException) = seq {
    for m in Regex.Matches (error.Message, "Header with name '([a-zA-Z]+)", RegexOptions.None) do
        yield m.Groups.[1].Value
}
```

But, aside from the personal preference, there's a logical reason to prefer the first as well.

Stroustrup is about _brackets_, whereas this brings the first line of the whole _expression_ to the first line. Changing to the first form here still has the `stroustrup` style brackets, but keeps the _expression_ itself on its own line.

**Comment by nojaf** [comment]
I had similar thoughts on this, let's discuss this further on Thursday.
