### ISSUE TITLE
Please retain --stdin & --stdout options in the cli

### ISSUE THREAD

**Issue by kaashyapan** [fsprojects/fantomas#2665]
I propose we ... retain --stdin & --stdout options in the cli

The existing way of Fantomas deals with this problem is ...It has been removed from the CLI. It works but does not respect editorconfig.

## Pros and Cons 

These have been removed from the documentation but it still appears to work.
It is a useful option to have when using from plugins for vim, emacs etc.. For e.g mhartington/formatter.nvim.
Although fantomas is part of LSP, I sometimes get a timeout and it is useful to call the formatter while bypassing calls to the LSP server.

The disadvantages of making this adjustment to Fantomas are ...
Cant think of any.
Work maybe required to add some tests. If it is too difficult to get at the editorconfig for the project, it can also be handled on the editor side. Maybe add tool argument --config "editconfig/filepath".

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] I have read the [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/main/CONTRIBUTING.md).
* [x] I have [searched both open and closed suggestions on this site](https://github.com/fsprojects/fantomas/issues) and believe this is not a duplicate

Please tick all that apply:
* [x] This is not a breaking change to Fantomas
* [x] I or my company would be willing to help implement and/or test this
* [ ] This suggestion is part of the [Microsoft style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) (please add a link to section if so)
* [ ] This suggestion is part of the [G-Research style guide](https://github.com/G-Research/fsharp-formatting-conventions) (please add a link to section if so)

**Comment by nojaf** [comment]
Hello, thank you for your interest in this project.

We removed `--stdin` and `--stdout` because we had no clue if anybody was using this in the first place, and due to the maintenance aspect. Quite some code was involved for this earlier (see https://github.com/fsprojects/fantomas/commit/2ca49d0854454fa3535eead10ca90fd0cb788521) and it never worked perfectly in combination with other flags (f.ex. `--check`).

Having `--stdin` in itself is insufficient to format the code properly. We need to know a file name as well to determine if the file is a signature file and compile the `.editorconfig` settings. The way `.editorconfig` works is that it resolves from the file point of view and not from the config file point of view. We never nailed this in the past, so the removal made a lot of sense.

> Although fantomas is part of LSP, I sometimes get a timeout and it is useful to call the formatter while bypassing calls to the LSP server.

Please elaborate on that. Discovering why you get timeouts seems a lot more relevant than this workaround request.  

And could you also explain to me why you specifically need `stdin/stdout`?
What is preventing you from calling the command line tool inside your editor? 
In other editors, you can configure an [external tool](https://fsprojects.github.io/fantomas/docs/end-users/VisualStudio.html).

**Comment by kaashyapan** [comment]
> Please elaborate on that. Discovering why you get timeouts seems a lot more relevant than this workaround request.

Mostly because of problems with FSAC. Spends a lot of time waiting for typecheck results and formatting requests dont work in the meantime. For some files it gets into a bad state and subsequent calls to the LS fails. From output logs there are index overflow errors etc.. on some files. Fixing FSAC at this level is beyond my paygrade.

> And could you also explain to me why you specifically need stdin/stdout?
>What is preventing you from calling the command line tool inside your editor?

In this case you can only format the document after it writes to disk. stdin is useful while formatting the document in an unsaved state. For example elm-format has an stdin option. Gofmt & ocamlfmt you can pipe a piece of code into the binary.

**Comment by nojaf** [comment]
> Fixing FSAC at this level is beyond my paygrade.

This is a different discussion for sure, but I do encourage you to invest time in that area. Anyway, there is no relation between type-checking and formatting in FSAC, so whatever your problem is with type-checking, that is the itch you want to scratch.

I'm going to leave this issue open so that more voices can be heard, but as it stands today I didn't hear any compelling arguments why we should retain this.

Lastly, there is nothing preventing you from writing a script that more or less does what you are after.

```fsharp
#r "nuget: Fantomas.Core"

open Fantomas.Core

// from stdin ...
let code = "let a  =   0"

let formattedCode =
    CodeFormatter.FormatDocumentAsync(false, code)
    |> Async.RunSynchronously

// to stdout ...
```

**Comment by kaashyapan** [comment]
ok. Thanks for your response.

**Comment by kumkee** [comment]
I have a reason to keep those two options.
I am using neovim where we use [null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) configure the formatters and linters, for example here is how [csharpier is configured](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/lua/null-ls/builtins/formatting/csharpier.lua) where both stdin and stdout are required.

Please reopen this discussion and reconsider adding them back.

**Comment by arialdomartini** [comment]
I'm working to use Emacs as my editor for F#, and make it possible to format regions of code as described in https://zwild.github.io/posts/emacs-as-a-fsharp-ide-part1. The approach documented there does not work anymore because it used to rely on `--stdin`. 

Basically,

- it lets the user select a region.
- it passed it to Fantomas, as a string with `--stdin`.
- it gets back the formatted code.
- and finally it replaces the code in the buffer.

Of course, I can always think to some workarounds (either working on the whole file, or  transparently saving the region to a temporary file).

Never the less, having Fantomas able to directly process a string instead of a file would have its usage.
