### ISSUE TITLE
Stroustrup: Two lists given directly as parameters, break code

### ISSUE THREAD

**Issue by panmona** [fsprojects/fantomas#2681]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/main?data=N4KABGBEDGD2AmBTSAuKAZAhgT1gVwBcA6Agd1gGFYAbPAWwDstdCB1ASwIAsBlA7aogDOAHQYQIQ-oNHiJAbTETlYRILqIGBAIxhqsBgHMACpgBOmDQURmAcpcS6ADucsAmMC4t0AzEpUQaogaWrr6RqbeiNZ2Ds6udB5eln5yEAC6YP4QimkqQSE6egYmCdE29hrx3kkJqQGB6ppF4aVRMZWOngm13vUS6ZAANOBQQtEE7EZCqGDyoxCgAZAAJPxOyGiQUwTDCxKrAG6YtJtz%2B8oADCMNUACSDEhaPOwAXsg3DQAsF2Dp%2BwBfT6LX6rdZnbZaPbLFbHU6zea3bTAlSQACymAAHugpoh0JpDNxoQ1tG5Lr9-sogfslqi1tgNrNIJp4AB5ABmOIYiD4Ag%2BoNhJzwZ0RDTcKOUkAAoo8OVz%2BbdINR2ZAKYCUbTJfTGVsAEawGjErVw4UI34QHwSg4PcZmAgAMSmJ1siFI1FxRpUBDMwrVVI1AvBTP1hqtRyFIvNYC%2BVogkB4LmgiAAQoh2bAzIhIg4Yp7lN7fQFKRJqcpNQdtRCQ9Q81BBfC0KKAgBWWNQBOYJOp9OZ9CwUg2aCYcYPQ6wIeTAy1iAFxB%2BksBmFBvUGmth%2BumxtRgBsbfjiZTaYziAAqk4NmYhyOGGOJ%2Bwp232SdxvOIKWJOW45Xg6va%2BGG%2BctwAOx7h2XZHpmFDUMOQhUAwUg%2BtABAZtOYBPtQL5FuqNKBgyVa-uuJqRrcAAcoEHt2x5osEuo2Kh6GYSoxZvoudLLlA1Z-huxENAAnORnaHj2iBUOE9HPnOWH%2BjhS54T%2BoYCkRZpItcUb7oJACC7IxFQdB0JgqGzq%2BYDviCsk6hxBGKRGykksialgUJx48ME7BwGJj4ScZplgJ%2BdbsZAnGETZW5IuKDkHlpMQuXQbk0A%2BUZGVJC4yWxckrgpMJKaFJKWhFmlmPgjwACJqOwsW5m2SVMdhZa4RZkK7MFAFNio2gxmpGKYnc7IACpcJoPBcBmBAcPARJtuSyUsalWoBTsXHZYBJKtp1WI9f1mhShhPLDXaY0TTuU01dJdXmRCC3NZuy0BNou5rd1DDsuwmKshemDIWYUqYk4mZCEI94MKhJHHcozEmaxc3pVAl3WS1UbaCBD0AEqIHAZjwAdXCoV8oMDLVH71RdUJXTxt1kSjaMZvAtj0LRZgcnc1h0DMbbaN5kMVgFdB4NQkzuty9oZvpBAxL1cmk7Zt38WpqPo-AaK8-zuJC2YIuVWp0BcK4SE2AA%2BqQ7DjdjHOzVz0ONYtIU3SoZJ7l1GlmBY2CsmYOJSFjwN4xkBNmWlDWw1l1utcobj2YqDtOzgrvuwQtN0PTjPM6zCOm2d-sQjzfPsALiCq%2BrNji4yks5QEbjhYqjvOzH7BSIr2e5-nH0a4qWs6zEBtG0SaeE%2BdTKB3SS0hxIbh5RHWIAGoRsmUzwFMhie22IM937UMByTcPXcPEBuB14%2BYvaeAMEhgMz488%2BL1GuMr75RP9xvQfw7cbirfvxWwAQADi0Tfb9wgAwYS%2BpFvZ-F9rfPuGU1ybzJrbe6ioXRulxKmMgiBNBF0QKVZ6DBOCAw0o8aiCcbAp1uNVMGYC-JggtkFaBUtbZI0ru6QwDBD7H0nAwF4TCPp4EzL1WADwngEA%2BoDcSO0b4UO-JAq2T8xQUwYTEBgQjDh4hKAQ%2BmmCpg4IMMQhoDFJInRSunNe%2BFMqD2DlGNwMsI5K3YPKLACd4CYCgrAAGRgEG5xEYxMhp1e4Z3klAx%2BW8ow%2BFUoqX%2BNhyrNBOAAaVQU4fhzQHjJgsMfbGnlRHTQhmbL8AVqEBJgcoHw4cGiQGTNBBgABreUQhHZFRpsIawCtrG51-n9AB8FDI%2Bj0V4gxPijF%2BKkYE24PgK7FOTOYSimZiq12gGYcqToGknmwQYUq0BoIWDYR4rp%2BNvGr3Ng1LOytuRJM7OU6IvJBADPyRIHwY9in10OSmCw0BTkEHOQqYpiAfrhMKCcPWCF8AITwE4VUGSfLiPmg-Ux0iAg%2BD3sUmJiAnBdXjondkpTMAVKqahbQlwQHgzBXfSRJcbYFNfsUvgsykJogQO8gIujvKjHSJ8bYQh7QA1mPSgEQA)

#### Code

```fsharp
Layout.twoColumnLayoutWithStyles
    styles
    [
        element1 longParameterName1 param2 param3
        element1 longParameterName1 param2 param3
    ] 
    [
        element1 longParameterName1 param2 param3
        element1 longParameterName1 param2 param3
    ]
```
            

#### Result

```fsharp
Layout.twoColumnLayoutWithStyles
    styles[element1 longParameterName1 param2 param3
           element1 longParameterName1 param2 param3]
    [
        element1 longParameterName1 param2 param3
        element1 longParameterName1 param2 param3
    ]

```
            
#### Problem description
When the items in the first list are big enough, it should add line breaks. But a space is removed between the first parameter and the first list. This is unfortunately invalid code.

#### Extra information

- [x] The formatted result breaks my code.
- [ ] The formatted result gives compiler warnings.
- [ ] I or my company would be willing to help fix this.

#### Options

Fantomas main branch at 2023-01-04T10:51:25Z - 1eb5725b43c7cf54aa1ebe5503249948751d6483

```fsharp
    { config with
                MultilineBracketStyle = experimental_stroustrup }
```

<sub>Did you know that you can ignore files when formatting from fantomas-tool or the FAKE targets by using a [.fantomasignore file](https://fsprojects.github.io/fantomas/docs/end-users/IgnoreFiles.html)?</sub>

**Comment by nojaf** [comment]
Hello, thank you for raising this issue.

I took a quick look and this doesn't appear to be a regression due to project Dallas. ([Sample](https://fsprojects.github.io/fantomas-tools/#/fantomas/v5?data=N4KABGBEDGD2AmBTSAuKBDAdAFwO6wGFYAbAVwFsA7AGXQE9ZTsB1AS2wAsBlbO4xAM4AdShAgBtEWOlhE-cokrYAjGGKxKAcwAK6AE7oF2RHoByhxKoAO%2BwwCYwNg%2BQDMUmRDmIFS1eq26zojGZhbWtuQOToZuomIAumDuEskyXj4qaho6EcEm5grhzlERsR6e8oqZ-jlBIQWWjhElzmUJkAA04FACwdisWgKoYOLdEKAekAAkvFbIaJAD2J1jYtMAbuhk8yOr0gAMXeVQAJKUSEpcrABeyEflACx7YPGrAL7348-TszuLSitJlNNtthqNjspPjJIABZdAAD2oA0Q1EUmk4gPKyjs%2B2er2kH1WE2hMzoc2GkEU8AA8gAzJGURA8Ph3b7ArakHbg8p2KHSSAAUXOdIZrOOkGItMgePeUOJ-NJ5IWACNYCRMQqQZywc8IC4%2BWszr09NgAGIDLamRC4YjIjUybB6Tkyglytm-Cmq9UGjYcrm6sAPA0QSBcGzQRAAIUQtNgekQgQsIXt0kdzo8%2BLEhOk8rWir%2BXuIKag7NBaG5HgArMGoGH0BHo7H49RYLgTNB0L0zutYB3%2BhpixA04gXVm3UCPSq1UWfaXteWAwA2Guh8NRmNxxAAVSscz0Ha7lB7fdYA5rtK2vVHEGzYlzIfznunxd9Zd2xwA7Cu6w2N-GCMQnYCEQlACGm0DYHGg5gBexBXhmspEu6ZIFs%2Bs5av6xwABzfmujabjC3jKiY0GwfBMiZje44kpOUCFi%2Bc6YeUACcuH1uuTaIEQ-ikZeI4Ia6SETihT7emyGE6hChwBqu7EAIK0iERDkOQ6DQcO15gLeXzCUqdFoeJfqSVikIyT%2BHGblw3isHAPHnnxmnaWA94lrRkD0ehRkLhCvJmWuCkhFZ5A2SQZ4BhpAljkJNEiVOYlAhJ3lYvqfnyXojDnAAInIrDBcmNYRRRiE5shen-MsnlvhWMjKEGMlwvCJy0gAKhwihcBwcYsKw8AYjWuKRVR0UKm5SwMYl75YtW9UIk1rWKAKcFMp1JpsL1HDQYuA1FYJJW6X8Y2VfOk0eMoy4zY1lC0qw8LUnu6CQXoArwlY8YCAIp6UNBWHbdIlFadRI2xVAh2GVVAbKF%2BF0AEqIHAejwGtfUBg8v0JMVd6lQdAJHUxp04TDcNxvApgUMReh0icxjkEMNbKI5gN5m55CkMQ-S2oyppxqp2AhM1Im48Zp2sTJsPw-AMKs%2BzyJc3oPP5TJ0AcLYEEmAA%2BrgPUYgzw1M8D5XjV5J0yDiK4NXJegGHQ1J6EiYFIxtNY-Tre0xWVoMJUb1XSHYpniublv0DbdvYKT5Dk5T1O0xDLuY-tFIs2zrAc4gsvyyY-PkoLSUeHYvnihbVvB6wYGS0nKdpw9CvikrKshBrWsbbHOlu9jFVg8d3tiHYKX%2BwiABqfqRgM8ADJoDvfWjED-U5Lk-PrHskhNXcQHYdV9-CpqkJQEGfcP5xjxPNao83zlYxSi%2Bal7AZ2NNG%2BZbA2AAOLBM9r2CB9GhHwGzuDQDusPjch5DueMTbnX9lLZOyJIzqGgAAa0jAYeBwQBDUkoFwCw3EKBfQKk6fiO0oquyBmVYBntwbHDsFDcUVobTQOCG2RQmdEDZWupQdgn05LnEIuHEw0djiFT%2BhjFuxDULxSXtfChBMC62k0JQLeO9%2BzoNYLIh6pB4zNVgGcC42AHqfV4ktU%2Bc9HxxRnCAoWJsRbSJCJQXR6wUTZG4eTFhAx2EaD4eUMi%2BDBG7Tjq3USpiyGdwDC4aSECk6iloOHeA6AAKwA%2BloGhKd9HkW8YQ3xIj-GG3IeUFwftyiCheiYXKVQtgAGlECICsFoqoZxEHoB3o7AMnjDHnxMVkoJxwXD53yTA%2BpcDRQCAthlEmghjAS0gSnN%2Bb1P6gXUnglp8c2nZ2NtIFwvcen6HwvGTKJdoB6FyhaMZW42EaGytAQCBhFHJK8ejHxwi9YkIMoE0Bqz175LfkUjIWweDpVIGBJ0VhmT8DmemAhQ0iEPLbu0l5YgXB33yeUypDUw4R1pL0yg-TkTuNOvsKeLwhFn0WfpMRV9skeBcOA-JPybLYBhAgMUHiHJ-zeN0eI9xFgCFNB9YYzS3hAA))

I believe the problem will be around:
https://github.com/fsprojects/fantomas/blob/8f2dead05eef0a5c6ee6c3d259495dd834cf023f/src/Fantomas.Core/CodePrinter.fs#L1378-L1379

`onlyIfNot node.SequentialExpr.IsEmpty sepSpace` might be required between those lines.
Haven't tested this.

Are you interested in submitting a PR?

**Comment by josh-degraw** [comment]
I just applied that and while it fixes the invalid code problem, it brought up another question for me of how the elmish syntax is kind of tangential to stroustrup.

That change results in output like this:

```fsharp
Layout.twoColumnLayoutWithStyles styles [
    element1 longParameterName1 param2 param3
    element1 longParameterName1 param2 param3
] [
    element1 longParameterName1 param2 param3
    element1 longParameterName1 param2 param3
]
```

which matches elmish style, and _technically_ matches stroustrup alignment, but I think this would make sense to be handled in a separate configuration option (e.g. `elmish_list_style` or something), especially because I could see some people wanting to use elmish style for situations like this but would prefer to use Aligned or Cramped for other situations (inversely, I would personally prefer the way OP had the code originally even when I'd prefer stroustrup for most situations).

I can PR this change as is but I thought I'd bring it up for discussion if you're open to discussing it separately.

**Comment by nojaf** [comment]
> I can PR this change as is but I thought I'd bring it up for discussion if you're open to discussing it separately.

Thanks for the PR! I've had a similar thought on extracting this to its own setting.
We can discuss this separately.
