### ISSUE TITLE
rec keyword is removed from recursive modules

### ISSUE THREAD

**Issue by JonCanning** [fsprojects/fantomas#274]
`module rec Foo` becomes `module Foo`

**Comment by 7sharp9** [comment]
I confirm, this is due to the `isRec` element of the ast being ignored:
https://github.com/fsprojects/fantomas/blob/fb120ed9ec5761be23f076035beced25a81d58e9/src/Fantomas/SourceParser.fs#L270
_parameter to the right of `xs`

Which is then used here in the code writer:
https://github.com/fsprojects/fantomas/blob/479b8ed73f0967d25ccbe36b51bc80977e513326/src/Fantomas/CodePrinter.fs#L180

**Comment by 7sharp9** [comment]
I got this one, PR incoming...
