### ISSUE TITLE
Fluent API with comments breaks code

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/fantomas#331]
This code (taken from the `Program.fs` file in the Server project of https://github.com/Zaid-Ajaj/tabula-rasa)

```fsharp
Log.Logger <- 
  LoggerConfiguration() 
    // Suave.SerilogExtensions has native destructuring mechanism
    // this helps Serilog deserialize the fsharp types like unions/records
    .Destructure.FSharpTypes()
    // use package Serilog.Sinks.Console  
    // https://github.com/serilog/serilog-sinks-console
    .WriteTo.Console() 
    // add more sinks etc.
    .CreateLogger()
```

gets rewritten as:

```fsharp
Log.Logger <- LoggerConfiguration().// Suave.SerilogExtensions has native destructuring mechanism
                                    // this helps Serilog deserialize the fsharp types like unions/records
                                    Destructure.FSharpTypes().// use package Serilog.Sinks.Console  
                                                              // https://github.com/serilog/serilog-sinks-console
                                                              WriteTo.Console().// add more sinks etc.
                                                                                CreateLogger()
```

which is actually invalid F# and does not build.

Using standard fantomas settings with 120 char line length.

In fact, fluent APIs in general don't get very well formatted e.g.:

```fsharp
Log.Logger <-
    LoggerConfiguration()
        .Destructure.FSharpTypes()
        .WriteTo.Console()
        .CreateLogger()
```

becomes

```fsharp
Log.Logger <- LoggerConfiguration().Destructure.FSharpTypes().WriteTo.Console().CreateLogger()
```

Although this is more aesthetic.

**Comment by nojaf** [comment]
Fixed in 2.9.1, [see online](http://ratatosk.dynu.net/fantomas/#?code=DIew5gdKZgpgTgAgDwFpEFgBQjHTvAMIgB2AZgJZgCu8AhgC4WkAUAlJjrogPQ+IBlanQBusCAIQUANuACiADwawSAZ2ZrEACzqrEJRhTGIAJrFUN41AMYNaFEmEQBbWNZ0kKq59m69+DFpe2rDSAA56kvAy4KbmUnTSFABesIiBaWSqOvBh6QCeYeaISQDWadSepKo88G4g8CaqvtwQACLmljZ2dRAAYgI5YQAqhebsLbh8iNSqaWF01qV0cIJSspACDqWqEMRqINJpnH7TWgwMEQBcfGAUgdQARhDWIM48c9EbH+vgqOokHaoV4HI6TRAQADq0WUwxAe2qh1g7BO3GmdBMJhcDTSAJ2iFgDGsEHBezqjFg+AQ7CAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA).
