### ISSUE TITLE
`in` is removed from binding when PreserveEndOfLine is true

### ISSUE THREAD

**Issue by auduchinok** [fsprojects/fantomas#340]
```fsharp
let x = 123 in ()
```

is being formatted to

```fsharp
let x = 123()
```

**Comment by nojaf** [comment]
Related:

```fsharp
let f () = 
  let x = 1 in   // the "in" keyword is available in F#
    let y = 2 in 
      x + y
```
gets formatted to

```fsharp
let f() =
    let x = 1
     // the "in" keyword is available in F#
     let y = 2
    x + y
```

Code is still valid, but the `in` keyword is lost.

**Comment by jindraivanek** [comment]
@nojaf I think removing `in` on EOL is fine because it is just unnecessary.

However this snippet shows other bug(s) related to comment 

* bad indent of line `let y = 2` - leads to invalid code
* comment on EOL moved to separate line

[with comment](
http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAZhAUCUEC8ECwAoCFSQB7IgEYIBLAOywgHoqIwALECAInOYgGsQBPAdwHsATgBNSAZwgBDAG6SSwSQCNQpCgDEAxBkrZwEbgQBMqtJh0R8Aan1A&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA)

[without comment](http://ratatosk.dynu.net/fantomas/#?code=DYUwLgBAZhAUCUEC8ECwAoCFSQB7IgEYIBLAOwyyxwgE8CAmUstTKrfAajqA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA)

**Comment by nojaf** [comment]
Ok, good to know that the comment caused the bad indent.

**Comment by uncleyo** [comment]
This doesn't seem to be fixed. At least for me `in` is being removed by `2.9.2.0`.
Sometimes that `in` can indeed be omitted, other times it is actually required.
For example, given original
```fsharp
let x = List.singleton <|
        let item = "text" in
        item
```
if it is processed with `--preserveEOL`, it will strip `in`, but the code is at least still valid:
```fsharp
let x = List.singleton <|
        let item = "text"
        item
```
however, without preserve the output is invalid F# (and subsequent `fantomas` runs will throw when parsing):
```fsharp
let x =
    List.singleton <| let item = "text"
                      item
```
The compiler error is `FS0010	Unexpected identifier in expression. Expected 'in' or other token.`
