### ISSUE TITLE
Wrongly removed "with" for member on record, PreserveEndOfLine=true

### ISSUE THREAD

**Issue by jindraivanek** [fsprojects/fantomas#388]
Issue created from [fantomas-ui](http://ratatosk.dynu.net/fantomas/#?code=C4TwDgpgBASlC8UDeBYAUFTUAaUBcUAlgHbDpZQC+UA7ocABblYDOwAhsIQMZQC2EPgCMIAJygARCADN2AVwA2wBMmzwADJSA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwi8XjhjlEMPA3QB7ADZ6IAQXiSoshUqIzUBoZrSYAQjBl7+J3tXxx4KmoaICgYMG4e-ADChsaB6k5hJjLwwjF4eKjxwaGYyam8Wjr6RhDZ5JCwCFIQACq8AJ6MrLb2jiAASjCesLxSyHAAIjDoBqi8qPAMcYR2DjnOMN56ONDDBgw6BeUhqrrwALJ6sK3zAL5AA)

Formatted code gives error: Unexpected keyword 'static' in implementation file

#### Code

```fsharp
type R = {
    X : int
    } with
    static member Default = {X=0}
```
            

#### Error

```fsharp
type R = {
    X : int
    }
    static member Default = { X = 0 }

```
            
#### Options

Fantomas 2.9.1

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `80` |
| `PreserveEndOfLine` | `true` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `true` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `ReorderOpenDeclaration` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Not an issue anymore due to removal of PreserveEndOfLine in #434.
https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=C4TwDgpgBASlC8UDeBYAUFTUAaUBcUAlgHbDpZQC+UA7ocABblYDOwAhsIQMZQC2EPgCMIAJygARCADN2AVwA2wBMmzwADJSA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsYBQSEOYTAmMvDCMXh4qPHBoU6p6bzaugZGELmJkLAIUhAAKrwAnoysthqJAEowHrC8UshwACIw6GqovKjwDHGEqh35mF76ONAjagy6RZVagXrwALL6sO1CAL5AA
