### ISSUE TITLE
Exception handling 'with' clause using drop-through is malformed

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#465]
### Description

Code like this
```
  let internal ImageLoadResilient (f: unit -> 'a) (tidy: unit -> 'a) =
    try
      f()
    with
    | :? BadImageFormatException
    | :? ArgumentException
    | :? IOException -> tidy()
```
becomes malformed
```
let internal ImageLoadResilient (f: unit -> 'a) (tidy: unit -> 'a) =
    try
        f()
    with :? BadImageFormatException
    | :? ArgumentException
    | :? IOException -> tidy()
```

### Repro code

[Here at v2.9.2](https://jindraivanek.gitlab.io/fantomas-ui/#?code=ATA2FMBdgSwO0uATnAhqYBJAtqg5uADID2qAJgErgDOMoM4CwAFAGYBcwArnDNALQA+YAHJUAShaQYZAJ6cefYENETgAXgCwAKBAhISWTr17Wzccb0B3PgAtLIAD7B2AfmAAhcjnzgAYsRIuJAAogAeAMbgAA7SxHAOwM5uwACCSHhc2IyhkTFxCbp6ye6YAPLhUbEw8crC0nLmOkA)

Also happens at the 2.9.3 preview; the 3.0.0 level preview of the tool simply faults.

**Comment by jindraivanek** [comment]
3.0.0 tool fault was caused by unrelated issue on tool side (incompatible version of FSharp.Compiler.Service and FSharp.Core), it is fixed now. [3.0.0 repro](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=ATA2FMBdgSwO0uATnAhqYBJAtqg5uADID2qAJgErgDOMoM4CwAFAGYBcwArnDNALQA+YAHJUAShaQYZAJ6cefYENETgAXgCwAKBAhISWTr17Wzccb0B3PgAtLIAD7B2AfmAAhcjnzgAYsRIuJAAogAeAMbgAA7SxHAOwM5uwACCSHhc2IyhkTFxCbp6ye6YAPLhUbEw8crC0nLmOkA)

**Comment by nojaf** [comment]
Should be ok now.
