### ISSUE TITLE
Poor formatting of elmish-inspired application code

### ISSUE THREAD

**Issue by MattKunze** [fsprojects/fantomas#470]
### Description

This is maybe more of a discussion item since I'm pretty new to the ecosystem, but I've found that using fantomas to format `view` functions that render a UI (elmish, Fabulous, Feliz, etc) almost always tends to result in a layout that is "worse" than the original hand-coded version.

The "Preserve EOL" option avoids this to some extent, but in my opinion that disables most of the benefit of the formatter in the first place.

### Repro code

For instance here is a simple example of some [example Fabulous code](https://jindraivanek.gitlab.io/fantomas-ui/#?code=AQ4GwUwF2A3BLCB3YAKAtgewCYTALmAFkc8BKYbeAZwAcBDKAYwAtgBeAKFB+ADVESAHQBhTADsoESQAV6AcwipuvVfVq0I9AE7xx89qgBmAV3FoKAWgB8lGg2Zs5igIIatu-WQA0K1Tyh4KEh2LFwwIRkwenFoIQBJcSNMIQA5enQIX39eACN6JgBreW1MM2wxMExtdkrqoQAhaKLsnNAmCSlJdgFkIQBxXWxlNv9WeDBsbWl2AG0-Uf9e4QBVbRZMAGUTbSMCiAAeKJjoAWoTejB4AC8IbTWNt1prEcW3gH5MWkCJakN0RisYBhPBCAAS9GoTw8EGwwCQQTYezA1AgwBswFSEjRAB9gFBtCY0RjNphMmhlkIHpgnlcmIx4BIAPLfRniaioSGoqDUABimEmd3YACIACKMejCsjS1pvUZMaaMWGGalPESKqRw6y2Kh0QEsMgLOWgQ3G1SUzZQAqFAAy9AAnmUoK8zf4GNgqPp2AAmAAMQllrt4eloJigABVtDE9dNugSiYGg+0WBMpjN5knRuhColknbcnhgGL4BloHdhWhCuhw1sCXp5MDSBFjrEoAkkilRSXMlJtKbMzls7nMPnC8LwxB0Joo1AdhAK6gmHhqPATNQa5bPA2Qc3oq328khBOp3dGHP+wPVEOO6OwEXNppYQu6BBYRu6-pG+FInu4sOhA+r7YBel48Neeb0AWd7CkQXILgC1DrrWW5fqCLZ-h2QiwYhIGgSA4EjpBY4AJoeMAmBGMAXbUB0sB3PaC56FALI-OI74ocKqQAPQuBWO4-icbb-qROhMkY1G0fRuF4ZSt6oFIAAeUChE2An7v+ooQDRuishI3jABsujXJ0lwTkpLhXPI4iZN0ZlQBZ8BWTZbYiNIvb6XR2iBPSYAsWyfx2o6YZ+b8Qi8hMYAuOI2AAKIKQw0UeXc3mmRA5mWdZbnsHZDlOW5QgxdFZBCAA6imUh2ag0lJgAukaZrVW0dVvI1ZBAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsa2GiEOYTAmMvDCMXh4qAFBiY6Yqem82roGRhC5weSQsAhSEAAqvACejKzx9gBKMB6wvFLIcAAiMOhqqLyo8AxxhKoJoU5e+jjQo2oMusVViQDSMDDIWDAA7ptKRcKd+YF68ACy+rA3AL5AA) from https://github.com/TimLariviere/FabulousPlanets/blob/master/FabulousPlanets/CardPage.fs that is pretty representative of the issues I've experienced.

![image](https://user-images.githubusercontent.com/421270/63721119-d9758b00-c80d-11e9-8b1c-d3d9221288b6.png)

It's seems like the formatting rules favor lining up statements without considering the size of nested arguments which essentially paints it into a corner where subsequent statements are shifted very far to the right and have to be broken apart into multiple lines. If the "weight" of nested items could just force a break with a single indent earlier then the end result would be much nicer.

The original code can certainly be reworked to have less nesting, but when I see that a very large percentage of the sample code provided by similarly inspired libraries isn't handled particularly well I wonder if there aren't a few tweaks to the formatter that could handle this better.

**Comment by jindraivanek** [comment]
Can confirm its not nice also in [newest version](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=AQ4GwUwF2A3BLCB3YAKAtgewCYTALmAFkc8BKYbeAZwAcBDKAYwAtgBeAKFB+ADVESAHQBhTADsoESQAV6AcwipuvVfVq0I9AE7xx89qgBmAV3FoKAWgB8lGg2Zs5igIIatu-WQA0K1Tyh4KEh2LFwwIRkwenFoIQBJcSNMIQA5enQIX39eACN6JgBreW1MM2wxMExtdkrqoQAhaKLsnNAmCSlJdgFkIQBxXWxlNv9WeDBsbWl2AG0-Uf9e4QBVbRZMAGUTbSMCiAAeKJjoAWoTejB4AC8IbTWNt1prEcW3gH5MWkCJakN0RisYBhPBCAAS9GoTw8EGwwCQQTYezA1AgwBswFSEjRAB9gFBtCY0RjNphMmhlkIHpgnlcmIx4BIAPLfRniaioSGoqDUABimEmd3YACIACKMejCsjS1pvUZMaaMWGGalPESKqRw6y2Kh0QEsMgLOWgQ3G1SUzZQAqFAAy9AAnmUoK8zf4GNgqPp2AAmAAMQllrt4eloJigABVtDE9dNugSiYGg+0WBMpjN5knRuhColknbcnhgGL4BloHdhWhCuhw1sCXp5MDSBFjrEoAkkilRSXMlJtKbMzls7nMPnC8LwxB0Joo1AdhAK6gmHhqPATNQa5bPA2Qc3oq328khBOp3dGHP+wPVEOO6OwEXNppYQu6BBYRu6-pG+FInu4sOhA+r7YBel48Neeb0AWd7CkQXILgC1DrrWW5fqCLZ-h2QiwYhIGgSA4EjpBY4AJoeMAmBGMAXbUB0sB3PaC56FALI-OI74ocKqQAPQuBWO4-icbb-qROhMkY1G0fRuF4ZSt6oFIAAeUChE2An7v+ooQDRuishI3jABsujXJ0lwTkpLhXPI4iZN0ZlQBZ8BWTZbYiNIvb6XR2iBPSYAsWyfx2o6YZ+b8Qi8hMYAuOI2AAKIKQw0UeXc3mmRA5mWdZbnsHZDlOW5QgxdFZBCAA6imUh2ag0lJgAukaZrVW0dVvI1ZBAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZEAcADORQE4wBnGLwBuMAKLQA8gDMAMgwgwiM1ABsh5RDDwN0AezX6IAQXiSoshUpXrNIFBhgAhGDP38Tvavjjwi8Lw4MFpomK7u-ADChsa2GiEOYTAmMvDCMXh4qAFBiY6Yqem82roGRhC5weSQsAhSEAAqvACejKzx9gBKMB6wvFLIcAAiMOhqqLyo8AxxhKoJoU5e+jjQo2oMusVViQDSMDDIWDAA7ptKRcKd+YF68ACy+rA3AL5AA).

We should extend technique from #419 also for named parameters.

**Comment by reaysawa** [comment]
I disagree with Fantomas' version being "worse". Preserving screen space is more important in my opinion and it's much better when one can read everything as streamlinedly as possible (also for preventing the need of scrolling the screen sideways in order to be able to read everything).

Indenting one level further in the the next line is enough of a nesting indicator. You actually don't need to push everything to after where the statement ended (I think we can refer to the [piping operator indentation](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview-trivia&code=LYQwLgxgFgBMCeA1EAnAliARgGwKYwHc0woBYAKAB8YBvGAMTV2wBMYBeGARhgF8YAtAD4YIRLhTwAMqgDmuegFcAdhDBoA9soBCGlvADqxKFI1gAzgHkAZgGE9uAJLLzaFrgrU6jZm04AmPkERc1BsbCVlT1oGJlYOGABmIOFRcUkZFHlItU0dPUNjUwsbe3dnV3cgA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXACwA0IACqgOYwDqAllPABZHEAM5FATjAM4weANxgBRaAHkAZgBkGEGEWmoANoPKIYeBugD2qvRACC8CVBnzFytRpAoMMAEIxpevsZ7V8ceEXg8ODCaaJgubnwAwgZGNurB9qEwxtLwQtF4eKj+gQkOmClpPFo6+oYQOUHkkLAIkhAAKjwAnoyscXYASjDusDySyHAAIjDoqqg8qPAMsYQq8SGOnno40COqDDpFlQkA0jAwyFgwAO4bioVCHXkBuvAAsnqw1wC+QA) tip from the style guide as a pointer to this situation).

If such a tweak to serve hand-formatted code is applied, please make it optional so that users can opt out of it. Thank you in advance!

**Comment by nojaf** [comment]
Fantomas should now push multi-line constructs after `=` to the next line.
