### ISSUE TITLE
Formatting removes "with" from type declaration which makes code not compile

### ISSUE THREAD

**Issue by isaevdan** [fsprojects/fantomas#547]
Formatting removes with from type declaration which makes code not compile

#### Code

```fsharp
type Range = {
    From: float
    To: float
}
with
    member this.Length =
            this.To - this.From
```
            

#### Result

```fsharp
type Range =
    { From: float
      To: float }
    member this.Length = this.To - this.From

```
            
#### Options

Fantomas 3.0.0

| Name | Value |
| ---- | ----- |
| `IndentOnTryWith` | `false` |
| `IndentSpaceNum` | `4` |
| `KeepNewlineAfter` | `false` |
| `PageWidth` | `120` |
| `ReorderOpenDeclaration` | `false` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceAfterSemicolon` | `true` |
| `SpaceAroundDelimiter` | `true` |
| `SpaceBeforeArgument` | `true` |
| `SpaceBeforeColon` | `false` |
| `StrictMode` | `false` |

**Comment by knocte** [comment]
I think I've found another instance of this bug. This code:

```
type IBlockchainFeeInfo =
    abstract member FeeEstimationTime: DateTime with get
    abstract member FeeValue: decimal with get
    abstract member Currency: Currency with get
```

gets formatted to this:

```
type IBlockchainFeeInfo =
    abstract FeeEstimationTime: DateTime
    abstract FeeValue: decimal
    abstract Currency: Currency
```

**Comment by isaevdan** [comment]
@nojaf is anyone looking into this? This seems pretty important

**Comment by nojaf** [comment]
Hello @isaevdan, this is not on my radar to be frank.
There is a lot of work in this project and there are [not that many contributors unfortunately](https://github.com/fsprojects/fantomas/graphs/contributors?from=2019-12-31&to=2020-03-30&type=c).

If you'd like to see a fix for this I propose you try and solve this yourself.
We have a [contribution guide](https://github.com/fsprojects/fantomas#contributing-guide) and some videos that explain [how Fantomas works.](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K)

I know this is probably not the answer you were looking for. And if you want to take a stab at this, I'd be happy to help you out along the way.

**Comment by isaevdan** [comment]
Hello @nojaf,
Fair enough
Luckily I`m currently working on my compiler for language similar to expressions in Excel, and it is interesting to look into how different tools work with AST. 
I created pull request here https://github.com/fsprojects/fantomas/pull/738
This is first time I`m contributing to open source project, so any feedback is appreciated.

**Comment by nojaf** [comment]
Thanks for the positive reaction @isaevdan!

> This is first time I'm contributing to open source project, so any feedback is appreciated.

There is a first time for everything, and being aware of this is a good reflex.
Some general advice:
Follow any contribution guides and ask questions when you are in doubt.
A maintainer should be comfortable with the change you propose as they will end up maintaining it.
So in that regard it is best to have a constructive conversation instead of changing a bunch of code and having one-side expectations.

Regarding your PR: you broke existing tests and the behavior you introduced changes the way existing code was formatted.
In that case you have two options: 
* Update the existing tests to the new behavior (always have the `with`)
* Add additional logic so the `with` is only printed when needed.

@jindraivanek any idea when the `with` keyword is absolutely required for the compiler?
I noticed that the wrong output of Fantomas is still [valid Untyped AST](https://jindraivanek.gitlab.io/ast-viewer/#?code=C4TwDgpgBASghgOwObQLwFgBQUdQN5QBiATgPYC2AXFAGYA2pcwWuuAKqdfY8FAL4tc5COQBGEYlGAALAJYBnAHQAZCMhlRUUuUo5QAtNoWKSFIA&defines=Q&filename=MoYwTglgDgLgdAMwM4A8g).

I would like to have a better understanding when `with` is exactly needed.
[The F# style guide ](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-record-declarations) seems to both have it and not have it.
So is it purely optional or not?

**Comment by isaevdan** [comment]
@nojaf 

> Regarding your PR: you broke existing tests and the behavior you introduced changes the way existing code was formatted.

Just found it as well. I already updated PR to only insert 'with' when needed. But there is still one test failing with code like this:

`type Route =
    { Verb: string
      Path: string
      Handler: Map<string, string> -> HttpListenerContext -> string }
    override x.ToString() = sprintf "%s %s" x.Verb x.Path`

I`m going to research when 'with' is needed and when is optional. From this test case I see there is special case for overrides, but maybe there are others. If you want to remove it when it is optional, I probably need to figure out what kind of members are in the type before calling `genMemberDefnList `

**Comment by cartermp** [comment]
@isaevdan note that on .NET Core 3.1 this program runs:

```fsharp
type Route =
    { Verb: string
      Path: string
      Handler: Map<string, string> -> string }
    override x.ToString() = sprintf "%s %s" x.Verb x.Path 

[<EntryPoint>]
let main argv =
    let handler = fun (m: Map<string, string>) -> m.["hello"]
    let verb = "derp"
    let path = "herp"

    printfn "%O"  { Verb = verb; Path = path; Handler = handler} // prints "derp herp"
```

So the `with` shouldn't be needed. The style guide `with` isn't needed, looks like a small docs bug

**Comment by isaevdan** [comment]
@cartermp Yes, in comment above I meant that this code snippet works correctly. So additional investigation is needed to figure out when 'with' is mandatory and when is optional

**Comment by jindraivanek** [comment]
Specs say this: "The with/endtokens can be omitted ifthe type-defn-elementsvertically align with the { in the record-fields." (https://fsharp.org/specs/language-spec/4.1/FSharpSpec-4.1-latest.pdf#page=134&zoom=auto,-116,385)

So, this is correct:
```
type Range =
    { From: float
      To: float }
    member this.Length = this.To - this.From
```
This is not correct:
```
type Range = {
      From: float
      To: float }
    member this.Length = this.To - this.From
```

I believe that Fantomas emit correct code (without `with`) now, but combination with #706 (that allow `type Range = {` style) can be tricky.

Use `with` always would avoid such problems.

Note that similar situation is with DU types.

**Comment by isaevdan** [comment]
@jindraivanek I just retested my case from this bug, and looks like you are right and my initial bug is not relevant. Probably I added new lines after formatting with fantomas and updated it to `type Range = {` style and that is why code didn`t compile. 
Do you suggest to add `with` always now to support https://github.com/fsprojects/fantomas/pull/706 ?

In this case I just need to update failing tests

**Comment by knocte** [comment]
IMO, if #706 is not merged yet, and your initial testcase is already working with current master branch, you should just add a test that covers your testcase, in your PR (not modifying implementation, just adding the test). This way, the PR706 won't be able to get merged until it doesn't cause regressions.

NB: @isaevdan maybe a similar fix to the one you were cooking, is the one that is needed by the issue https://github.com/fsprojects/fantomas/issues/733 (which I opened after making my testcase in https://github.com/fsprojects/fantomas/issues/547#issuecomment-550230647 be smaller).

**Comment by jindraivanek** [comment]
@isaevdan 

> Do you suggest to add `with` always now to support #706 ?

I agree, I think it is the only consistent solution. (Switching use of `with` on/off based on other style choices seems weird).

Also, I think we should do the same for DUs.

What do you think, @nojaf ?

**Comment by nojaf** [comment]
#706 would not format the type that way:
Instead of 
```fsharp
type Range = {
      From: float
      To: float }
    member this.Length = this.To - this.From
```

it would be 
```fsharp
type Range =
    {
        From: float
        To: float
    }

    member this.Length = this.To - this.From
```

So I don't think we need to take this into account just yet.
I would go for a solution without `with` actually since that is how G-Research wants it in #706 and how it is formatted today.

Going back to the original issue: is this still a bug?

I'm a bit puzzled whether something needs to be solved in the first place. Or am I missing something here?
I'm able to execute the formatted code (today) in FSI:
![image](https://user-images.githubusercontent.com/2621499/78036230-58b1db00-736a-11ea-8d9d-7340d457347f.png)

**Comment by isaevdan** [comment]
@nojaf orginal issue is not a bug. I`ve tested it as well and stated here https://github.com/fsprojects/fantomas/issues/547#issuecomment-606469785 that this is not a bug. Other suggestions were more relevant to https://github.com/fsprojects/fantomas/pull/706. I will close current issue to make it clear. I wanted to know if I should do anything with my PR (if it is needed for https://github.com/fsprojects/fantomas/pull/706). If no, I can just cancel it

**Comment by nojaf** [comment]
Hey @isaevdan , sorry I overlooked over that comment. The title of this issue contained `which makes code not compile`, so I was always under the impression that we actually had a bug here. Glad we don't.

I propose you close the PR as no changes are required here. As for #706, the goal is to also have it without the `with` keyword. I'll add a test later this week to verify that.
