### ISSUE TITLE
No way or no documentation on how to disable the `default = true` command-line options

### ISSUE THREAD

**Issue by knocte** [fsprojects/fantomas#549]
### Description

The command-line flags that default to true, such as 	`--noSpaceBeforeArgument`, `--noSpaceAfterComma`, `--noSpaceAfterSemiColon`, `--noSpaceAroundDelimiter`, don't seem to accept a "false" string as a second argument, either by `--fooBar=false` or `--fooBar false`.

So it's not clear how they can be disabled.

**Comment by knocte** [comment]
@nojaf @jindraivanek would it be acceptable to fix this with a PR that inverts the options? e.g. change `--noSpaceBeforeArgument` to `--spaceBeforeArgument`?

**Comment by jindraivanek** [comment]
These flags are parameter-less and they set accompanying config option (with default=true) to false.

I agree that help text is confusing and should be changed. Maybe just remove `(default = ...)` part for bool config options?

**Comment by knocte** [comment]
I'm not sure I understand your comment, are you saying that using `--noSpaceBeforeArgument` should do the opposite as what the default is? I just tested this and seems to not be the case (that is, there's no difference in the formatting if I use the flag or if I don't use it).

**Comment by knocte** [comment]
i.e. fantomas is changing my code this way regardless if I use `--noSpaceBeforeArgument`:

```
-        foo.Bar ()
+        foo.Bar()
```

**Comment by jindraivanek** [comment]
Hmm, maybe `SpaceBeforeArgument` is broken, I also wasn't able to construct example where output differ based on its setting. We have no tests for this.

But you can try it with another options, like [this](https://jindraivanek.gitlab.io/fantomas-ui/#?code=NoRg3ATGDMC6CwAoIA), try to turn off `SpaceAfterSemicolon`. `--noSpaceAfterSemicolon` in CLI should behave same.

**Comment by VelocityRa** [comment]
I see now - the option operates on arguments in function _declarations_, but not function calls as you expected it to.

Perhaps a new option should be added, that operates on function calls? I can do that.
Because in #550 I made `SpaceBeforeArgument` operate on calls too which broke tests, since their declarations have spaces and the calls don't.

So project maintainers, which of the following should I do:
1) Make a `SpaceBeforeFunctionCall` and set it to `false` by default, or
2) Make the current option (`SpaceBeforeArgument`) operate on function calls too, decide on a default value (probably `true`) and tweak the tests accordingly

The most robust approach would be 1. of course, but it's up to you.

**Comment by nojaf** [comment]
I'm not entirely convinced that we need any code changes here, to be honest.
@knocte was confused about how the cli settings work.

An example was given where it was assumed that `SpaceBeforeArgument` had an impact where it didn't. Fantomas has always worked this way and @VelocityRa made a PR a bit to early.

I'm open for discussion on spaces after function calls but it needs to be fleshed out properly and I would like to see some interest from other people as well. Please make your case in another issue.

Let's keep this issue to talk about the cli settings. @knocte do you need any further assistance?

**Comment by knocte** [comment]
Thanks for all your insights everyone.

Let me reply one by one:

> on arguments in function declarations, but not function calls as you expected it to.

Oh I see, so I was interpreting the flag wrongly. IMO the flag should also allow adding a space in invokations, but yes let's rather discuss that separate topic in #552 to not mix things and make @nohaf happy :) (and thanks for opening that issue @VelocityRa )

> do you need any further assistance?

Well, after trying again `--noSpaceBeforeArgument` with this new intel, seems it still doesn't work!

I have this code:

```
let ShowSaneDate (date: DateTime): string =
    date.ToString("dd-MMM-yyyy")
```

If I run fantomas with `fantomas . --recurse`, I get:

```
let ShowSaneDate(date: DateTime): string = date.ToString("dd-MMM-yyyy")
```

And if I run it with `fantomas . --recurse --noSpaceBeforeArgument` I get exactly the same! I thought it was supposed to generate this instead:

```
let ShowSaneDate (date: DateTime): string = date.ToString("dd-MMM-yyyy")
```

What am I missing?

**Comment by nojaf** [comment]
`SpaceBeforeArgument` seems to only be doing anything in very specific situations.

See https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYFgBQWA2YlQIAWwA7jAIYRgAiFKUAFACb1gBcUdKAKgJaowASk7IATnwgBzKAF4sURVFYoAdD2AwkE6YwBEzZgFoAsmaNxLcPUIVLc+WCXJVabAKohwYpio5c2fkERQm1JGXlMJWU2dU0w3QNjMxMLKxssBwIQHSQTMCImITkoHMkkADNoPUEiPUzMGGdKam4wT29GNqCwVQA5MltMAB8APig+KQhgMTA7RSxiMha3FC7AgV6B0iGxiamZuexMMog8gqKgA

Only `showSaneDate` is formatted differently because it has a lowercase `s`.

When the argument is a single unit `()` no spaces are added either. See `printMeh`

**Comment by knocte** [comment]
Thanks, it seems then we need to fix that inconsistency right? I'll open a new issue with that testcase cause there's so much noise in here now.
