### ISSUE TITLE
Invoking a file to format with --stdout throws exception

### ISSUE THREAD

**Issue by martinbryant** [fsprojects/fantomas#613]
### Description

**Actual behaviour**

When invoking the command using a file containing the code [here](https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYChSSgGQJYBGATgIZFzroDaAPAKIRLkAKwejAfALqW-oA2YJFFQl2UMgHMAblAC86KEqggi7JADNoAIgByeAMZgoB4KlEQAJgFp+7Y1ICuqSEgQBCKAAkwRMAHIEKAB3AAsSYQApGAB5XQA6XToAFShwoKRgKAQSOAkCYEdhJFC0AC5tCSIZRWUAHw4oAEEiUjh40RAoSSFIhGAIXV7+6Abm1tz4vBQiKAAKVXUtKG0AUgRtAEooWqUABigAekOoPyRHImgSaHUwHtmwAA9pk2BLMCA&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWCAvkA) with the --stdout flag on the command line the following exception is thrown - using v3.1.0

![image](https://user-images.githubusercontent.com/25330805/71522574-39b03280-28bd-11ea-902c-6177ccc08bf4.png)

**Expected behaviour**

The formatted code should be displayed. Works ok on v2.9.2

**Comment by nojaf** [comment]
I don't think this problem is related to `--stdout` flag but more to the filename `Program.fs`.
Using the online tool (with the same filename) I get the same error.

[Example](https://jindraivanek.gitlab.io/fantomas-ui/#?code=PYBwpgdgBAygngZwC5gLYChSSgGQJYBGATgIZFzroDaAPAKIRLkAKwejAfALqW-oA2YJFFQl2UMgHMAblAC86KEqggi7JADNoAIgByeAMZgoB4KlEQAJgFp+7Y1ICuqSEgQBCKAAkwRMAHIEKAB3AAsSYQApGAB5XQA6XToAFShwoKRgKAQSOAkCYEdhJFC0AC5tCSIZRWUAHw4oAEEiUjh40RAoSSFIhGAIXV7+6Abm1tz4vBQiKAAKVXUtKG0AUgRtAEooWqUABigAekOoPyRHImgSaHUwHtmwAA9pk2BLMCA&config=N4IgygDghgxgpgQQGYBc4CcDCB7AtrqEALiSgBsBnOAGnGnmTXTDlwEsZszsA7Y0yjTqxE6bAFceAEwAicMm3ZN+5KrUgiAQnCTZ0ogObjccHihWCAvkA&filename=AoJw9g5iCGC2B0AzAzkA)

![image](https://user-images.githubusercontent.com/2621499/71713123-a4ef8c80-2e08-11ea-8f6f-ca04984449c3.png)

Adding a namespace or module as the error mentions resolves the problem.
And when I rename the file to Program.fsx the file formats correctly using `--stout`.

![image](https://user-images.githubusercontent.com/2621499/71713273-51317300-2e09-11ea-9156-ec09c2be7c28.png)
