### ISSUE TITLE
Line comment displaced from commented #-directive

### ISSUE THREAD

**Issue by SteveGilham** [fsprojects/fantomas#638]
### Description

A comment about the next line in the original is pushed several lines down the source file

### Repro code

https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=PTAEGcGMCcEsAcAupoFMA2BDRsBurR5sALcURAe3OIIFkKA7CgOgGFVJZ1RMGATUPSbMA8kliMymcOFQBbAEbpYqcAFgAUAGIAkqABEzZsCKQA1pgDmq4EJbtO6ZgAZmARldvgyhcAapEABZnfU1dAyMTTHMrGztRcUlmAGVYS38+F2YAJmYAZm9YX38ggFZQ7WgDeIcuCq0q-RqOLmYABT4FfVAQUAAJTHxyKngAV2REGlBmPnRuRlBYADNBRnsWpw6FRal0cBG0WQZEMMb4sRxJCs0KeFQGUGSAT3BEeRu7h+fX+TYKOY4lwY4GYAHF7qg4JAPvdHi83nJmDoRDCvvDfgAlVBLdCAiQMVGCWAwCj7JaIZgAMWSxEw0HgzAAKqgAB4nDS3WHNRyE7mtLa8tYJIHqDSaXqsChyOS8ATKfw8aCWUZye7IIjQcCwBiWQhoTCKXGgAC0prN5otlqtFs0uOQAAoAIQAagAlKB7bcgaAAFwQRBwHWgABU-sDutD9te4ZNAD5QKMGLBEK73Z7EsDfaALvjkgF3QBeTSgUB2vUUSiIJ53AA0oBo6Hgdei3oLoC9+OL7YzIIAgnw+Pb4NAKxXq6g6w2m6B-AB3OE-RG9yBAgA80e1llj9pb+NTQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A

**Comment by nojaf** [comment]
This seems fixed in the [latest master](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKB6dYDO0BOAlgA4AuYeiANgIYkEBuiYRtAFtmCbJ60wLKwAdrAB0AYUTQClMNUHwwA4SIDypAkI7Vs2RAFsARpQKJsAHTxnBAYgCSYM5BEj0LaAGtqAc1PoloiSlKEQAGEQBGMPD0YwN0QUQSABYQxwsrOwcnFzdPH2w-IVE1Ok0RAGUCLwT4UJEAJhEAZhiCOITkgFY0yxs8LP9xSWkejP7HQcDpEQAFeANHMEwwAAlqRk5uIgBXMhJeMBF4ShkhMAIAM0UioaDZ%2BfOtSmwtil1BEnS%2BgZuSjUFzJAvl9YEREIIwOUAJ7YEj6EFgiHQ2H6cSwE6SUoAkQAcXBiEI0AR4MhMLhehEthUxKRZNRACVEBdKJj-jTFAR8LAXhcSCIAGLlVjUPBEEQAFUQAA9Pr1QSTJsNKOzFXc5gs5Yjrso-ppgb1lmJYHo9HIFMYErI8F5tnpwWQWHhsARBF5mBRqIYWWAALR%2B-0BwNB4OBr4ssgACgAhABqACUYAjoKxYDQsMIrrAACocCQM26cxH0y63T6AHxgbaCAgkOMJpPqTSpsC6wTlRIJgC8Xwg4fdsC4JChYIANGBeJQiGPqNAU52wMm2b0IIuygBBeDwCNEPADgfDxBjidTsAJADupJRFLXs-%2BAB5i66yxGZ1i65AR%2BAoLoSHRXdhUDAABtL8IFACAIKgAASIcwUAyAXRID9QIgyAoPoahKG2ZA0BAyDIJCT98NQ2x5HtSoAC9kCI4iwCSFCIAAXRQgBfGiwIY6DYJwqBEOQ4i0IwrCeLw2jwnY-DID4agpQAGRdRBZPBLx9n4sT6hCTjmMgtiUPAySYIPeCDFgdE1MgwTMOwwDROI%2BoJIs9s9E5dEhDXEgAFF5BUC55IScz8IuTDdC01iJP0izDLgtBIBMsyHOgoTrNwziICaBKIEgco3EQAAhJlYAoGYRU9RICQCyC82w0KdPCzi0O44zTMoCrEqskTUrojKoGymc8oKihZNgM8CWgbREFI%2BhYDGrFWogKrEBqiDdMgiLUKinjYua1rLOEmzOs6bqspy-KLkKxAAFUiDBPAxt0Sbptof45rAILnkW4jtOWuqBI2pr4vq9D2v22iwAANiO3roH6s6KDEGgdCNAEqtnQqXrekLPrCvTAcamK4pahLduS4DOoAdkhk6BsQPh9AMcruoxj78K%2BiAVogtbMr%2B-HtqJoG9pS0GAA5Kb607zqNSghHR4Lmcg1mwHZjjfrxqACZ2-mSds-CAE5RehtdeQJI0TWoF6FqWtmfoM1WtoB36ko60HIn1mHzqclypcEGX3stxXrci231b5x2QbE8TOuOvrDbhPAPbgL3zbwaqsdqnGVaMnn7YM0PBfUo7SKQD4VEEcU8ChAB1GtWB9zGWex1bccztXecB3PSed9LI6hxA113Kt4AAESoAhnNjpOU-rtPG4z6LeI%2BDX2%2B1yDwiSI7pKlWwLnFXhBA896hUKkgq-gVTupSP2lbATmuObhCF5D4G8%2BI8JDsjjfSIuAgpTUAlaEKjyUodymGdNLbqnRNKp2%2BunG2d8%2BKPwFh3MSEN34yUZHAPA8AT5n06hfKBVsYGBzgQ-NuT8kEvwpqgqUfc8DUChCoPA8lYTYJrufSBU9oEz1gXPe%2BSEEFa06uEEWVCABq7VcoungCWFhL08EcIIVwohPD4GkMQcvCC4Q9ZUP5FWW8QgJHyGkQQU%2BrDcHsPlg3DmTceHB1UQI0GGl17bEoHQC0eUpYeFyrQjwiRsAl3KKVSWtpvaM1lpfAO60g6twdmQ9REB6gR1BpAAAcogM8bj8okBGuCcUB5h5f2rFiNc8haaGAJABUJvt8H%2B0IZEu%2BtiYlqM6vUeykcADSiBEBEC3jvcEpEAl2j8tRTqTNwm1K5rbFRjT7G0XqF3JJG997OWwKwGRbCxmKLqTY6JOdYnNLXt3EsLI%2B42jtB8CuiADACCQLXOWEEFZXxvg1epOzIpL2aW-JJa5jDVB0YIPRbYqiCFoNsCg4pYCF3tE9MBIywnVMedYzaDTdlNIcSgr5LiCTAroIwIarpSn0zwPkl0NZ-gVNhVU%2BRNTNkTJednN5eyHGUKSeUPMnISDXOGaDUZ8KvyMRoghbA-JnSAVGSxIAA).
