### ISSUE TITLE
Configurable space around range operators (..) and (.. ..)

### ISSUE THREAD

**Issue by maxild** [fsprojects/fantomas#643]
Ranges using the infix range operator `(..)` (and the affiliated `(.. ..)` operator) are formatted differently in v2.9.2 and v3.1.0. I personally don't like the v3.1.0 behaviour, and would like a named setting in the `Fantomas.FormatConfig` [system](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/FormatConfig.fs#L12), (
Maybe something like `SpacesAroundRangeOperator`) such that I can switch between

```fsharp
// v2.9.2 
let numbers = [ 0..5 ]
```

and 

```fsharp
// v3.1.0
let numbers = [ 0 .. 5 ]
```

This issue is a reaction to the changes merged in with PR #466

**Comment by maxild** [comment]
@nojaf I personally like ranges formatted as 

```fsharp
let numbers = [0..5]
```

This can be controlled by `SpaceAroundDelimiter`. How does setting this to `false` (not the [default value](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas/FormatConfig.fs#L41)) change other formatting of F# source code?

**Comment by nojaf** [comment]
Hey @maxild , thanks for opening this issue.
To reply to your comment in #466 , we appear to be using both `x .. y` and `x..y` because of multiple authors I think.

Fantomas is not formatting its own source code, in that past that wasn't possible and I'm not entirely sure that it would work.
Main reason for this is that Fantomas is not perfect, we are making progress each release, however you can't quite compare it yet to things like prettier.

Personally, I don't have a strong opinion on the subject. Choose one option and stick to it.
In this case it seems like a single setting could be introduced to control this behavior.

SpaceAroundDelimiter will add a space near `{`, `[|` and others. See https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#--nospacearounddelimiter

**Comment by maxild** [comment]
I was exposed to fantomas because I updated ionide in vscode. And suddenly all my ranges was formatted with spaces (I normally use `"editor.formatOnSave": true`). 

In #466 @jindraivanek talks about official docs. In the [language reference](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/loops-for-in-expression) I have found ```0 .. 5``` syntax, and in the [style guide](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting) I have found `0..5` syntax. I haven't found any definitive guidance from Microsoft. I guess some people like spaces and others (myself) like the more terse syntax without spaces.

**Comment by jindraivanek** [comment]
Note that with terse syntax, we would need to solve #456 some other way.

**Comment by maxild** [comment]
@jindraivanek is the following code at the REPL a problem

```fsharpi
> let numbers10to0 = [ for i in 10..-1..0 do yield i ];;
val numbers10to0 : int list = [10; 9; 8; 7; 6; 5; 4; 3; 2; 1; 0]
```

Is it because you don't like no spaces before unary minus operator?

**Comment by maxild** [comment]
@nojaf I must say that achieving the syntax `[0..5]` by setting `SpaceAroundDelimiter=false` does make records look kind of ugly. Just browsing through some of the most used community projects on Github (e.g. FAKE), I see ranges with no spaces and records formatted like

```
type AssemblyInfo =
  { FullName : string
    Version : string
    Location : string }
```

Those are mutually exclusive using fantomas, right? 

You also said that you are not using the code formatter for your own code in the repo. Is anybody using it in the community? I haven't found any code that have a fantomas config file, or any code that doesn't have a lot of different ways to format records (types and values).

**Comment by nojaf** [comment]
`.fantomas-config.json` is a brand new concept that has not been officially released. It is part of the [latest beta](https://blog.nojaf.com/2020/10/01/fantomas-configuration-file/), released two weeks ago.

Those community projects don't necessarily use Fantomas so that example is most likely unrelated.
I use it in my own projects, f.ex. https://github.com/nojaf/capital-guardian/blob/master/build.fsx#L155
Fantomas still needs to grow in adoption and improve in general.

The formatting of records is a popular topic. You can write records in F# in multiple ways:
```fsharp
type AssemblyInfo =
  { FullName : string
    Version : string
    Location : string }

type AssemblyInfo =  { 
    FullName : string
    Version : string
    Location : string 
}

type AssemblyInfo =
    { 
         FullName : string
         Version : string
         Location : string 
    }
```

Fantomas uses the first style and not everyone is on board with that.
Some people don't use Fantomas due to this reason. 
Discussions are ongoing about this, see https://github.com/fsprojects/fantomas/issues/453 for example.

Lastly, @jindraivanek why exactly do we need a space in #456? Will it output different AST?

**Comment by jindraivanek** [comment]
@maxild @nojaf  Problematic code is something like this `for i in (9+1)..-1..0 do ()` which is compiler error. It is quite possible this is compiler bug, it is weird that `for i in 10..-1..0 do ()` works.

**Comment by nojaf** [comment]
Closing due to lack of input of our supported style guides. Please review our Contribution Guidelines.
