### ISSUE TITLE
Don't indent too far

### ISSUE THREAD

**Issue by cmeeren** [fsprojects/fantomas#659]
Following up on #657 #658, here's another example where Fantomas produces suboptimal code.

I think the below is fine:

```f#
ctx.Response.Headers.[HeaderNames.ContentType] <- 
  Constants.jsonApiMediaType |> StringValues
ctx.Response.Headers.[HeaderNames.ContentLength] <- 
  bytes.Length |> string |> StringValues
```

Fantomas [formats it like this](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=MYFwHgdASgpgzgBwPYDs4wgCRgQwCYwBOcEA2tvkQHI4C28EAwqiDCiACoCeCMAugAIAPAFoBAWABQAgczQgc7EgCs4qAIIIAlgFkYeLTm68BAHwB8AgMohCWlAHMAajgA2AV3hTQkWIlToWLgExGQUITT0JHKs7AAybA4gABaCohLSAgBGXKwkCY4pZpZwtvYOxdZlji4eXpJAA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZECcADAL5A):

```f#
ctx.Response.Headers.[HeaderNames.ContentType] <- Constants.jsonApiMediaType
                                                  |> StringValues
ctx.Response.Headers.[HeaderNames.ContentLength] <- bytes.Length
                                                    |> string
                                                    |> StringValues
```

See the linked issues for an explanation of why this isn't good.

**Comment by cmeeren** [comment]
[Here's another example](https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=AQ1kN4D4CYIYBc7ALwFgBQ5vmg1wARAA5wBOApgHYICMhmOToAljASfY805QDaIWAeyoBnABYtio1Nx5NoAY0l8YlKrKzzt0YPCQEA2nO2nd+FEWUtVAJkIBuYGw6L7wKAF8Tp+edcqMPROLpaEivQe3lq+PAC6PrFgXom+KTGm6dpeQA&config=N4IgkgdgJgphAuBlADgQwMYwHIFcC2IAXAEwA0IACqgOYwDqAllPABZEAcADAL5A) using anonymous records. If you adjust the page width to 50, it's more in line with what I consider readable code.

**Comment by cmeeren** [comment]
PS - this general issue (indenting too far) is the primary thing keeping me from actually using Fantomas. Statistics suggest I'm not alone, though of course I have nothing concrete. I really want a decent F# formatter, and Fantomas is currently the best there is, but there are some deal-breakers. I'm posting all the issues I'm posting only because I hope Fantomas might one day "fix" what I consider to be deal-breakers. Keep up the good work. :)

**Comment by nojaf** [comment]
Hello @cmeeren,

I'm well aware some people don't use Fantomas due to some stylistic decisions.
Fixing those things could potentially be a lot of work and it hard to justify the effort versus the gain.

Don't take this the wrong way, I often agree with what people say when they ask for stylistic changes.
However, there is much other work left in this project.
There are bugs in Fantomas that break people's code after formatting and even performance issue when the file gets too large. These things to me have a higher priority than stylistic improvements.

The lack of concrete numbers also doesn't help in making decisions on what to pick up first.

That being said these examples could fit under the `KeepNewline` feature.
The idea of that feature is that certain newline is preserved if they are found in source code.
`=` is not taken into account in records and `<-` not in setters.

**Comment by cmeeren** [comment]
> There are bugs in Fantomas that break people's code after formatting and even performance issue when the file gets too large. These things to me have a higher priority than stylistic improvements.

Totally get that, thanks again for all the great work 👍 <3

**Comment by lydell** [comment]
Here’s another case of indenting too far:

```fsharp
f x =
    Case.fromCaseTimeline [ { mockClaim with x = 5 }
                            |> Event.claim "42"
                            |> Commit.caseCommit System.DateTime.Now ]
```

I’d like it to be something like this (with `fsharp_multiline_block_brackets_on_same_column=true`):

```fsharp
f x =
    Case.fromCaseTimeline
        [ { mockClaim with x = 5 }
            |> Event.claim "42"
            |> Commit.caseCommit System.DateTime.Now
        ]
```

**Comment by nojaf** [comment]
@lydell that shape matches the Elmish DSL, these are formatted differently...
See the end of [this video](https://youtu.be/n4C3f2b32O8?t=66).

**Comment by lydell** [comment]
@nojaf Cool video! I’m not sure I understand what you mean though?

- That I can disable it somehow?
- That it’s difficult for you to support because of the Elmish feature?
- That I should open a separate issue? (Feature/option request: Never align based on the length of names.)
- Something else?

**Comment by nojaf** [comment]
The video explains why you see what you see.
`Case.fromCaseTimeline [ ]` matches that Elmish shape in terms of AST and is formatted as
```fsharp
functionName listArg1
```
instead of 
```fsharp
functionName
    listArg1
```

There is no way to disable this atm (you could create separate feature request to have this).
I tried to improve the Elmish thing and as a result, the alignment here is fixed after the function name.
I guess I tried to say that the sample you provided falls into a different category as what @cmeeren originally posted.
Also, `Never align based on the length of names` is rather vague, I think in this case you want to have an option to disable the opinioned Elmish stuff so it follows [the normal flow](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzMAPMBeAOgE74B2EEAwgIYDOiAdOobALbV0AqAli4gDZcSiMAAoAlGADaYYGBaxoAawp8qPMAHcuAFwAW2PGACsYAL5FS5K9Zu3rAHwB8YAKIA3RCW31oq9fkgAFgAmAIsyO0ioiCcwClYWHR9aRHiWRO0wAGUATxptRBZ6ABEqAu5eegA5WA0wAF1IABpwKDptbUEAcxpUKVaIUBtIABJtHIAHZDRIQW1mgfJRtyo%2BAFdp-rsABha7SABJEiQvLK4AL2Q920DFiHrF02vBu6gxyc3ZrwXhkZX1zaSV4QACMz2skAAslQsAAZQSIWGeLp6H62EHBbavB5WJ6LIYQ95TPqQABGsFgfDRVmWqw2fSBdmC4JpWUKXDgfFgJAAgtoXMcAPLoeFCanWdCrOjYx7ggk0omfcmU8UQWkAhnAsAAZhZSyyEyo0EQACFEOhYIREAAFKiEKi8AqEVXkbSEDYy3Fy16jcbEmbKql69X0tCMm56tUGo2m82WxG1RCEaApI5uBRlLjcl0QN0emw48h4qzypaKkmBl0hwFaoyRqDR41mi1WgCqEymydTJHTKc62frkr40oLsvxPvLAYpQYn-1DW1sADZ65BG7GW6lVDQaPESPl3dBtJac2AhyPrIWIMXyKW1ZOoJXg386TW7AB2Fdr5vxyGFUlJk8z0QT0i29X4-SVacq2fDUwy1AAOT9DSbOMrXiLkSEAqVgNHL1x3Aj4Kygp851fWwAE4kJjHl0CdNIWCoE88xwi8xxLCcIKIlUSJfTU7BBXYtVXZD13jNlEk5ActSAkCrzAwlOKnbjZ14uD%2BLBIS1xop1xI5SkpLsZjZLMeSFUUh9iJU2CFxsDEVyOE5tEFEgOEIHIAHUdF0LDhxYqxLxM-CFMIpSZ1%2BUi%2BPRXVNJEnlmDWY5in4HgdAA%2BsjNw0CgrMkKoDmaCIrU9FAhXaEsAOdAOF0TwXF8rJdEtbRPPgVF60CLFMrk7Ky3Mr55h46zw1sushLKo50C4LBBU7MpLRcLAJitbcs0w%2BsjA61i8PYgj-Ty74BvnIbrBBZdRphAAlRA4EIeBmtarV2uM68Xh2z58oOsjbI-M6sDi%2B0ckFQh4XyO7vLajb-LYm8ONyvqCtUmzjsQn6ADUXxNQR4G6UGT0ezrAu24Ldrhj7ItsyifoAMQSw8Vox45sa4FqwYeiHyAC56ZBh4nHysw6tUxUq1j4ToBCEE0uSUE17SURBtBoZysgdVJKTWFhVuk7CntMnrYd58KEaOqxgg0-YqkQDQxdjbQNEQTwOA%2BJKJpIHQVp5Y5fxYf9CF6QctfxznbzeXr9cJQrEeN5khIAaTtiYKqqzwjiV3hRSuTXfO17q71696%2Bc%2B6xgmi-YytqxIaF0HHwazwmcp5yyDcGgWSs07o%2BEQOKujVzwmsQUlIQQdO7BkgOdZzvWG7Dw2BZG-YeQELoSGpkhae5M5F7KNYrQ4WAHJ7zMDNsEfNqy2vdfr5TG-5plTrnkWkxITMPFhbkuk972ncEV3uV9jPz0hra0NXpcTClPJuTJvr7CyG6Dk2gB5IB8v-dmjxWj1GuLMGglMaBcD6DJUwQA).

**Comment by cmeeren** [comment]
> Also, `Never align based on the length of names` is rather vague

I find it clear. In my words, I would say "never let the length of names influence the alignment of other code".



> I’d like it to be something like this (with `fsharp_multiline_block_brackets_on_same_column=true`):
> 
> ```fsharp
> f x =
>     Case.fromCaseTimeline
>         [ { mockClaim with x = 5 }
>             |> Event.claim "42"
>             |> Commit.caseCommit System.DateTime.Now
>         ]
> ```

It seems to me that the pipes are indented two spaces too far. They operate on the entire `{ mockClaim with x = 5 }` and should be indented similarly to its opening `{`, not deeper. But that's just a parenthesis and not terribly important to this issue; I just felt like pointing it out to be clear.

**Comment by pragmatrix** [comment]
> never let the length of names influence the alignment code on subsequent lines

In my team I call them "vanity alignments" and they are strongly discouraged even when auto-formatting tools are used. The reason is that sometimes diffs get confusingly large when names are renamed and tool support breaks down, e.g. indenting with the tab _key_ may not work if alignments start at non-indent multiples. Moreover I think that the aesthetic properties human code readers see in them are subjective, because I feel that there is also a lot aesthetic in code files that change one indent level per line at maximum.

**Comment by cmeeren** [comment]
> In my team I call them "vanity alignments" and they are strongly discouraged even when auto-formatting tools are used. The reason is that sometimes diffs get confusingly large when names are renamed and tool support breaks down, e.g. indenting with the tab _key_ may not work if alignments start at non-indent multiples. Moreover I think that the aesthetic properties human code readers see in them are subjective, because I feel that there is also a lot aesthetic in code files that change one indent level per line at maximum.

Great summary @pragmatrix, I agree with every single statement here. Which is why I can't use Fantomas before the some configuration (default or otherwise) allows me to remove the "vanity alignments", which is why I'm pushing for this in several issues because I'd really like to use Fantomas. :)

**Comment by knocte** [comment]
> I think the below is fine:
>
>ctx.Response.Headers.[HeaderNames.ContentType] <- 
>  Constants.jsonApiMediaType |> StringValues
>ctx.Response.Headers.[HeaderNames.ContentLength] <- 
>  bytes.Length |> string |> StringValues


@cmeeren how about this way?:

```
ctx.Response.Headers.[HeaderNames.ContentType]
  <- Constants.jsonApiMediaType |> StringValues
ctx.Response.Headers.[HeaderNames.ContentLength]
  <- bytes.Length |> string |> StringValues
```

(assuming indent size of 2), this would be more in line of how lines are splitted through operators today.

**Comment by cmeeren** [comment]
I would consider `<-` akin to `->` in match expressions, so I prefer them at the end of the first line. But I could certainly live with your suggestion.

**Comment by knocte** [comment]
> I think in this case you want to have an option to disable the opinioned Elmish stuff so it follows the normal flow.

I see that @nojaf introduced a new setting to disable elmish style (https://github.com/fsprojects/fantomas/commit/1c1411f818b9375ac75d327db25cb9baebbdfcec), anyone tested the testcases again using this setting? If it doesn't help, I wonder if a PR that fixes these scenarios when this setting is used, would be accepted? If not, maybe we need a new setting? If yes:

> Also, _Never align based on the length of names is rather vague_, I

It doesn't seem to be very vague to me, especially considering that this practice is actually just simply called **alignment** (with no reference to lengths of items, just alignment), as explained here: https://dmitryfrank.com/articles/indent_with_tabs_align_with_spaces , so the setting could be called just like that, **alignment**, or *LengthBasedAlignment*, or *VanityAlignment*/*CosmeticAlignment* like others suggested?

I'm in two minds about whether alignment is good or bad in general, I've been guilty of using it a lot (knowing that it can cause unnecessarily long diffs when renaming/refactoring) but there are times in which the code looks much clearer with it. Regardless if I go for it or not in my projects, I think a setting would be a thing of value for fantomas.

**Comment by nojaf** [comment]
Gentlemen, I do not care about any these discussions. Everyone thinks they are entitled to an opinion and I'm sick and tired of having to deal with this in Fantomas. I wrote this all down in our [Contribution Guidelines](https://github.com/fsprojects/fantomas/blob/master/CONTRIBUTING.md#what-are-we-not-looking-for) and going forward I'm going to need evidence of a style guide reference before changing anything.

So, please open an issue on the F# style guide for the original issue and come back when you have an outcome.
Otherwise, I'm going to close this issue as I have done with others. No style guide, no style changes.

**Comment by knocte** [comment]
> Gentlemen...

Woah, please re-read my last comment. I'm first talking about a setting **you** introduced, to ask the reporters if it helps with what they reported. Second, if it doesn't help, I'm suggesting a possible new setting. I don't think discussing settings belongs to any style guide, because style guides have a strict style, settings are for when you want to deviate from that style in some certain aspect. Otherwise, MS style guide would offer different valid options for a certain aspect, and I don't see any occurrence of this.

**Comment by lydell** [comment]
> Everyone thinks they are entitled to an opinion and I'm sick and tired of having to deal with this in Fantomas.

Oh yes, I know exactly what it’s like – I used to be one of the maintainers of [Prettier](https://github.com/prettier/prettier/). I’ll take the opportunity to say thank you for all the hard work and continuous improvements. Coding F# is so much more fun with Fantomas.

**Comment by cmeeren** [comment]
> Everyone thinks they are entitled to an opinion and I'm sick and tired of having to deal with this in Fantomas.

Yes, thank you again for all the hard work 🙏 and for clearly pointing to the new contribution guidelines. I have now started a discussion about vanity alignments in https://github.com/dotnet/docs/issues/21487.

**Comment by cmeeren** [comment]
For the record, https://github.com/dotnet/docs/pull/21690 was just merged, so now the core issue here (avoiding vanity alignment) has style guide backing.

**Comment by lydell** [comment]
@nojaf Since https://github.com/dotnet/docs/pull/21690 was merged, is the intention to remove all vanity indentation from Fantomas? If so, in what way do you prefer to track that? One “Remove vanity indentation” issue, or several issues for every little case we find? [Example of vanity indentation](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAzWsBGBDATmANpjBiwB2iYAvGAIwDcYALgO6y1gBMzLAFvkTU6AZmaYAroToAWCQEsAbiLABWMAF8wAXUgAacFADOiFiwUUA5sdTEjEUBGdQAJCwCeAB2RpIllgMHZ0hXJVwAG0lfexcXAAZDOJCASQokChYAZQUAL2Qk5LBZYIgdYM1Cx1K3Tx87f0yg5NDwqJiiGoh6KrjIAFlcAA8AGUtEEcRrAWai%2Bm54mvKXSuCnPvdvGMhsLAjZl1bI6LtOop5ew6zEAFsFOAjKAEEWAFF0gHl0MaoDuPRIqYlhVeutDpt6n5drB9pc3G0TmgzkVRHCIJAsl5cNBEAAhRCYIQABQIuBuZkQ%2BD%2BLhY%2BGiwJWoJqoTq22hsOZYWOHS6xTRUEx2LxBNgQhGsDYlOguFMaSUsGlFko1OctPpyWWzlWLjBIQhbL2KqO7VOvLU-IxWJx%2BMJiAAql4fPhpbKKPLFQplfyAREgRqQWtOayGuyjVyTUjeQA2C2C60ioQAYQiMuMicoxjV0BYopVEB9frimog2ucuvR%2BpDhrhxsRsSKAHZY1bhbb%2BrdsJS82AC4gGVqmS1K1Dq5yETzzgAOZtCm2ixDpx4Ubu9-slwcbYMjmFh8em84AThnOKe6BYlPTNxuuG7ar7-sZgaHW6goZr4bryOS9ESvMts4TRBrjuB4vV5VcHwHJ9Ny2Ksd3fPdI3Oegej-ONEFPc98GA%2B4YTA847zXLQN3BF8dlHIdEPrb9uAtNIMhYD4KAAFXwDwAHUFBmb1AXvIsAx1INYO3DlKO5fc5lRNCWyefBYEkdIABFEAiBQ7iw286T4lxi2I6DSOEqAAl3cSkLmWQLUGIYUnQZj%2BCmV5fSA-hRRYTj4G43lZEWSD130vUyOMhDTOouJ6HNP8rLSdAFCGD4nVwHN8FeIYvCEYxjE9Zd%2BTUHz%2BMfQTn0MxpAmCiNQpcegY0i4YACVEDgfB4Hczzzm8ojS2qIrISMpoys-Xl6CbGqhnqxr4AAOUkG5O3wL4UnPG5bH5egOpIgLipuSQIgsVSqAAMVFa9zEpZjYP6ic5mnP8xtFeB%2Bm23bxkO-Bjo0i1oH4Uls0pAB9NgFA8-hIDW-yK0CvqxxCr8wqPEbZPwXAPA%2BfAxkzFrgf5drfL0wqYJ6kqTPKmGXAWSzhgRpGUbRlgppmyl5sW5bBtBvGDIJradoUPbEBet7TvOqHid5bhUPOSBKeR1GFEzB6uZ5vnEvev9Pu%2BrD-sBmZWbLISCaCoWBvObhaJGgA1blcUseBLCsDHu2x-KoLZja9chsThaNqTxas-aFOzLLLfSG27axvKdIEnXuu2fX3cNopuAskbFNgFgAHEzBStLEAyrKQ7NMPnF0zrSF1g14INy7km4CLvce7nxlxR5oAAa1xRGW7MYwmKyMkFxhabsvA3jta6-Gy9EjYqJJ5xuGq8WJsQNgefxdhhBYrZlJiiguKyp50nben8GZ84IMdvznfB4q3wriSq%2BG8WAGlhC8Gy7KmNIe-JH4CiHpyR5LqODQY6T2hiLa63thiOTuMYfgec2oFzKBHUe7Nx5EzjlXOG4scjWAiBhfAVhppTDcogbA-QEA-xPsPHGxdyy1CvhREBHsUS-nFk8VSVgKC%2BwoP7SgOQOGJWkIgZisB6JEMSllFcVCz640jmPOCE9wRT15KIMWRQJY7UpBQcRKhxTWAPrNTelgd4ZkkX-ah61L4E2vrHSucRRAm1rlzb%2BIwyTYHgLgZMsBMrWAXkvcYpjCzhwKrIlB8i0G2JcKIL2ajFIy1wNgXBUCZb8CyB4TIwwAnaULkggBci-BTHgF8b%2BWRPC4PCbfOxidxbvEKd8fxH18ARHQCDcxYM6FWIYYo0B5xRA1zUSU-A9wWBkKQJkjqRgdCFH8MYfamU7Crk0EAA)

**Comment by nojaf** [comment]
If somebody is willing to do this, I'd prefer separate issues for each case of the updated style guide.
It is ok to use the online tool and point out that Fantomas is not adhering the style guide (with a link to the section ;))

**Comment by lydell** [comment]
I opened two issues: #1302 and #1303

I’ll open more as I find them
