### ISSUE TITLE
Idea: Remove unnecessary parentheses around simple constructs

### ISSUE THREAD

**Issue by lydell** [fsprojects/fantomas#684]
When refactoring code it is easy to end up with some unnecessary parentheses:

```diff
-Workflow.run (makeRequest author) "/invoices"
+Workflow.run (makeRequest) "/invoices"
```

It would be nice if Fantomas could automatically remove the now unnecessary parentheses above!

I’m thinking that parentheses could be removed in the following cases:

- Around an identifier: `(x)` → `x`
- Around a literal: `(5)` → `5`, `("x")` → `"x"`
- Double parens: `((whatever foo))` → `(whatever foo)`
- Around a “top expression”: `let x = (whatever foo)` → `let x = whatever foo`, `| Some x -> (Ok x)` → `| Some x -> Ok x`
- Maybe other cases as well that you can think of! For me, it does not have to be comprehensive – it would be helpful if at least a few of the most common cases was supported.

**Comment by nojaf** [comment]
I'm very skeptical of this proposal. This seems more like a thing for analyzer instead of a code formatter.
I'm not entirely sure Fantomas can make the correct assumptions of removing `(` with the guarantee that the code will still compile.

**Comment by lydell** [comment]
For more context, I’m used to this behavior from Prettier and elm-format 🤷‍♂

**Comment by nojaf** [comment]
Yes, and to be clear I agree that is is nice behavior. My main concern is that we are introducing something that could break people's code. At first glance it might not be that easy to implement.

I would like to see a proof of concept PR to measure the impact in the code base.

**Comment by nojaf** [comment]
I don't want to pursue this in this project.
Please consider contributing to:

JetBrains Rider (https://github.com/JetBrains/fsharp-support)
Ionide /VsCode (https://github.com/fsharp/FsAutoComplete)
Visual Studio (https://github.com/dotnet/fsharp)

**Comment by lydell** [comment]
Ok.

@nojaf What is your personal way of handling unnecessary parens?

- [ ] “I probably have lots of them and I don’t care”
- [ ] Keen eyes and quick fingers (if so, how do you do code reviews?)
- [ ] This cool tool: _______
- [ ] Other: ______

**Comment by lydell** [comment]
JetBrains Rider now supports detecting and removing redundant parentheses 🎉 

https://www.jetbrains.com/help/rider/ArrangeRedundantParentheses.html

**Comment by brianrourkeboll** [comment]
Since people seem to stumble upon this issue when looking for this functionality in Fantomas, I'll just note here that a [parenthesization API](https://fsharp.github.io/fsharp-compiler-docs/reference/fsharp-compiler-syntax-synexprmodule.html#shouldBeParenthesizedInContext) was added to the F# compiler service in https://github.com/dotnet/fsharp/pull/16079, https://github.com/dotnet/fsharp/pull/16461, etc., and there are now analyzers and code fixes based on this for removing unnecessary parentheses in Visual Studio and FsAutoComplete (Ionide).

The current API has limitations, however, and it would need additional work (see https://github.com/dotnet/fsharp/issues/16966) before it could be used by Fantomas.
