### ISSUE TITLE
Ability to add newline between module definition and its body

### ISSUE THREAD

**Issue by Thecentury** [fsprojects/fantomas#695]
With this setting enabled, code

```fsharp
module Module =
    let x = 42
```

will become

```fsharp
module Module =

    let x = 42
```

**Comment by nojaf** [comment]
Hello @Thecentury, I see that you already started working on this in #696.
I'd like to remind you that we have [contribution guidelines](https://github.com/fsprojects/fantomas#contributing-guide).
In those, it is stated:

> For new features, the same things apply: please discuss before making a PR.

I'm not sure I want this feature at first glance to be honest. And just because you did the work does not mean I'm mandated to merge this.

With that off my chest, I do wish to start a constructive conversation. I'd like to know what your motivation is for this change. 
If the original source code contains a newline after `module x =` it will be preserved via Trivia (see  https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=LYewJgrgNgpgBAWXNeBeAsAKC3XdYAucAHnKnACwBMQA) so I'm wondering what your use case is here.

**Comment by Thecentury** [comment]
Hello @nojaf, my motivation is to become able to format source code according the guidelines that exist in my company. Sounds pretty selfish, I guess :)

Regarding your comment about preserving the newline — I'd like to get this newline even if it is not present in original source code.

**Comment by nojaf** [comment]
So I'm assuming you only wish to introduce the newline when the module is nested right?
https://jindraivanek.gitlab.io/fantomas-ui/#?fantomas=preview&code=LYewJgrgNgpgBADwLAChYBc4E84F44AcQA

I feel like the setting name should reflect that as well.
Would do you think of`NewlineAfterNestedModule`?

**Comment by Thecentury** [comment]
Yes, my wish was to introduce a newline for nested modules.
I also had doubts about the name, so any suggestion for better name is welcomed.

**Comment by nojaf** [comment]
Naming is hard, I'd go for `NewlineAfterNestedModule` because `NewlineBetweenModuleAndChildren` would indicate that the setting has an impact on every module which is not the case.
The setting has a very limited scope, which makes it a good setting.
I'll review your PR when I have some time. I will have some minor change requests but the overall approach is good.

**Comment by Thecentury** [comment]
Alright, I'll rename the setting.

**Comment by auduchinok** [comment]
> Naming is hard, I'd go for NewlineAfterNestedModule because NewlineBetweenModuleAndChildren would indicate that the setting has an impact on every module which is not the case.

It's not about a new line, it's about an empty line which consist of two consequent new lines. Let's use empty line term?

The `AfterNestedModule` also sounds like it's about placing something actually _after_ the module but it's in fact inside, before the first thing in a module.

FCS uses term `module member` instead of a child so I'd be in favour of it too, though, speaking about tree nodes, a comment would be a child node too.

Maybe `EmptyLineBeforeNestedModuleMember` or perhaps `EmptyLineBeforeNestedModuleBody`?

**Comment by nojaf** [comment]
> It's not about a new line, it's about an empty line which consists of two consequent new lines.

True, I like the `EmptyLineBeforeNestedModuleBody` suggestion.

**Comment by Thecentury** [comment]
@auduchinok @nojaf Renamed setting to `EmptyLineBeforeNestedModuleBody`.

**Comment by nojaf** [comment]
Closing as https://github.com/fsprojects/fantomas/pull/696 as closed.
