### ISSUE TITLE
Wrong handling multi lines comment at the end of file after function application

### ISSUE THREAD

**Issue by matteobaglini** [fsprojects/fantomas#810]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAHATgSwHYBcAzXMAHUgAlEAba2MAdVk2vnNNwAoAqMAFQAW2AM5gRYAIZg4AWxmICAOjDcAlJAA04KMMT58eAObDUYANraIoCDagASfAE90yNJDz5Nlm5DsA3CWoAV1dzb1sABi1bW0gASVwkAgBldAloRAA5IJkvGJsAFnCwAF1vAF9om2sY3ycXU3cCPNr-QJDTC3yIAEYq-MgABQlDRAZseHwBFvyegCYI4rLbSu8a2IdnUMgAI1hYahmfNuDQru65-trkxBlsODpcAEF8AFFEgHlCABk8ZCvbIRArolhUrutjvVtnsDkcIL4AqdOsUIABmAE%2BVLpRAAIUQhGYiGGmAk8nwiEwcJs%2BEwIVBK3BxTqW0aMMOGIR7TOKLABQx8KxGTxBMwiG%2BsAA7hToBJdAk-LAZQZYLgqRAaXT8ssbKtbBD4ZsGm42VTOUi0Od8gBWflQQW4-GEgCq6BcmBlctwCqV2BVarAQOoIK1YLWTMN0P27PDiI6Fp5ADZbZB7cLCQBhaiy4TplXCDXQfDMf2B4MxbUQXXVcNQ1lR00nONhbpgADsydTjtFAFlbjsKSXgYh6TrGQMI3XYRzG9yWwAODtpIVdxC5x6DoPDkMMsPj2vG%2BvT2Oz7oATkX2KehHJmFzcgk-o1W-Lob1NZZB6nMa5yJbPSiPIpkuDoiogNx3A8fq2qWz62BWYBVlY75GlAJpHj%2B8Z-n0gH2leN7gfcBxQTyT4jpWY6tPuqGHt%2B5rNt08zJgkST4B8uB8JgjjjFMG5lnBr7VnuH7UV%2B47Hr%2BDHojhwFPJgsBBIkAAiNDYHcN6PrSsE2PBiFgPq9hUU0njoXRloxD0fKAd2EgAB5xIQggKK8m7JAIzD4OMkzTLaBSLNuo67pRwlGQ24mYQxNpWbZCSENgNkfG6EhFpgrw2VgiDCMIvqqraVp%2BS%2BO5vkJKEhSZTZmbYPRJlFNkAEqIHAmDwJ5PE%2Bfl-GFYJQUlR4oUYfRsztjVskko4HyYL8%2BYtd5PK%2BWRCEURshm9WVJ6zAuNXfHoOJ4PARjTf6c3%2BeRgVLcFaG0eVPI9OeVlBNQBjUH8OJ0NAADWOIku9ejCGxySkquBw5DlPIwfNun6cyJUXWJ-UVTYCzJpkiASk9uAOvgUoKHwWzKbFuDYMqzyJL2Mj9pgJjQUO4OLZC500bDpk8nM2EtimNL3Pg3YIP8oPU8dCHaCUVTuMIABiWWmGD5RAA)

Typically comments at the end of file stay there after formatting (see [test](https://github.com/fsprojects/fantomas/blob/master/src/Fantomas.Tests/CommentTests.fs#L377)), but if the comment is a multi line one (`(* . . . *)` block) and the the previous line is a function application, the comment is moved between function call and parameters. 

#### Code

```fsharp
printfn "Hello World"
(* This is a comment. *)
```
            
#### Result

```fsharp
printfn
(* This is a comment. *) "Hello World"

```
            
#### Expected Result

```fsharp
printfn "Hello World"
(* This is a comment. *)
```

**Note** that with a single line comment (`//`) it works properly.            

#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| `PageWidth` | `120` |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
Hello, this is a trivia bug. The block comment is now being assigned to the `printfn` Ident instead of the SynConst.String.

![image](https://user-images.githubusercontent.com/2621499/81410938-e048f180-9141-11ea-8676-f70f29741a8c.png)
![image](https://user-images.githubusercontent.com/2621499/81410982-efc83a80-9141-11ea-8d8f-4273f65e1f8a.png)

The problem occurs when the trivia is being assigned to a trivia node.
I think the [addTriviaToTriviaNode](https://github.com/nojaf/fantomas/blob/6594af6a9995fc4bdacc1cdc281cfd6331b1af06/src/Fantomas/Trivia.fs#L255) case should be extended to support scenarios where the comment is the last line of the file.
Maybe it automatically should be assigned to the SynModule.

You can watch the [first three videos on YouTube](https://www.youtube.com/playlist?list=PLvw_J2kfZCX3Mf6tEbIPZXbzJOD1VGl4K) to understand how Fantomas works and what Trivia does.

I know this is a big ask, but could I persuade you to try and tackle this issue yourself?
This is a good first issue for newcomers.

**Comment by matteobaglini** [comment]
Forgive the delay response but you have definitely persuaded me :smile:.

**Comment by nojaf** [comment]
Hey @matteobaglini, very cool to hear 🤗!
Don't hesitate to make a draft PR and ask me questions along the way.
