### ISSUE TITLE
Explicit constructor parameters which exceed PageWidth cause indentation error

### ISSUE THREAD

**Issue by Bobface** [fsprojects/fantomas#849]
Issue created from [fantomas-online](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqOeAvADoBO1AdhBA4gO4AUANrL3-3wYBzAIxoAzuloBLYQBowPActjCATBKmyhCpSv7CAzJpnCAlGBr0mzW8DqNbtgL4OGbrLgLFEAeXQAFoi05F5WjsysbGAcAIYm2haUYMDOkHLgUOKI6Oja4qhgANqZEKBOUAAknshokLLo6aXMkJUAbrFcAK61xc22AAwZFRCQAJIMSAzo%2BNix0IgAcl1ETSNgACz9YAC6zc7DzOVOrTWF9dNrJ%2B2dPYUl6yKHFZAACrFCiADq0vCBVxUABwDbZ7FzPFLbU4Uc4AI14XABLRu3V6DxGaghtkg%2BEQRGkcB4DAAgugAKKTXwAMwAMrJkFjmFTOtlQfsIcdsdUYXV4bBEYzWh1UfdthBDIzRrN5ogAEKIKmwWiId60WIkdDBJG2KQ9Nng5qc5FnXkI7VVYV3NDoiobSVQaULeWK5U02BsYLQWLZCZtWBevKqc0QXWIfXMA6GqHc3Bws2ClFWvrrACs9pxcydCqViAAqthcLQvT6GH6A9Ig-bmVxWRUwRGOdGTVA%2BQLo5a0WKwAA2dOOuXZ5UAYS43vEQ9UkloXWg6CVwbA1drTnrEEjdibPJb8fbt076wA7H3MwOXYgALJ42FaqsssN19lRl4x3qQVvmoV70XrQHHmXOnMJyJBcl3vFdHw3Z9mzfHdnw7b8RgATj-BZiSpTVaAnIgiFiBdQ3DNdGygrcYP5D9E33EYRCGLsM3-QdEFxfFCUrLtQIIsB1yOTdY1NMiE3g60uxEJ5aP7NCMKYgl%2BVY9Z8IfA1IOuaD3wEr8hMeTFaImKZ0F8BhSFoTAfn%2BW8azA2xV04ojlJI1TdxFDSqIlMST2JWhYC6SYABFEC4aR8QwvDpws5grK4soeNfBpyME5MqLtWjz1iAAPMYqVIIIGDJcz8ACJV0B%2BP4AgXDYQQUhsn1s3ioBitTHPiioRDTJLUomKlpBS3xC1iOdaDJFLsGVcRxArBgFxTcrwMU7jiJqi5GnqpMbScERe1alKACVEDgWh4CK0yuzKjiIshObosuJbKKao8NvctVMF8Wg6UkA6SvtY6KsIqquWguqHOW4Tfw2mkcllWR4G0N7SqmyyINm6rX3suD1Ma1bkKSrouDyfzWFlHhoAAa1lNUiZycR9PwdVECAlZxrM5c4ZmyLzrjfiAeupw1Bo9ZIEWdhcYHdAPUQAyKF8jqGGkQMSUmS8iGvWgCgZ0KIHCmzfrs2DrjilbbDUUTeYAaUQRBsHSzLRYmKmSDpVgQLvE6NeNLX2ZRhq9eYNQtN5-AtFnc8EAZNjHa%2BzjMh2Q56nEAAxUbCnY5wgA)

In the result below `SomeOtherType` has one indentation too much which can cause indentation errors further down in the code. Might be a similar bug as in #844 .

#### Code

```fsharp
type SomeType =
    new(looooooooooooong1: string, looooooooooooong2: string, looooooooooooong3: string) =
        {
        }

type SomeOtherType =
    new (a: string) = {}
```
            

#### Result

```fsharp
type SomeType =
    new(
        looooooooooooong1: string,
        looooooooooooong2: string,
        looooooooooooong3: string) = {  }

    type SomeOtherType =
        new(a: string) = {  }

```
            
#### Options

Fantomas Next - 4.0.0-alpha-001-1/1/1990

| Name | Value |
| ---- | ----- |
| `IndentSpaceNum` | `4` |
| **`PageWidth`** | **`80`** |
| `SemicolonAtEndOfLine` | `false` |
| `SpaceBeforeParameter` | `true` |
| `SpaceBeforeLowercaseInvocation` | `true` |
| `SpaceBeforeUppercaseInvocation` | `false` |
| `SpaceBeforeClassConstructor` | `false` |
| `SpaceBeforeMember` | `false` |
| `SpaceBeforeColon` | `false` |
| `SpaceAfterComma` | `true` |
| `SpaceBeforeSemicolon` | `false` |
| `SpaceAfterSemicolon` | `true` |
| `IndentOnTryWith` | `false` |
| `SpaceAroundDelimiter` | `true` |
| `MaxIfThenElseShortWidth` | `40` |
| `MaxInfixOperatorExpression` | `50` |
| `MaxRecordWidth` | `40` |
| `MaxArrayOrListWidth` | `40` |
| `MaxLetBindingWidth` | `40` |
| `MultilineBlockBracketsOnSameColumn` | `false` |
| `NewlineBetweenTypeDefinitionAndMembers` | `false` |
| `KeepIfThenInSameLine` | `false` |
| `StrictMode` | `false` |

**Comment by nojaf** [comment]
@Bobface I think this will partially also be resolved by #851.
The indentation bug doesn't seem to appear there when I tested this locally.

The question would then remain what to do with the
```
    new(
        looooooooooooong1: string,
```
part...

**Comment by Bobface** [comment]
@nojaf Tested with #851 and indeed that fixes the problem. Regarding the formatting, I am not sure how the F#-Styleguide handles that situation but most languages do

```
new(looooooooooooong1: string,
    looooooooooooong2: string,
    looooooooooooong3: string) = {  }
```

**Comment by nojaf** [comment]
Fantomas 3.3 formats this as:
```fsharp
type SomeType =
    new(looooooooooooong1: string, looooooooooooong2: string,
        looooooooooooong3: string) = {  }
```

so I would go with your proposal.

Side question: I'm not familiar with the `{ }` part, can there be code in there as well?

**Comment by Bobface** [comment]
@nojaf As a newbie in F# I will have to redirect that question to @knocte :)

**Comment by knocte** [comment]
I'm not very familiar with it either, because it's very related to the OOP-parts of F# (which I try to avoid; but it's kinda unavoidable when you're dealing with exceptions and the need to derive from `System.Exception`). I got all my (short)knowledge about this from the docs IIRC, example: https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/inheritance#constructors-and-inheritance

**Comment by knocte** [comment]
> @nojaf Tested with #851 and indeed that fixes the problem.

That PR was merged so this can be closed?

**Comment by nojaf** [comment]
@knocte that PR only fixed the indentation issue.

I would like to see:
```fsharp
type SomeType =
    new(
        looooooooooooong1: string,
        looooooooooooong2: string,
        looooooooooooong3: string) = {  }
```
change to
```fsharp
type SomeType =
    new(looooooooooooong1: string,
        looooooooooooong2: string,
        looooooooooooong3: string) = {  }
```

**Comment by nojaf** [comment]
I believe this as a whole is fixed by now. (See [online tool](https://fsprojects.github.io/fantomas-tools/#/fantomas/preview?data=N4KABGBEDGD2AmBTSAuKAXAngB0WAyrALaIAqOeAvADoBO1AdhBA4gO4AUANrL3-3wYBzAIxoAzuloBLYQBowPActjCATBKmyhCpSv7CAzJpnCAlGBr0mzW8DqNbtgL4OGbrLgLFEAeXQAFoi05F5WjsysbGAcAIYm2haUYMDOkHLgUOKI6Oja4qhgANqZEKBOUAAknshokLLo6aXMkJUAbrFcAK61xc22AAwZFRCQAJIMSAzo%2BNIAXsjDIwAs-WAAus3OS2VrrTWF9dNNFa0d3b0lI2AiO06QALKxAB4AMrKIr4jCgScjABwDNabFx3cr3aoUQ4AI14XD%2BtjOnR6hSuIzUd0R%2BEQRGkcB4DAAgugAKKTXwAM3erARTgpnWywK2YL2kNwMLhtNG7WRlzWEEMmJa%2BGwsWgiAAQogKbBaIgAAqxWixEjoYJc5hSHpM0HNcGItm9SCw2DwoVIi6o-lgZZC0YisWS6Wyz6wNjBaCxbITNqwT15VQaiBaxA65jbPWsg51E1m1nnFFoNEVACsdqgDvFUplcoAqthcLRPd6GL7-dJA%2Bn6VxGRUQeGWadDRzTRqLYm%2BtcAGzpyCZp05xAAYS4XvEQ9UkloXWg6FlQbA1drTnrEAjdijUJjnPNPMtSetAHZe-3sy6HjjoeqqwzQ3XmZGm9GoLG23uO8mnP8T6Ks865ROBILkud4rg%2BG5PluL47vGvJWtcACcP6OoSFJqrQE5EEQsQLiGYZro2ELPsaMFNgmfLXCIQzWn2v4Di62K4vilbWiB%2BFgOuzD6i0zbbq2u7kfBIwiLcNH9qh6GMXiposdceH3rqEFEVBJH8bB%2B6dsJGI0RMUzoL4DCkLQmAAOrSL8N41qBtirhxhEGsRr4CXBB6UYKYl0YStCwF0kwACKIFw0i4uhuHTtZzC2ZxuyQeydQNG%2BgmucJto0U8zxjBSpBBAwJJWfgASyugZnwBZ1rLECCkNo%2BylxVACXORpn62CIaZpS8EwUtIzy%2BIWsRzrQJLPNgcriOIFYMAuKaVWBilcZudVHI0jUftaIg9u1zwAEqIHAtDwCVZXXBV7HRSkC1Gg16mrZRx6bV5yqYL4tDvJIh0BAuJ1VQRNUOSpV1kS5mkVCI36bQAaryEqyPA2jvZ9M02eB82xZdxwrRRwlIZtABivmzhN0OTHD0ilR96ZfbN1VKX9i1OddmMVGo1HXI8XRcHkQWsBKPDQAA1hKyr8zk4gGfgKrDqaXREJNlnLkjc0xbVRr04DTXWmoomswAcuwXNOug7rfKEiABV1DDmRNhKTBeRBXrQBRyxFEBRfZPGOaREJJcDThqNprMANKIIg2CZdl3wTOLJDUosrG3qdbvcsRANe0DzXMGo7ms%2BleW4uIATwxTiORcjSu0yrnsGt76cQGoqWs7MwhcIgXlCNL3zFYg0IPAgsfXGx312b97sqarqfq9cahtazhJBUIDB4wwBOqLM8-9V0cqkLAukd-1E3AfHg9ndxSej5XPHVxrG0zxzwQMHvbSusItv22bsiW5OB9WQnw%2Bn3T5-ckvpPO6DctCzh7kgL%2B8sS4uEyOsJY9RxA43GoUNizggA)).
Please reopen if something still doesn't add up.
